export type ReadingTokenType = "vocab" | "kanji" | "grammar" | "punctuation";

export interface ReadingToken {
  surface: string;
  reading?: string;
  meaning?: string;
  dictKey?: string;
  type: ReadingTokenType;
  addToSrs: boolean;
  tappable: boolean;
}

export interface ReadingPassage {
  id: string;
  title: string;
  titleJa: string;
  translation: string;
  tokens: ReadingToken[];
}

const word = (surface: string, reading: string, meaning: string, dictKey = surface): ReadingToken => ({
  surface,
  reading,
  meaning,
  dictKey,
  type: "vocab",
  addToSrs: true,
  tappable: true,
});

const grammar = (surface: string, reading: string, meaning: string): ReadingToken => ({
  surface,
  reading,
  meaning,
  type: "grammar",
  addToSrs: false,
  tappable: true,
});

const punctuation = (surface: string): ReadingToken => ({
  surface,
  type: "punctuation",
  addToSrs: false,
  tappable: false,
});

export const SEED_READING_PASSAGES: ReadingPassage[] = [
  {
    id: "morning-walk",
    title: "A Morning Routine & Walk",
    titleJa: "朝の日課と散歩",
    translation:
      "Every morning, I wake up at six. First, I open the window and drink fresh cold water. Today the morning weather is very clear and nice. I put on my shoes and walk along the calm park to the station. On the way, I meet my friendly neighbor and say good morning. Small green birds are singing cheerfully in the tall trees. I buy warm green tea at the shop near the station entrance. Today also begins as a wonderful and peaceful day.",
    tokens: [
      word("私", "わたし", "I"),
      grammar("は", "は", "topic marker"),
      word("毎朝", "まいあさ", "every morning"),
      word("六時", "ろくじ", "six o'clock"),
      grammar("に", "に", "at / on"),
      word("起きます", "おきます", "wake up", "起きる"),
      punctuation("。"),

      word("まず", "まず", "first of all"),
      punctuation("、"),
      word("窓", "まど", "window"),
      grammar("を", "を", "object marker"),
      word("開けて", "あけて", "open and", "開ける"),
      punctuation("、"),
      word("冷たい", "つめたい", "cold"),
      word("水", "みず", "water"),
      grammar("を", "を", "object marker"),
      word("飲みます", "のみます", "drink", "飲む"),
      punctuation("。"),

      word("今日", "きょう", "today"),
      grammar("は", "は", "topic marker"),
      word("朝", "あさ", "morning"),
      grammar("の", "の", "of"),
      word("天気", "てんき", "weather"),
      grammar("が", "が", "subject marker"),
      word("とても", "とても", "very"),
      word("いい", "いい", "good"),
      grammar("です", "です", "is / polite ending"),
      punctuation("。"),

      word("靴", "くつ", "shoes"),
      grammar("を", "を", "object marker"),
      word("履いて", "はいて", "put on / wear", "履く"),
      punctuation("、"),
      word("静かな", "しずかな", "quiet"),
      word("公園", "こうえん", "park"),
      grammar("を", "を", "through"),
      word("通って", "とおって", "pass through", "通る"),
      word("駅", "えき", "station"),
      grammar("まで", "まで", "up to / as far as"),
      word("歩きます", "あるきます", "walk", "歩く"),
      punctuation("。"),

      word("道", "みち", "path / road"),
      grammar("で", "で", "on / at"),
      word("親切な", "しんせつな", "kind / friendly"),
      word("隣の人", "となりのひと", "neighbor"),
      grammar("に", "に", "to / with"),
      word("会って", "あって", "meet and", "会う"),
      punctuation("、"),
      word("挨拶", "あいさつ", "greeting"),
      grammar("を", "を", "object marker"),
      word("します", "します", "do / make", "する"),
      punctuation("。"),

      word("高い", "たかい", "tall / high"),
      word("木", "き", "tree"),
      grammar("の", "の", "of"),
      word("上", "うえ", "top / above"),
      grammar("で", "で", "at / in"),
      word("小さな", "ちいさな", "small"),
      word("鳥", "とり", "bird"),
      grammar("が", "が", "subject marker"),
      word("歌って", "うたって", "singing", "歌う"),
      word("います", "います", "is (continuous)", "いる"),
      punctuation("。"),

      word("駅", "えき", "station"),
      grammar("の", "の", "of"),
      word("前", "まえ", "in front of"),
      grammar("の", "の", "of"),
      word("店", "みせ", "shop"),
      grammar("で", "で", "at"),
      word("温かい", "あたたかい", "warm"),
      word("お茶", "おちゃ", "green tea"),
      grammar("を", "を", "object marker"),
      word("買います", "かいます", "buy", "買う"),
      punctuation("。"),

      word("今日も", "きょうも", "today also"),
      word("素晴らしい", "すばらしい", "wonderful"),
      word("一日", "いちにち", "one day"),
      grammar("が", "が", "subject marker"),
      word("始まります", "はじまります", "begins", "始まる"),
      punctuation("。"),
    ],
  },
  {
    id: "library-book",
    title: "An Afternoon at the Library",
    titleJa: "図書館で過ごす午後",
    translation:
      "On Sunday afternoon, I go to the big library in the center of town. Inside the library, it is quiet and full of many books. I find a comfortable chair next to the large sunlit window. I picked up an interesting Japanese history book and began reading. Reading kanji slowly takes time, but learning is very fun. When I do not know a new word, I look it up in my dictionary. I also write down useful phrases in my notebook. Before returning home, I borrowed three new books.",
    tokens: [
      word("日曜日", "にちようび", "Sunday"),
      grammar("の", "の", "of"),
      word("午後", "ごご", "afternoon"),
      punctuation("、"),
      word("町", "まち", "town"),
      grammar("の", "の", "of"),
      word("大きな", "おおきな", "big / large"),
      word("図書館", "としょかん", "library"),
      grammar("へ", "へ", "toward"),
      word("行きます", "いきます", "go", "行く"),
      punctuation("。"),

      word("館内", "かんない", "inside the library"),
      grammar("は", "は", "topic marker"),
      word("とても", "とても", "very"),
      word("静か", "しずか", "quiet"),
      grammar("で", "で", "and / is"),
      punctuation("、"),
      word("たくさん", "たくさん", "many / plenty"),
      grammar("の", "の", "of"),
      word("本", "ほん", "book"),
      grammar("が", "が", "subject marker"),
      word("あります", "あります", "there are / exist", "ある"),
      punctuation("。"),

      word("日当たり", "ひあたり", "sunlight"),
      grammar("の", "の", "of"),
      word("良い", "よい", "good / pleasant"),
      word("窓", "まど", "window"),
      grammar("の", "の", "of"),
      word("隣", "となり", "next to"),
      grammar("で", "で", "at"),
      word("椅子", "いす", "chair"),
      grammar("を", "を", "object marker"),
      word("見つけました", "みつけました", "found", "見つける"),
      punctuation("。"),

      word("面白い", "おもしろい", "interesting"),
      word("日本語", "にほんご", "Japanese language"),
      grammar("の", "の", "of"),
      word("歴史", "れきし", "history"),
      grammar("の", "の", "of"),
      word("本", "ほん", "book"),
      grammar("を", "を", "object marker"),
      word("読み始めます", "よみはじめます", "begin reading", "読み始める"),
      punctuation("。"),

      word("漢字", "かんじ", "kanji"),
      grammar("を", "を", "object marker"),
      word("ゆっくり", "ゆっくり", "slowly"),
      word("読む", "よむ", "read"),
      grammar("の", "の", "nominalizer"),
      grammar("は", "は", "topic marker"),
      word("時間", "じかん", "time"),
      grammar("が", "が", "subject marker"),
      word("かかります", "かかります", "takes (time)", "かかる"),
      punctuation("。"),

      word("しかし", "しかし", "however"),
      punctuation("、"),
      word("新しい", "あたらしい", "new"),
      word("こと", "こと", "thing / matter"),
      grammar("を", "を", "object marker"),
      word("学ぶ", "まなぶ", "learn"),
      grammar("の", "の", "nominalizer"),
      grammar("は", "は", "topic marker"),
      word("楽しい", "たのしい", "fun / enjoyable"),
      grammar("です", "です", "is / polite ending"),
      punctuation("。"),

      word("分からない", "わからない", "do not know / understand", "分かる"),
      word("言葉", "ことば", "word"),
      grammar("は", "は", "topic marker"),
      word("辞書", "じしょ", "dictionary"),
      grammar("で", "で", "with / using"),
      word("調べます", "しらべます", "look up / check", "調べる"),
      punctuation("。"),

      word("ノート", "のーと", "notebook"),
      grammar("に", "に", "in / on"),
      word("大切な", "たいせつな", "important"),
      word("表現", "ひょうげん", "expression"),
      grammar("を", "を", "object marker"),
      word("書きます", "かきます", "write", "書く"),
      punctuation("。"),

      word("家", "いえ", "home"),
      grammar("へ", "へ", "toward"),
      word("帰る", "かえる", "return"),
      word("前", "まえ", "before"),
      grammar("に", "に", "at"),
      punctuation("、"),
      word("本", "ほん", "book"),
      grammar("を", "を", "object marker"),
      word("三冊", "さんさつ", "three books (counter)"),
      word("借りました", "かりました", "borrowed", "借りる"),
      punctuation("。"),
    ],
  },
  {
    id: "weather-and-tea",
    title: "A Cozy Rainy Afternoon",
    titleJa: "雨の日の静かな午後",
    translation:
      "Today, it has been raining gently outside since this morning. The sound of rain hitting the window is very peaceful and soothing. I turned on a warm lamp inside my cozy room. I brewed hot fragrant green tea in my ceramic cup. While listening to the rain, I practice writing Japanese kanji. Astra-chan rests quietly beside my desk and reads a spell book. Hot steam rises gently from the cup into the air. Spending time quietly at home like this is a real treat.",
    tokens: [
      word("今日", "きょう", "today"),
      grammar("は", "は", "topic marker"),
      word("朝", "あさ", "morning"),
      grammar("から", "から", "from / since"),
      word("静かに", "しずかに", "gently / quietly"),
      word("雨", "あめ", "rain"),
      grammar("が", "が", "subject marker"),
      word("降って", "ふって", "falling", "降る"),
      word("います", "います", "is (continuous)", "いる"),
      punctuation("。"),

      word("窓", "まど", "window"),
      grammar("を", "を", "object marker"),
      word("打つ", "うつ", "hitting / tapping"),
      word("雨音", "あまおと", "sound of rain"),
      grammar("は", "は", "topic marker"),
      word("心を", "こころを", "the heart / mind"),
      word("落ち着かせます", "おちつかせます", "calms / soothes", "落ち着かせる"),
      punctuation("。"),

      word("部屋", "へや", "room"),
      grammar("の", "の", "of"),
      word("中", "なか", "inside"),
      grammar("で", "で", "in / at"),
      word("温かい", "あたたかい", "warm"),
      word("ランプ", "らんぷ", "lamp"),
      grammar("を", "を", "object marker"),
      word("つけました", "つけました", "turned on", "つける"),
      punctuation("。"),

      word("お気に入り", "おきにいり", "favorite"),
      grammar("の", "の", "of"),
      word("カップ", "かっぷ", "cup"),
      grammar("で", "で", "with / in"),
      word("美味しい", "おいしい", "delicious"),
      word("お茶", "おちゃ", "tea"),
      grammar("を", "を", "object marker"),
      word("淹れます", "いれます", "brew / make", "淹れる"),
      punctuation("。"),

      word("雨", "あめ", "rain"),
      grammar("の", "の", "of"),
      word("音", "おと", "sound"),
      grammar("を", "を", "object marker"),
      word("聴きながら", "ききながら", "while listening", "聴く"),
      punctuation("、"),
      word("漢字", "かんじ", "kanji"),
      grammar("の", "の", "of"),
      word("練習", "れんしゅう", "practice"),
      grammar("を", "を", "object marker"),
      word("します", "します", "do", "する"),
      punctuation("。"),

      word("アストラちゃん", "あすとらちゃん", "Astra-chan"),
      grammar("も", "も", "also"),
      word("机", "つくえ", "desk"),
      grammar("の", "の", "of"),
      word("横", "よこ", "side / next to"),
      grammar("で", "で", "at"),
      word("本", "ほん", "book"),
      grammar("を", "を", "object marker"),
      word("読んで", "よんで", "reading", "読む"),
      word("います", "います", "is (continuous)", "いる"),
      punctuation("。"),

      word("温かい", "あたたかい", "warm"),
      word("湯気", "ゆげ", "steam"),
      grammar("が", "が", "subject marker"),
      word("ふわふわ", "ふわふわ", "softly / gently"),
      grammar("と", "と", "with / like"),
      word("立ち上ります", "たちのぼります", "rises up", "立ち上る"),
      punctuation("。"),

      word("家", "いえ", "home"),
      grammar("で", "で", "at"),
      word("ゆっくり", "ゆっくり", "leisurely"),
      word("過ごす", "すごす", "spend (time)"),
      word("時間", "じかん", "time"),
      grammar("は", "は", "topic marker"),
      word("とても", "とても", "very"),
      word("幸せ", "しあわせ", "happy / peaceful"),
      grammar("です", "です", "is / polite ending"),
      punctuation("。"),
    ],
  },
  {
    id: "weekend-food",
    title: "A Weekend Meal with Friends",
    titleJa: "友達と楽しむ週末の食事",
    translation:
      "On Saturday evening, I met my good friend at the station plaza. We walked together into a lively traditional Japanese noodle shop. The shop was bustling with delicious smells of dashi broth. I ordered warm tempura udon, and my friend ordered tonkatsu ramen. The broth was rich, and the noodles were fresh and chewy. We talked happily about our Japanese studies and future travel plans. After eating, we enjoyed sweet matcha ice cream together. It was a deeply memorable and happy weekend evening.",
    tokens: [
      word("土曜日", "どようび", "Saturday"),
      grammar("の", "の", "of"),
      word("夕方", "ゆうがた", "evening"),
      punctuation("、"),
      word("駅", "えき", "station"),
      grammar("の", "の", "of"),
      word("広場", "ひろば", "plaza"),
      grammar("で", "で", "at"),
      word("友達", "ともだち", "friend"),
      grammar("と", "と", "with"),
      word("待ち合わせました", "まちあわせました", "met up", "待ち合わせる"),
      punctuation("。"),

      word("二人", "ふたり", "two people / together"),
      grammar("で", "で", "as"),
      word("賑やかな", "にぎやかな", "lively"),
      word("和食", "わしょく", "Japanese cuisine"),
      grammar("の", "の", "of"),
      word("店", "みせ", "shop / restaurant"),
      grammar("へ", "へ", "toward"),
      word("入りました", "はいりました", "entered", "入る"),
      punctuation("。"),

      word("店", "みせ", "shop"),
      grammar("の", "の", "of"),
      word("中", "なか", "inside"),
      grammar("は", "は", "topic marker"),
      word("美味しい", "おいしい", "delicious"),
      word("出汁", "だし", "soup stock / dashi"),
      grammar("の", "の", "of"),
      word("いい", "いい", "good"),
      word("匂い", "におい", "smell / aroma"),
      grammar("が", "が", "subject marker"),
      word("します", "します", "makes / has"),
      punctuation("。"),

      word("私", "わたし", "I"),
      grammar("は", "は", "topic marker"),
      word("天ぷら", "てんぷら", "tempura"),
      word("うどん", "うどん", "udon"),
      grammar("を", "を", "object marker"),
      punctuation("、"),
      word("友達", "ともだち", "friend"),
      grammar("は", "は", "topic marker"),
      word("ラーメン", "らーめん", "ramen"),
      grammar("を", "を", "object marker"),
      word("注文しました", "ちゅうもんしました", "ordered", "注文する"),
      punctuation("。"),

      word("スープ", "すーぷ", "soup / broth"),
      grammar("は", "は", "topic marker"),
      word("温かく", "あたたかく", "warm and", "温かい"),
      word("深い", "ふかい", "deep / rich"),
      word("味", "あじ", "flavor / taste"),
      grammar("が", "が", "subject marker"),
      word("しました", "しました", "had (taste)", "する"),
      punctuation("。"),

      word("食事", "しょくじ", "meal"),
      grammar("を", "を", "object marker"),
      word("しながら", "しながら", "while doing", "する"),
      punctuation("、"),
      word("日本語", "にほんご", "Japanese language"),
      grammar("の", "の", "of"),
      word("勉強", "べんきょう", "study"),
      grammar("や", "や", "and (non-exhaustive)"),
      word("旅行", "りょこう", "travel"),
      grammar("の", "の", "of"),
      word("話", "はなし", "talk / conversation"),
      grammar("を", "を", "object marker"),
      word("たくさん", "たくさん", "a lot"),
      word("しました", "しました", "did / made", "する"),
      punctuation("。"),

      word("最後", "さいご", "at the end"),
      grammar("に", "に", "at"),
      word("甘い", "あまい", "sweet"),
      word("抹茶", "まっちゃ", "matcha"),
      word("アイス", "あいす", "ice cream"),
      grammar("も", "も", "also"),
      word("食べました", "たべました", "ate", "食べる"),
      punctuation("。"),

      word("とても", "とても", "very"),
      word("楽しくて", "たのしくて", "fun and", "楽しい"),
      word("満足な", "まんぞくな", "satisfying"),
      word("夜", "よる", "night / evening"),
      grammar("でした", "でした", "was / polite past"),
      punctuation("。"),
    ],
  },
  {
    id: "new-class",
    title: "My New Japanese Classroom",
    titleJa: "新しい日本語の教室",
    translation:
      "Today was the first day of our new Japanese class. There are fifteen eager students from different countries studying together. Our teacher is always kind, smiling, and teaches with great patience. In the classroom, we practiced self-introductions and daily greetings. Everyone listened attentively to each other and practiced speaking out loud. After class ended, we exchanged phone numbers and made study plans. I look forward to coming to class again tomorrow.",
    tokens: [
      word("今日", "きょう", "today"),
      grammar("は", "は", "topic marker"),
      word("新しい", "あたらしい", "new"),
      word("日本語", "にほんご", "Japanese language"),
      word("クラス", "くらす", "class"),
      grammar("の", "の", "of"),
      word("最初", "さいしょ", "first"),
      grammar("の", "の", "of"),
      word("日", "ひ", "day"),
      grammar("でした", "でした", "was / polite past"),
      punctuation("。"),

      word("世界中", "せかいじゅう", "around the world"),
      grammar("から", "から", "from"),
      word("十五人", "じゅうごにん", "fifteen people"),
      grammar("の", "の", "of"),
      word("学生", "がくせい", "student"),
      grammar("が", "が", "subject marker"),
      word("集まりました", "あつまりました", "gathered", "集まる"),
      punctuation("。"),

      word("先生", "せんせい", "teacher"),
      grammar("は", "は", "topic marker"),
      word("いつも", "いつも", "always"),
      word("親切", "しんせつ", "kind"),
      grammar("で", "で", "and / is"),
      punctuation("、"),
      word("笑顔", "えがお", "smiling face"),
      grammar("で", "で", "with"),
      word("丁寧に", "ていねいに", "patiently / politely"),
      word("教えて", "おしえて", "teaches", "教える"),
      word("くれます", "くれます", "gives (favor)", "くれる"),
      punctuation("。"),

      word("教室", "きょうしつ", "classroom"),
      grammar("で", "で", "in"),
      word("自己紹介", "じこしょうかい", "self introduction"),
      grammar("と", "と", "and"),
      word("挨拶", "あいさつ", "greeting"),
      grammar("の", "の", "of"),
      word("練習", "れんしゅう", "practice"),
      grammar("を", "を", "object marker"),
      word("しました", "しました", "did", "する"),
      punctuation("。"),

      word("みんな", "みんな", "everyone"),
      word("真剣に", "しんけんに", "attentively / seriously"),
      word("声", "こえ", "voice"),
      grammar("を", "を", "object marker"),
      word("出して", "だして", "speak out", "出す"),
      word("話しました", "はなしました", "spoke", "話す"),
      punctuation("。"),

      word("授業", "じゅぎょう", "lesson / class"),
      grammar("の", "の", "of"),
      word("後", "あと", "after"),
      punctuation("、"),
      word("連絡先", "れんらくさき", "contact info"),
      grammar("を", "を", "object marker"),
      word("交換しました", "こうかんしました", "exchanged", "交換する"),
      punctuation("。"),

      word("明日", "あした", "tomorrow"),
      grammar("の", "の", "of"),
      word("授業", "じゅぎょう", "class"),
      grammar("も", "も", "also"),
      word("今", "いま", "now"),
      grammar("から", "から", "from"),
      word("とても", "とても", "very"),
      word("楽しみ", "たのしみ", "looking forward to"),
      grammar("です", "です", "is / polite ending"),
      punctuation("。"),
    ],
  },
];

export function getPassageText(passage: ReadingPassage): string {
  return passage.tokens.map((token) => token.surface).join("");
}
