/*
 * KanjiVG stroke data for 下 (U+4E0B) — release 20260714, source file kanji/04e0b.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "下",
  code: "04e0b",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M13.25,22.5c0.94,0.23,5.18,0.96,7.74,0.75c17.87-1.5,46.54-4.75,66.38-4.75c2.92,0,6.42,0.75,7.88,1.25", type: "㇐", start: [13.25, 22.5], end: [95.25, 19.75], dir: -2, endDir: 19, len: 82.4, num: [6.5, 22.63], part: 0 },
    { n: 2, d: "M52.97,23.25c0.93,1.07,1.56,2.75,1.56,5.3c0,8.65-0.2,39.42-0.27,57.2c-0.02,3.86-0.02,5.89-0.02,8.25", type: "㇑", start: [52.97, 23.25], end: [54.24, 94], dir: 89, endDir: 90, len: 71.1, num: [46.75, 33.13], part: 1 },
    { n: 3, d: "M67.83,37.17C72.75,39.5,79.88,47.62,82,52.12", type: "㇔", start: [67.83, 37.17], end: [82, 52.12], dir: 47, endDir: 65, len: 20.9, num: [62.5, 32.13], part: 1 },
  ],
  parts: [
    { element: "一", radical: "general" },
    { element: "卜" },
  ],
};

export default data;
