/*
 * KanjiVG stroke data for 上 (U+4E0A) — release 20260714, source file kanji/04e0a.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "上",
  code: "04e0a",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M52.31,15.88c1.15,1.15,2.01,3.12,2.01,5.12c0,0.82-0.22,63.62-0.25,64.63", type: "㇑a", start: [52.31, 15.88], end: [54.07, 85.63], dir: 89, endDir: 92, len: 70.3, num: [43.5, 16.28], part: 0 },
    { n: 2, d: "M58,44.75c7-0.62,14.25-2.5,17.75-3c1.38-0.2,3.5-0.38,4.75,0", type: "㇐b/㇔", start: [58, 44.75], end: [80.5, 41.75], dir: -8, endDir: 17, len: 22.8, num: [60.25, 41.5], part: 0 },
    { n: 3, d: "M13.38,88.28c3.6,1.15,7.45,0.62,11.13,0.34c16.23-1.23,41.16-2.66,60.24-2.92c3.65-0.05,7.47-0.32,11,0.82", type: "㇐", start: [13.38, 88.28], end: [95.75, 86.52], dir: -1, endDir: 18, len: 82.6, num: [5.5, 88.5], part: 1 },
  ],
  parts: [
    { element: "卜", radical: "nelson" },
    { element: "一", radical: "tradit" },
  ],
};

export default data;
