/*
 * KanjiVG stroke data for 三 (U+4E09) — release 20260714, source file kanji/04e09.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "三",
  code: "04e09",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M27.5,23.65c3.09,0.73,6.29,0.36,9.4,0.06c10.2-1,27-2.94,38.97-3.57c3.06-0.16,6.09-0.2,9.14,0.23", type: "㇐", start: [27.5, 23.65], end: [85.01, 20.37], dir: -3, endDir: 8, len: 57.7, num: [18, 25.78], part: 0 },
    { n: 2, d: "M28.75,55.14c3.13,0.76,6.46,0.43,9.64,0.2c10.03-0.72,23.97-2.63,34.73-3.12c2.7-0.12,5.45-0.16,8.13,0.3", type: "㇐", start: [28.75, 55.14], end: [81.25, 52.52], dir: -3, endDir: 10, len: 52.7, num: [18.75, 57.13], part: 2 },
    { n: 3, d: "M13,87.83c3.94,1.01,7.72,0.96,11.75,0.72c18.41-1.07,41.27-3.39,61.12-4.07c3.63-0.13,7.2-0.1,10.75,0.78", type: "㇐", start: [13, 87.83], end: [96.62, 85.26], dir: -2, endDir: 14, len: 83.9, num: [3.75, 91.63], part: 3 },
  ],
  parts: [
    { element: "一", position: "top", radical: "general" },
    { position: "bottom" },
    { element: "一", parent: 1 },
    { element: "一", parent: 1 },
  ],
};

export default data;
