/*
 * KanjiVG stroke data for 一 (U+4E00) — release 20260714, source file kanji/04e00.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "一",
  code: "04e00",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M11,54.25c3.19,0.62,6.25,0.75,9.73,0.5c20.64-1.5,50.39-5.12,68.58-5.24c3.6-0.02,5.77,0.24,7.57,0.49", type: "㇐", start: [11, 54.25], end: [96.88, 50], dir: -3, endDir: 8, len: 86.2, num: [4.25, 54.13] },
  ],
  parts: [

  ],
};

export default data;
