/*
 * KanjiVG stroke data for 万 (U+4E07) — release 20260714, source file kanji/04e07.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "万",
  code: "04e07",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M14.38,24.73c2.3,0.54,6.52,0.78,8.81,0.54c21.57-2.27,44.44-5.64,64.9-5.98c3.83-0.06,6.12,0.26,8.04,0.53", type: "㇐", start: [14.38, 24.73], end: [96.13, 19.82], dir: -3, endDir: 8, len: 82.1, num: [7.5, 26.5], part: 0 },
    { n: 2, d: "M51,41.5c1.45,0.7,3.19,1.43,5.19,1.74c7.31,1.14,17.05,1.94,22.64,1.5c4.64-0.37,6.38,1.08,5.17,4.73C77.88,68,72.75,78.75,63.87,90.4c-7.6,9.97-10.12,3.22-12.62,0.2", type: "㇆", start: [51, 41.5], end: [51.25, 90.6], dir: 90, endDir: -130, len: 100, num: [57.5, 41.5] },
    { n: 3, d: "M51.75,25.5c0.5,2,0.22,3.78-0.21,5.89C48.95,43.8,34.75,73.38,13.56,87.97", type: "㇒", start: [51.75, 25.5], end: [13.56, 87.97], dir: 121, endDir: 145, len: 75.3, num: [43.5, 33.5] },
  ],
  parts: [
    { element: "一", radical: "general" },
  ],
};

export default data;
