/*
 * KanjiVG stroke data for 七 (U+4E03) — release 20260714, source file kanji/04e03.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "七",
  code: "04e03",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M15.5,51.75c1.82,0.5,4.38,0.88,6.96,0.5c16.91-2.45,50.92-8.12,64.44-8.74c3.02-0.14,4.84,0.24,6.35,0.49", type: "㇐", start: [15.5, 51.75], end: [93.25, 44], dir: -6, endDir: 9, len: 78.5, num: [8.5, 53.5], part: 0 },
    { n: 2, d: "M43,20c1.38,1.38,2.15,3.25,2.15,5.26C45.15,29.5,45,71.84,45,76c0,10.5,2.25,12.25,20.25,12.25c18.75,0,20-3.75,20-2.75", type: "㇄", start: [43, 20], end: [85.25, 85.5], dir: 57, endDir: 90, len: 105.4, num: [34.5, 19.63], part: 1 },
  ],
  parts: [
    { element: "一", radical: "tradit" },
    { element: "乙", radical: "nelson" },
  ],
};

export default data;
