/*
 * KanjiVG stroke data for 中 (U+4E2D) — release 20260714, source file kanji/04e2d.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "中",
  code: "04e2d",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M19.89,36.87c1,1,1.74,2.25,2.01,3.65c1.13,5.71,2.58,13.06,4.17,22.97c0.27,1.68,0.55,4.43,0.83,6.26", type: "㇑", start: [19.89, 36.87], end: [26.9, 69.75], dir: 78, endDir: 81, len: 33.9, num: [14.5, 45.13], part: 0 },
    { n: 2, d: "M23.33,39.51C37.12,37.62,70.88,34,84,33.24c4.38-0.25,6,1.14,5.12,4.42c-1.53,5.7-5.61,20.18-6.12,22.09", type: "㇕b", start: [23.33, 39.51], end: [83, 59.75], dir: 19, endDir: 105, len: 92.4, num: [24.5, 35.5], part: 0 },
    { n: 3, d: "M27.74,64.84C40.12,63.62,61.86,62.2,79,60.77c2.36-0.2,5.75-0.27,7.25-0.27", type: "㇐b", start: [27.74, 64.84], end: [86.25, 60.5], dir: -4, endDir: 0, len: 58.7, num: [30.5, 60.75], part: 0 },
    { n: 4, d: "M52.5,11.5c1.44,1.44,2.25,3.5,2.25,5.06c0,0.9,0.06,56.6-0.15,76.69c-0.03,3.3-0.07,5.6-0.1,6.5", type: "㇑", start: [52.5, 11.5], end: [54.5, 99.75], dir: 89, endDir: 92, len: 88.9, num: [43.5, 12.5], part: 1 },
  ],
  parts: [
    { element: "口" },
    { element: "丨", radical: "general" },
  ],
};

export default data;
