/*
 * KanjiVG stroke data for 九 (U+4E5D) — release 20260714, source file kanji/04e5d.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "九",
  code: "04e5d",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M41.88,14.38c1,1.38,1.5,3.25,1.5,5.12c0,40.13-9.12,57.5-28.5,68.75", type: "㇒", start: [41.88, 14.38], end: [14.88, 88.25], dir: 110, endDir: 150, len: 84, num: [32.5, 14.5], part: 0 },
    { n: 2, d: "M13.5,45.75c2.88,0.85,5.78,0.05,8.58-0.66c8.47-2.14,39.88-9.79,40.92-9.84c2.5-0.12,4.75,0.5,4.25,4.75c-0.5,4.25-5.5,20.75-7,32.5c-2.23,17.46,2,19.37,18.21,19.37c13.79,0,19.01-1.07,19.27-10.12", type: "㇈", start: [13.5, 45.75], end: [97.73, 81.75], dir: 23, endDir: -88, len: 150.5, num: [5.5, 46.63], part: 1 },
  ],
  parts: [
    { element: "丿", radical: "nelson" },
    { element: "乙", radical: "tradit" },
  ],
};

export default data;
