/*
 * KanjiVG stroke data for 乗 (U+4E57) — release 20260714, source file kanji/04e57.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "乗",
  code: "04e57",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M68.21,10.39c-0.33,0.98-0.83,1.61-1.87,2.11c-4.32,2.09-17.96,6.87-33.78,9.72", type: "㇒", start: [68.21, 10.39], end: [32.56, 22.22], dir: 162, endDir: 170, len: 38.1, num: [58.5, 9.5], part: 1 },
    { n: 2, d: "M24,32.7c2.01,0.54,5.71,0.51,7.71,0.29c14.85-1.62,30.99-3.62,45-4.23c3.35-0.15,5.36,0.26,7.04,0.53", type: "㇐", start: [24, 32.7], end: [83.75, 29.29], dir: -3, endDir: 9, len: 60, num: [16.5, 33.5], part: 2 },
    { n: 3, d: "M14.5,47.95c2.47,0.54,7,0.46,9.46,0.29c16.04-1.12,39.16-3.62,59.27-4.48c4.11-0.18,6.58,0.26,8.64,0.53", type: "㇐", start: [14.5, 47.95], end: [91.87, 44.29], dir: -3, endDir: 7, len: 77.6, num: [7.5, 48.5] },
    { n: 4, d: "M34.81,36.63c1.28,1.28,1.82,2.13,2.01,3.5c0.93,6.62,1.53,16.82,1.93,21.12", type: "㇑a", start: [34.81, 36.63], end: [38.75, 61.25], dir: 81, endDir: 85, len: 25.3, num: [27.75, 42.5] },
    { n: 5, d: "M72.81,32.63c0.9,0.9,1.11,2.6,1.01,3.5C73.25,41.38,72,51.75,70.25,59", type: "㇑a", start: [72.81, 32.63], end: [70.25, 59], dir: 96, endDir: 104, len: 26.9, num: [65.5, 39.5] },
    { n: 6, d: "M24,62.05c2.09,0.58,5.92,0.47,8,0.31c10.56-0.79,32.6-3.2,49.69-3.72c3.48-0.11,5.57,0.28,7.31,0.56", type: "㇐", start: [24, 62.05], end: [89, 59.2], dir: -3, endDir: 9, len: 65.2, num: [17.25, 63.5], part: 3 },
    { n: 7, d: "M52.56,20.13c0.84,0.84,1.51,2.62,1.51,4.25c0,4.61,0,48.92,0,66.99c0,2.98,0,5.25,0,6.51", type: "㇑", start: [52.56, 20.13], end: [54.07, 97.88], dir: 89, endDir: 90, len: 78.1, num: [46.5, 27.5], part: 5 },
    { n: 8, d: "M50.75,61.25c0,0.62-0.7,1.85-1.41,2.81C42.35,73.56,28.38,85.46,17,90.5", type: "㇒", start: [50.75, 61.25], end: [17, 90.5], dir: 139, endDir: 156, len: 45.3, num: [34.5, 71.5], part: 3 },
    { n: 9, d: "M56.5,61.5c4.2,3.45,19.42,17.95,27.52,23.46c2.64,1.8,5.19,3.54,7.85,4.41", type: "㇏", start: [56.5, 61.5], end: [91.87, 89.37], dir: 38, endDir: 18, len: 45.2, num: [69.5, 69.5], part: 3 },
  ],
  parts: [
    { element: "千", part: "1" },
    { element: "丿", radical: "general", parent: 0 },
    { element: "十", part: "1", parent: 0 },
    { element: "木" },
    { element: "千", part: "2", parent: 3 },
    { element: "十", part: "2", parent: 4 },
  ],
};

export default data;
