/*
 * KanjiVG stroke data for 二 (U+4E8C) — release 20260714, source file kanji/04e8c.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "二",
  code: "04e8c",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M25.25,32.4c1.77,0.37,4.78,0.56,6.55,0.37c10.82-1.15,28.82-3.4,41.24-3.76c2.95-0.09,4.73,0.18,6.21,0.36", type: "㇐", start: [25.25, 32.4], end: [79.25, 29.37], dir: -3, endDir: 7, len: 54.2, num: [17.5, 33.13], part: 0 },
    { n: 2, d: "M12,80.75c2.37,0.5,6.73,0.67,9.09,0.5c23.79-1.75,45.04-4.12,67.49-4.74c3.95-0.11,6.32,0.24,8.3,0.49", type: "㇐", start: [12, 80.75], end: [96.88, 77], dir: -3, endDir: 7, len: 85.1, num: [3.5, 81.5], part: 1 },
  ],
  parts: [
    { position: "top" },
    { position: "bottom" },
  ],
};

export default data;
