/*
 * KanjiVG stroke data for 五 (U+4E94) — release 20260714, source file kanji/04e94.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "五",
  code: "04e94",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M31.75,23.15c2.8,0.67,5.54,0.42,8.36,0.12c9.3-0.99,22.18-2.4,34.14-3.21c2.49-0.17,5.04-0.33,7.5,0.2", type: "㇐", start: [31.75, 23.15], end: [81.75, 20.26], dir: -3, endDir: 12, len: 50.2, num: [24.5, 24.13], part: 1 },
    { n: 2, d: "M55.75,25.25c0.62,1.25,1.02,3.01,0.5,5c-3.12,11.88-14,44.12-19.75,59", type: "㇑a", start: [55.75, 25.25], end: [36.5, 89.25], dir: 107, endDir: 111, len: 67.4, num: [47.5, 33.5] },
    { n: 3, d: "M25.5,55.25c2.07,1.24,4.73,1.03,7,0.81c15.49-1.45,29.89-3.03,42.25-4.06c3-0.25,4.25,1.75,3.5,3.75c-2.24,5.96-6,20.75-7.75,31.5", type: "㇕c", start: [25.5, 55.25], end: [70.5, 87.25], dir: 35, endDir: 99, len: 88.4, num: [18.5, 57.5] },
    { n: 4, d: "M11.25,90.5c3.04,0.81,6.52,0.63,9.63,0.41c15.71-1.1,43.9-2.8,67.75-3.8c3.41-0.14,6.9-0.4,10.25,0.39", type: "㇐", start: [11.25, 90.5], end: [98.88, 87.5], dir: -2, endDir: 13, len: 87.8, num: [3.5, 91.5], part: 2 },
  ],
  parts: [
    { element: "二", radical: "tradit", part: "1" },
    { element: "一", radical: "nelson", parent: 0 },
    { element: "二", radical: "tradit", part: "2" },
  ],
};

export default data;
