/*
 * KanjiVG stroke data for 人 (U+4EBA) — release 20260714, source file kanji/04eba.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "人",
  code: "04eba",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M54.5,20c0.37,2.12,0.23,4.03-0.22,6.27C51.68,39.48,38.25,72.25,16.5,87.25", type: "㇒", start: [54.5, 20], end: [16.5, 87.25], dir: 119, endDir: 145, len: 79.4, num: [45.5, 19.5] },
    { n: 2, d: "M46,54.25c6.12,6,25.51,22.24,35.52,29.72c3.66,2.73,6.94,4.64,11.48,5.53", type: "㇏", start: [46, 54.25], end: [93, 89.5], dir: 37, endDir: 11, len: 59.2, num: [52.5, 55.63] },
  ],
  parts: [

  ],
};

export default data;
