/*
 * KanjiVG stroke data for 今 (U+4ECA) — release 20260714, source file kanji/04eca.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "今",
  code: "04eca",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M49.42,14.25c0.1,1.11-0.11,2.93-0.71,4.47C44.5,29.5,32,47.25,11.5,61.75", type: "㇒", start: [49.42, 14.25], end: [11.5, 61.75], dir: 129, endDir: 145, len: 62.1, num: [41.5, 13.5], part: 0 },
    { n: 2, d: "M50.66,18.99c6.1,7.28,32.37,31.03,39.1,36.36c2.28,1.81,5.21,2.58,7.49,3.09", type: "㇏", start: [50.66, 18.99], end: [97.25, 58.44], dir: 40, endDir: 13, len: 61.6, num: [58.5, 22.63], part: 0 },
    { n: 3, d: "M39.23,50.26c1.27,0.24,2.64,0.37,4.13,0.18c5.39-0.68,11.02-1.69,15.86-2.31c1.8-0.23,3.66-0.38,4.8-0.08", type: "㇐", start: [39.23, 50.26], end: [64.02, 48.05], dir: -5, endDir: 15, len: 25, num: [38.5, 47.5], part: 2 },
    { n: 4, d: "M33.25,67.75c2.12,0.38,3.57,0.61,6,0.25c6.31-0.93,18.5-3.25,25.24-4.44C68.48,62.85,70,65,68,68.75C63.33,77.5,58.75,85,53,94.5", type: "㇇", start: [33.25, 67.75], end: [53, 94.5], dir: 54, endDir: 121, len: 70.3, num: [25.5, 69.5], part: 1 },
  ],
  parts: [
    { element: "人", position: "top", radical: "general" },
    { position: "bottom" },
    { element: "一", parent: 1 },
  ],
};

export default data;
