/*
 * KanjiVG stroke data for 休 (U+4F11) — release 20260714, source file kanji/04f11.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "休",
  code: "04f11",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M35,16.5c0.25,1.75,0.25,4.25-0.88,6.8C28.91,35.01,22.37,46.02,10.5,60.29", type: "㇒", start: [35, 16.5], end: [10.5, 60.29], dir: 119, endDir: 130, len: 51, num: [25.5, 15.5], part: 0 },
    { n: 2, d: "M26.28,42.5c0.72,1.25,1.26,3.48,1.26,4.75c0,12.75-0.07,29.88-0.26,42.25c-0.02,1.54-0.04,2.97-0.04,4.25", type: "㇑", start: [26.28, 42.5], end: [27.24, 93.75], dir: 89, endDir: 90, len: 51.5, num: [20.5, 58.5], part: 0 },
    { n: 3, d: "M37.65,38.83c2.45,0.97,5.18,0.75,7.73,0.54c11.76-0.97,24.94-3.35,37.49-4.01c2.65-0.14,5.39-0.22,7.99,0.39", type: "㇐", start: [37.65, 38.83], end: [90.86, 35.75], dir: -3, endDir: 13, len: 53.6, num: [38.5, 36.5], part: 1 },
    { n: 4, d: "M61.43,14c0.82,0.75,1.87,2.12,1.87,3.7c0,8.8,0.05,53.72-0.12,72.05c-0.03,2.88-0.06,4.91-0.08,5.75", type: "㇑", start: [61.43, 14], end: [63.1, 95.5], dir: 89, endDir: 91, len: 82.1, num: [52.5, 14.5], part: 1 },
    { n: 5, d: "M62.43,38.32c0,2.18-1.1,4.31-1.9,6.04C54.57,57.4,44.96,71.84,35,78.75", type: "㇒", start: [62.43, 38.32], end: [35, 78.75], dir: 124, endDir: 145, len: 49.7, num: [50.5, 49.5], part: 1 },
    { n: 6, d: "M64.12,38.08c4.45,8.37,16.21,25.33,24.99,33.19c1.96,1.76,4.35,4.18,6.9,5", type: "㇏", start: [64.12, 38.08], end: [96.01, 76.27], dir: 50, endDir: 18, len: 50.3, num: [73.5, 48.5], part: 1 },
  ],
  parts: [
    { element: "亻", position: "left", radical: "general" },
    { element: "木", position: "right" },
  ],
};

export default data;
