/*
 * KanjiVG stroke data for 会 (U+4F1A) — release 20260714, source file kanji/04f1a.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "会",
  code: "04f1a",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M52.25,14c0.25,2.28-0.52,3.59-1.8,5.62c-5.76,9.14-17.9,27-39.2,39.88", type: "㇒", start: [52.25, 14], end: [11.25, 59.5], dir: 132, endDir: 149, len: 62.5, num: [44.25, 10.63], part: 0 },
    { n: 2, d: "M54.5,19.25c6.73,7.3,24.09,24.81,32.95,31.91c2.73,2.18,5.61,3.8,9.05,4.59", type: "㇏", start: [54.5, 19.25], end: [96.5, 55.75], dir: 41, endDir: 13, len: 56.1, num: [60.75, 21.13], part: 0 },
    { n: 3, d: "M37.36,50.16c1.64,0.34,4.04,0.36,4.98,0.25c6.79-0.79,14.29-1.91,19.66-2.4c1.56-0.14,3.25-0.39,4.66,0", type: "㇐", start: [37.36, 50.16], end: [66.66, 48.01], dir: -4, endDir: 15, len: 29.5, num: [39.75, 46.63], part: 2 },
    { n: 4, d: "M23,65.98c2.12,0.52,4.25,0.64,7.01,0.3c13.77-1.71,30.99-3.66,46.35-3.74c3.04-0.02,4.87,0.14,6.4,0.29", type: "㇐", start: [23, 65.98], end: [82.76, 62.83], dir: -3, endDir: 6, len: 60, num: [23.25, 63.13], part: 2 },
    { n: 5, d: "M47.16,66.38c0.62,1.65-0.03,2.93-0.92,4.28c-5.17,7.8-8.02,11.38-14.99,18.84c-2.11,2.25-1.5,4.18,2,3.75c7.35-0.91,28.19-5.83,40.16-7.95", type: "㇜", start: [47.16, 66.38], end: [73.41, 85.3], dir: 36, endDir: -10, len: 76.3, num: [33.75, 76.63], part: 3 },
    { n: 6, d: "M66.62,77.39c4.52,3.23,11,12.73,13.06,18.82", type: "㇔", start: [66.62, 77.39], end: [79.68, 96.21], dir: 55, endDir: 71, len: 23.2, num: [69.75, 76.63], part: 3 },
  ],
  parts: [
    { element: "人", position: "top", radical: "general" },
    { element: "云", position: "bottom" },
    { element: "二", parent: 1 },
    { element: "厶", parent: 1 },
  ],
};

export default data;
