/*
 * KanjiVG stroke data for 何 (U+4F55) — release 20260714, source file kanji/04f55.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "何",
  code: "04f55",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M32.5,13.75c0.23,2.1-0.19,3.81-0.8,5.66c-3.95,11.84-9.67,23.37-20.45,37.34", type: "㇒", start: [32.5, 13.75], end: [11.25, 56.75], dir: 116, endDir: 128, len: 48.6, num: [24.5, 13.5], part: 0 },
    { n: 2, d: "M26.76,36.5c1.24,1.5,1.54,3.04,1.54,5.5c0,9.46-0.13,30.79-0.17,44.62c-0.01,2.6-0.01,4.94-0.01,6.88", type: "㇑", start: [26.76, 36.5], end: [28.12, 93.5], dir: 89, endDir: 90, len: 57.3, num: [20.5, 55.5], part: 0 },
    { n: 3, d: "M38.88,26.64c1.74,0.5,4.68,0.67,6.41,0.5c13.21-1.27,33.84-4.77,46.26-5.86c2.88-0.25,4.63,0.24,6.08,0.49", type: "㇐", start: [38.88, 26.64], end: [97.63, 21.77], dir: -5, endDir: 10, len: 59.2, num: [42.75, 24.5], part: 3 },
    { n: 4, d: "M40.87,44c0.75,0.75,1.26,1.62,1.36,2.21c0.67,4.06,1.44,10.16,2.25,16.3c0.27,2.04,0.26,2.01,0.47,3.75", type: "㇑", start: [40.87, 44], end: [44.95, 66.26], dir: 80, endDir: 83, len: 22.9, num: [35.5, 52.63], part: 4 },
    { n: 5, d: "M43.27,45.6c6.28-1.17,15.14-2.97,19.73-3.72c3.13-0.51,4.4,0.31,3.68,3.51c-0.86,3.86-2.49,10.33-3.28,14.14", type: "㇕b", start: [43.27, 45.6], end: [63.4, 59.53], dir: 35, endDir: 102, len: 41.3, num: [44.25, 42.13], part: 4 },
    { n: 6, d: "M45.59,63.17c3.71-0.39,9.45-1.24,14.45-1.85c1.89-0.23,3.82-0.47,5.75-0.69", type: "㇐b", start: [45.59, 63.17], end: [65.79, 60.63], dir: -7, endDir: -7, len: 20.4, num: [48.75, 59.5], part: 4 },
    { n: 7, d: "M83.25,24.75c1,1,1.74,2.18,1.81,4.99c0.33,13.52-0.21,56.44-0.21,61.04c0,10.71-6.35,2.71-9.18-0.77", type: "㇚", start: [83.25, 24.75], end: [75.67, 90.01], dir: 97, endDir: -129, len: 82.4, num: [76.5, 34.63], part: 6 },
  ],
  parts: [
    { element: "亻", position: "left", radical: "general" },
    { element: "可", position: "right" },
    { element: "丁", part: "1", parent: 1 },
    { element: "一", parent: 2 },
    { element: "口", parent: 1 },
    { element: "丁", part: "2", parent: 1 },
    { element: "亅", parent: 5 },
  ],
};

export default data;
