/*
 * KanjiVG stroke data for 体 (U+4F53) — release 20260714, source file kanji/04f53.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "体",
  code: "04f53",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M31.75,16.25c0.23,2.15-0.05,3.95-0.8,5.78C26.88,32,21,45.88,9.12,60", type: "㇒", start: [31.75, 16.25], end: [9.12, 60], dir: 117, endDir: 130, len: 49.9, num: [23.25, 12.13], part: 0 },
    { n: 2, d: "M23.78,42.75c1.11,1.11,1.23,2.89,1.31,4.49c0.46,10.12-0.23,30.08-0.5,41.01c-0.06,2.38-0.09,4.36-0.09,5.75", type: "㇑", start: [23.78, 42.75], end: [24.5, 94], dir: 89, endDir: 90, len: 51.6, num: [17.25, 63.13], part: 0 },
    { n: 3, d: "M37.28,36.89c0.95,0.24,3.21,0.59,5.72,0.36c11.97-1.12,30.25-4,42.78-4.7c2.52-0.14,4.42,0.01,6,0.25", type: "㇐", start: [37.28, 36.89], end: [91.78, 32.8], dir: -4, endDir: 9, len: 54.8, num: [36.75, 33.13], part: 2 },
    { n: 4, d: "M61.88,12c1.06,1.06,1.6,2.75,1.6,4.38c0,0.85,0.05,55.5-0.12,74.13c-0.03,2.9-0.05,4.93-0.08,5.74", type: "㇑", start: [61.88, 12], end: [63.28, 96.25], dir: 89, endDir: 92, len: 84.6, num: [56.25, 7.63], part: 2 },
    { n: 5, d: "M61.88,36.37c0,1.38-0.51,2.64-0.94,3.49C55.07,51.39,42.61,66.29,32.5,72.5", type: "㇒", start: [61.88, 36.37], end: [32.5, 72.5], dir: 129, endDir: 148, len: 47.4, num: [47.25, 48.13], part: 2 },
    { n: 6, d: "M64.38,36.75c3.77,7.25,17.11,24.4,23.75,30.78c1.71,1.64,3.85,3.76,6.13,4.47", type: "㇏", start: [64.38, 36.75], end: [94.26, 72], dir: 50, endDir: 17, len: 46.6, num: [75.75, 46.63], part: 2 },
    { n: 7, d: "M46.54,74.65c1.23,0.29,3.48,0.39,4.71,0.29c10.8-0.93,17.26-2.18,24.7-2.46c2.05-0.08,3.28,0.14,4.3,0.28", type: "㇐", start: [46.54, 74.65], end: [80.25, 72.76], dir: -3, endDir: 8, len: 33.9, num: [39.75, 81.13], part: 1 },
  ],
  parts: [
    { element: "亻", position: "left", radical: "general" },
    { element: "本", position: "right" },
    { element: "木", parent: 1 },
  ],
};

export default data;
