/*
 * KanjiVG stroke data for 使 (U+4F7F) — release 20260714, source file kanji/04f7f.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "使",
  code: "04f7f",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M32.51,18.25c0.23,1.89-0.06,4.11-0.8,5.73C27.03,34.28,21.12,45,10.38,56.5", type: "㇒", start: [32.51, 18.25], end: [10.38, 56.5], dir: 120, endDir: 133, len: 44.9, num: [24.5, 18.13], part: 0 },
    { n: 2, d: "M24.53,42.75c0.92,0.92,1.75,2.5,1.74,3.75c-0.03,10.66-0.2,32.7-0.26,44.5C26.01,93.55,26,95.62,26,97", type: "㇑", start: [24.53, 42.75], end: [26, 97], dir: 88, endDir: 90, len: 54.7, num: [18.5, 58.5], part: 0 },
    { n: 3, d: "M44,30.64c1.42,0.38,4.04,0.3,5.45,0.13c8.43-1.02,21.93-2.77,31.57-3.63c2.35-0.21,3.79,0.18,4.98,0.37", type: "㇐", start: [44, 30.64], end: [86, 27.51], dir: -4, endDir: 9, len: 42.3, num: [44.25, 27.13], part: 3 },
    { n: 4, d: "M42.5,43.19c1.12,0.56,1.99,1.94,2.17,2.75c0.79,3.66,1.69,8.6,2.48,13.44c0.17,1.04,0.33,2.08,0.49,3.09", type: "㇑", start: [42.5, 43.19], end: [47.64, 62.47], dir: 75, endDir: 81, len: 20.4, num: [37.5, 51.5], part: 4 },
    { n: 5, d: "M45.57,44.79c8.26-1.22,27.06-3.54,36.45-4.38c4.37-0.39,5.86,1.84,4.52,5.21c-1.45,3.66-2.44,5.85-4.3,10.81", type: "㇕b", start: [45.57, 44.79], end: [82.24, 56.43], dir: 18, endDir: 111, len: 57.3, num: [45.5, 41.5], part: 4 },
    { n: 6, d: "M48.26,59.6c4.73-0.44,22.73-1.85,32.87-2.44c1.7-0.1,3.17-0.18,4.33-0.22", type: "㇐b", start: [48.26, 59.6], end: [85.46, 56.94], dir: -4, endDir: -2, len: 37.3, num: [51.5, 56.5], part: 4 },
    { n: 7, d: "M63.38,12.93c1.22,1.22,1.39,2.57,1.44,4.82C66,70,66.62,81.25,36.75,95", type: "㇒", start: [63.38, 12.93], end: [36.75, 95], dir: 108, endDir: 155, len: 95, num: [56.5, 13.5], part: 7 },
    { n: 8, d: "M44,67.88c7.25,0.38,28.04,16.2,40.84,22.59c2.52,1.25,4.41,2.29,7.54,3.04", type: "㇏", start: [44, 67.88], end: [92.38, 93.51], dir: 28, endDir: 13, len: 55, num: [36.75, 69.13], part: 6 },
  ],
  parts: [
    { element: "亻", position: "left", radical: "general" },
    { element: "吏", position: "right" },
    { element: "丈", part: "1", parent: 1 },
    { element: "一", parent: 2 },
    { element: "口", parent: 1 },
    { element: "丈", part: "2", parent: 1 },
    { element: "乂", parent: 5 },
    { element: "丿", parent: 6 },
  ],
};

export default data;
