/*
 * KanjiVG stroke data for 働 (U+50CD) — release 20260714, source file kanji/050cd.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "働",
  code: "050cd",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M29.5,17c0.25,1.35,0.25,2.7-0.24,4C24.7,32.98,18.88,47.23,9,60.29", type: "㇒", start: [29.5, 17], end: [9, 60.29], dir: 115, endDir: 127, len: 48.4, num: [20.25, 18.13], part: 0 },
    { n: 2, d: "M21.78,43.5c0.73,0.73,1,1.97,1,3.12c0,10.4-0.02,29.95-0.03,41c0,2.58,0,4.69,0,6.12", type: "㇑", start: [21.78, 43.5], end: [22.75, 93.74], dir: 89, endDir: 90, len: 50.5, num: [15.75, 61.63], part: 0 },
    { n: 3, d: "M58.89,13.26c-0.02,1.11-0.41,1.84-1.27,2.72c-2.51,2.56-10.37,6.88-21.52,10.78", type: "㇒", start: [58.89, 13.26], end: [36.1, 26.76], dir: 149, endDir: 161, len: 27.3, num: [49.5, 13.48], part: 4 },
    { n: 4, d: "M30.22,35.31c1.51,0.19,3.54,0.23,4.81,0.1c10.52-1.04,20.28-2.42,30.05-3.23c2.08-0.17,3.35,0.14,4.39,0.35", type: "㇐", start: [30.22, 35.31], end: [69.47, 32.53], dir: -4, endDir: 11, len: 39.5, num: [30.75, 33.13], part: 5 },
    { n: 5, d: "M34.12,45.15c0.87,0.87,1.27,1.88,1.43,2.72c0.83,3.78,1.62,9.21,2.17,14.51c0.11,1.06,0.21,2.12,0.3,3.16", type: "㇑", start: [34.12, 45.15], end: [38.02, 65.54], dir: 79, endDir: 85, len: 21, num: [29.25, 55.63], part: 6 },
    { n: 6, d: "M36.13,46.05c7.57-1.21,19.25-2.43,25.82-3.06c2.1-0.2,3.67,0.98,3.38,2.91c-0.49,3.24-1.45,8.35-2.72,13.87c-0.24,1.04-0.49,2.09-0.75,3.15", type: "㇕a", start: [36.13, 46.05], end: [61.86, 62.92], dir: 33, endDir: 104, len: 48.6, num: [36.75, 43.63], part: 6 },
    { n: 7, d: "M38.26,54.64c5.24-0.64,20.12-2.26,24.57-2.4", type: "㇐a", start: [38.26, 54.64], end: [62.83, 52.24], dir: -6, endDir: -2, len: 24.7, num: [41.25, 52.5], part: 6 },
    { n: 8, d: "M39.38,64.09c6.12-0.84,13-1.59,21.48-2.21", type: "㇐a", start: [39.38, 64.09], end: [60.86, 61.88], dir: -6, endDir: -4, len: 21.6, num: [41.5, 62.5], part: 6 },
    { n: 9, d: "M49.19,24.41c0.76,0.76,1.03,2.09,1.03,3.29c0,0.88-0.14,48.42-0.14,54.39", type: "㇑a", start: [49.19, 24.41], end: [50.08, 82.09], dir: 89, endDir: 90, len: 57.9, num: [43.5, 31.5], part: 8 },
    { n: 10, d: "M34.94,73.71c1.03,0.34,2.98,0.35,4.06,0.2c8-1.16,15.88-2.54,20.26-3.25c1.17-0.19,2.45-0.42,3.64-0.2", type: "㇐", start: [34.94, 73.71], end: [62.9, 70.46], dir: -7, endDir: 10, len: 28.3, num: [26.25, 74.5], part: 6 },
    { n: 11, d: "M32.42,88.36c1.08,0.89,2.71,1.01,4.56,0.28c9.7-3.83,12.81-5.14,23.93-9.61", type: "㇀/㇐", start: [32.42, 88.36], end: [60.91, 79.03], dir: -18, endDir: -22, len: 30.6, num: [26.44, 84.88], part: 6 },
    { n: 12, d: "M72.34,44.06c1.41,0.32,2.64,0.43,3.49,0.33c5.57-0.69,13.03-2.52,17.2-3.34c3.24-0.63,4.39,0.73,4.23,3.99c-0.36,7.5-6.56,38.02-10.38,43.1c-2.93,3.89-3.46,2.15-6.54-0.61", type: "㇆", start: [72.34, 44.06], end: [80.34, 87.53], dir: 80, endDir: -138, len: 81.3, num: [69.75, 40.63], part: 9 },
    { n: 13, d: "M81.76,21.18c0.99,1.32,1.26,2.91,1.19,5.37c-0.58,19.58-6.7,49.2-24.88,67.54", type: "㇒", start: [81.76, 21.18], end: [58.07, 94.09], dir: 108, endDir: 135, len: 79.2, num: [70.5, 20.5], part: 9 },
  ],
  parts: [
    { element: "亻", position: "left", radical: "general" },
    { element: "動", position: "right" },
    { element: "重", position: "left", parent: 1 },
    { element: "千", part: "1", parent: 2 },
    { element: "丿", parent: 3 },
    { element: "十", part: "1", parent: 3 },
    { element: "里", parent: 2 },
    { element: "千", part: "2", parent: 6 },
    { element: "十", part: "2", parent: 7 },
    { element: "力", position: "right", parent: 1 },
  ],
};

export default data;
