/*
 * KanjiVG stroke data for 先 (U+5148) — release 20260714, source file kanji/05148.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "先",
  code: "05148",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M37.51,21c0.07,0.62,0.15,1.61-0.14,2.49C35.25,29.88,31.62,37.38,24.5,45", type: "㇒", start: [37.51, 21], end: [24.5, 45], dir: 118, endDir: 133, len: 27.8, num: [29.5, 20.13], part: 0 },
    { n: 2, d: "M38.13,32.04c1.5,0.09,3.95-0.16,4.64-0.22c6.48-0.57,20.36-1.82,27.82-2.94c1.65-0.25,3.66-0.13,5.16,0.27", type: "㇐", start: [38.13, 32.04], end: [75.75, 29.15], dir: -4, endDir: 15, len: 37.8, num: [42.5, 28.5], part: 0 },
    { n: 3, d: "M52.81,12.38c1.28,1.28,2.01,3.12,2.01,4.75c0,0.75-0.05,31.92-0.07,32.87", type: "㇑a", start: [52.81, 12.38], end: [54.75, 50], dir: 87, endDir: 91, len: 38.2, num: [43.5, 11.5], part: 0 },
    { n: 4, d: "M15.88,53.26c3.42,0.98,7.15,0.5,10.62,0.22c15.99-1.3,38.99-3.55,59-4.4c2.94-0.13,5.84-0.03,8.75,0.47", type: "㇐", start: [15.88, 53.26], end: [94.25, 49.55], dir: -3, endDir: 10, len: 78.6, num: [7.5, 54.5], part: 0 },
    { n: 5, d: "M45.18,55.68c0.32,1.45,0.15,2.48-0.15,3.85C43.24,67.65,35,86.62,20,96.38", type: "㇒", start: [45.18, 55.68], end: [20, 96.38], dir: 122, endDir: 147, len: 49.4, num: [36.75, 62.13], part: 2 },
    { n: 6, d: "M60.49,53.62c1.07,1.07,1.38,2.71,1.38,4.98c0,7.78-0.22,14.88-0.22,21.89c0,15.14,1.1,16.04,15.85,16.04c14.62,0,15.64-1.78,15.64-11.29", type: "㇟", start: [60.49, 53.62], end: [93.14, 85.24], dir: 44, endDir: -90, len: 78.8, num: [53.5, 65.5], part: 1 },
  ],
  parts: [
    { position: "top" },
    { element: "儿", position: "bottom", radical: "general" },
    { element: "丿", parent: 1 },
  ],
};

export default data;
