/*
 * KanjiVG stroke data for 兄 (U+5144) — release 20260714, source file kanji/05144.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "兄",
  code: "05144",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M28.24,20.33c0.96,0.96,1.51,2.17,1.72,3.33c0.73,4.23,2.35,13.89,3.5,22.34c0.16,1.16,0.32,2.29,0.48,3.38", type: "㇑", start: [28.24, 20.33], end: [33.94, 49.38], dir: 79, endDir: 82, len: 29.8, num: [23.5, 28.63], part: 0 },
    { n: 2, d: "M31.29,22.29C43.75,20.38,61,18.12,72,17c2.62-0.27,5,2.25,4.5,4.67c-0.99,4.8-4.27,14.16-5.61,19.85", type: "㇕b", start: [31.29, 22.29], end: [70.89, 41.52], dir: 26, endDir: 103, len: 69.1, num: [30.5, 18.5], part: 0 },
    { n: 3, d: "M34.5,45.88c6.96-0.45,23.37-2.05,34.45-3.18c1.48-0.15,2.8-0.07,4.17-0.13", type: "㇐b", start: [34.5, 45.88], end: [73.12, 42.57], dir: -5, endDir: -3, len: 38.8, num: [36.62, 42.75], part: 0 },
    { n: 4, d: "M43.49,53.25c0.26,1.38,0.2,2.51-0.15,4.1C41.56,65.48,32.5,84.25,17.75,94", type: "㇒", start: [43.49, 53.25], end: [17.75, 94], dir: 122, endDir: 147, len: 49.7, num: [35.5, 58.5], part: 2 },
    { n: 5, d: "M55.99,48.12c0.88,0.88,1.74,2.63,1.74,4.64c0,6.72-0.12,16.9-0.12,25.23c0,14.25,0.63,15.23,16.89,15.23c16.87,0,17.63-1.72,17.63-11.85", type: "㇟", start: [55.99, 48.12], end: [92.13, 81.37], dir: 43, endDir: -90, len: 84.7, num: [50.5, 56.5], part: 1 },
  ],
  parts: [
    { element: "口", position: "top", radical: "nelson" },
    { element: "儿", position: "bottom", radical: "tradit" },
    { element: "丿", parent: 1 },
  ],
};

export default data;
