/*
 * KanjiVG stroke data for 元 (U+5143) — release 20260714, source file kanji/05143.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "元",
  code: "05143",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M28.59,21.36c1.78,0.33,5.04,0.48,6.82,0.33c10.84-0.94,21.52-2.57,32.08-3.03c2.96-0.13,4.75,0.16,6.23,0.32", type: "㇐", start: [28.59, 21.36], end: [73.72, 18.98], dir: -3, endDir: 6, len: 45.3, num: [20.25, 21.13], part: 0 },
    { n: 2, d: "M16.13,44.06c2.16,0.47,5.88,0.62,8.04,0.47c18.08-1.27,36.71-3.9,56.39-4.5c3.6-0.11,5.77,0.22,7.57,0.46", type: "㇐", start: [16.13, 44.06], end: [88.13, 40.49], dir: -3, endDir: 8, len: 72.2, num: [8.25, 45.13], part: 0 },
    { n: 3, d: "M41.29,46.69c0.59,1.18,0.74,2.97,0.36,4.44c-2.9,11.36-8.78,27.99-25.4,41.36", type: "㇒", start: [41.29, 46.69], end: [16.25, 92.49], dir: 119, endDir: 141, len: 54, num: [32.25, 54.13], part: 2 },
    { n: 4, d: "M56.7,44.12c1.53,1.53,2,3.11,2,5.66c0,9.59,0.01,19.49,0.01,27.97c0,14.38,1.03,15.62,18.28,15.62c14.88,0,16.14-1.12,16.14-12.69", type: "㇟", start: [56.7, 44.12], end: [93.13, 80.68], dir: 45, endDir: -90, len: 89.4, num: [50.25, 54.13], part: 1 },
  ],
  parts: [
    { element: "二", position: "top", radical: "nelson" },
    { element: "儿", position: "bottom", radical: "tradit" },
    { element: "丿", parent: 1 },
  ],
};

export default data;
