/*
 * KanjiVG stroke data for 入 (U+5165) — release 20260714, source file kanji/05165.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "入",
  code: "05165",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M54.75,48.75c-0.5,2-1.1,3.2-2.07,4.62C44.22,65.8,27.98,81.44,14.5,88", type: "㇒", start: [54.75, 48.75], end: [14.5, 88], dir: 136, endDir: 154, len: 57.1, num: [45, 51] },
    { n: 2, d: "M36.5,20c8.25,1.38,15.12,34,48.81,62.08c2.71,2.26,5.56,4.8,9.44,6.42", type: "㇏", start: [36.5, 20], end: [94.75, 88.5], dir: 50, endDir: 23, len: 91.2, num: [28.5, 21] },
  ],
  parts: [

  ],
};

export default data;
