/*
 * KanjiVG stroke data for 八 (U+516B) — release 20260714, source file kanji/0516b.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "八",
  code: "0516b",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M37.22,45c0.28,1.5,0.2,3.21-0.86,5.48c-4.23,9.02-11.48,20.4-24.1,32.02", type: "㇒", start: [37.22, 45], end: [12.26, 82.5], dir: 124, endDir: 137, len: 46, num: [27.75, 42.13], part: 0 },
    { n: 2, d: "M48,27.25c9.38,0.25,21.12,30,37.27,45.72c3.79,3.69,6.73,5.66,9.98,7.03", type: "㇏", start: [48, 27.25], end: [95.25, 80], dir: 48, endDir: 23, len: 72.1, num: [51.75, 22.63], part: 1 },
  ],
  parts: [
    { position: "left" },
    { position: "right" },
  ],
};

export default data;
