/*
 * KanjiVG stroke data for 六 (U+516D) — release 20260714, source file kanji/0516d.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "六",
  code: "0516d",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M51.87,17.5c1.78,1.78,2.71,3.48,2.71,6.5c0,6.46,0.12,9.16,0.12,14.35", type: "㇑a", start: [51.87, 17.5], end: [54.7, 38.35], dir: 82, endDir: 90, len: 21.6, num: [42.25, 17.63], part: 0 },
    { n: 2, d: "M13.5,42.13c3.27,0.74,7.11,0.89,9.93,0.64c21.56-1.9,41.78-5.02,61.41-5.47c4.8-0.11,7.49,0.31,11.06,1.07", type: "㇐", start: [13.5, 42.13], end: [95.9, 38.37], dir: -3, endDir: 12, len: 82.8, num: [5.5, 43.63], part: 0 },
    { n: 3, d: "M38.11,58.6c0.51,1.37,0.42,3.67-0.49,5.29C33.38,71.38,24,82.38,15.41,88.75", type: "㇒", start: [38.11, 58.6], end: [15.41, 88.75], dir: 127, endDir: 143, len: 39, num: [27.5, 58.63], part: 1 },
    { n: 4, d: "M70.16,59.92c9.96,8.61,18.18,18.54,23.16,28.99", type: "㇔/㇏", start: [70.16, 59.92], end: [93.32, 88.91], dir: 51, endDir: 65, len: 37.4, num: [60.5, 58.63], part: 1 },
  ],
  parts: [
    { element: "亠", position: "top", radical: "nelson" },
    { element: "八", position: "bottom", radical: "tradit" },
  ],
};

export default data;
