/*
 * KanjiVG stroke data for 円 (U+5186) — release 20260714, source file kanji/05186.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "円",
  code: "05186",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M21.75,19.8c0.91,0.91,1.47,3.23,1.5,5.45c0.2,13.9,0.03,47.69,0.03,62.5c0,2-0.03,4.99-0.03,6", type: "㇑", start: [21.75, 19.8], end: [23.25, 93.75], dir: 89, endDir: 90, len: 74.3, num: [16.5, 28.63], part: 0 },
    { n: 2, d: "M24.06,21.56c15.07-1.68,49.46-5.58,57.92-6.31c2.9-0.25,4.78,1.88,4.78,4.27c0,13.48,0,53.21,0,67.48c0,9.75-4.25,6.5-8.5,1.5", type: "㇆a", start: [24.06, 21.56], end: [78.26, 88.5], dir: 51, endDir: -130, len: 148.3, num: [24.75, 17.5], part: 0 },
    { n: 3, d: "M52.25,20.75c0.88,0.88,1.5,2,1.5,3.71c0,6.76,0,27.54,0,31.04", type: "㇑a", start: [52.25, 20.75], end: [53.75, 55.5], dir: 88, endDir: 90, len: 35.2, num: [45.5, 29.5], part: 1 },
    { n: 4, d: "M24.75,59.75c14.62-1.75,43-4.25,60.5-5.25", type: "㇐a", start: [24.75, 59.75], end: [85.25, 54.5], dir: -5, endDir: -3, len: 60.7, num: [28.5, 56.5], part: 1 },
  ],
  parts: [
    { element: "冂", radical: "general" },
    {  },
  ],
};

export default data;
