/*
 * KanjiVG stroke data for 出 (U+51FA) — release 20260714, source file kanji/051fa.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "出",
  code: "051fa",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M52.76,13.38c1.42,1.42,1.86,2.91,1.86,5.31c0,3.18,0.19,61.81,0.19,68.31", type: "㇑a", start: [52.76, 13.38], end: [54.81, 87], dir: 88, endDir: 90, len: 74.1, num: [42.25, 11.63], part: 1 },
    { n: 2, d: "M29.02,36.13c0.98,1.12,1.23,2.87,1.06,4.04c-0.4,2.82-1.02,7.67-2.78,13.4c-0.43,1.41,0.07,2.84,1.55,2.39c10.61-3.24,33.9-5.33,55.97-6.28", type: "㇄a", start: [29.02, 36.13], end: [84.82, 49.68], dir: 14, endDir: -2, len: 78.1, num: [20.25, 35.63], part: 0 },
    { n: 3, d: "M86.31,30.63c0.94,1.37,1.17,3,0.94,4.87c-0.62,5.12-0.86,7.07-1.66,13.48c-0.15,1.19-0.34,1.9-0.51,3.4", type: "㇑", start: [86.31, 30.63], end: [85.08, 52.38], dir: 93, endDir: 96, len: 22.1, num: [76.75, 29.13], part: 0 },
    { n: 4, d: "M25.27,71.13c1.11,1.11,1.6,2.74,1.31,4.29c-0.53,2.8-1.27,8.92-3.03,14.65c-0.43,1.41,0.57,3.11,2.05,2.64c12.9-4.08,41.9-6.21,59.47-7.03", type: "㇄a", start: [25.27, 71.13], end: [85.07, 85.68], dir: 14, endDir: -3, len: 83.7, num: [16.75, 71.13], part: 2 },
    { n: 5, d: "M85.06,66.88c1.06,1.49,1.56,3.12,1.44,5.37c-0.27,4.8-0.23,9.14-0.45,13.51c-0.08,1.54-0.17,3.17-0.3,4.99", type: "㇑", start: [85.06, 66.88], end: [85.75, 90.75], dir: 88, endDir: 94, len: 24.2, num: [75.75, 67.5], part: 2 },
  ],
  parts: [
    { element: "山" },
    { element: "丨", radical: "nelson", parent: 0 },
    { element: "凵", radical: "tradit" },
  ],
};

export default data;
