/*
 * KanjiVG stroke data for 分 (U+5206) — release 20260714, source file kanji/05206.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "分",
  code: "05206",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M41.12,19.38c0.25,1.24-0.44,3.01-1.1,4.08C34.31,32.72,27.13,40.62,13,51.25", type: "㇒", start: [41.12, 19.38], end: [13, 51.25], dir: 131, endDir: 143, len: 43.3, num: [32.5, 19.5], part: 0 },
    { n: 2, d: "M54.69,13.75c7.56-0.12,20.68,19.17,29.41,25.95c3.07,2.39,6.02,4.05,10.4,5.3", type: "㇏", start: [54.69, 13.75], end: [94.5, 45], dir: 38, endDir: 16, len: 51.5, num: [50.5, 11.5], part: 0 },
    { n: 3, d: "M29.35,55.37c2.42,0.83,4.97,0.75,7.42,0.37c11.06-1.7,28.87-5.3,34.1-5.76c3.69-0.33,5.08,1.48,4.88,3.77c-0.54,6.05-5.94,29.03-10.5,36.3c-4.99,7.96-5.74,4.21-9.84-0.49", type: "㇆", start: [29.35, 55.37], end: [55.41, 89.56], dir: 53, endDir: -131, len: 101.5, num: [30.5, 52.5], part: 1 },
    { n: 4, d: "M49.12,57.25c0.15,1.49,0.06,2.72-0.56,4.08C43.5,72.5,35.75,82,22.5,90.75", type: "㇒", start: [49.12, 57.25], end: [22.5, 90.75], dir: 128, endDir: 147, len: 44, num: [39.5, 65.5], part: 1 },
  ],
  parts: [
    { element: "八", position: "top", radical: "nelson" },
    { element: "刀", position: "bottom", radical: "tradit" },
  ],
};

export default data;
