/*
 * KanjiVG stroke data for 前 (U+524D) — release 20260714, source file kanji/0524d.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "前",
  code: "0524d",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M33.5,14.5c3.34,2.07,8.64,8.5,9.48,11.72", type: "㇔", start: [33.5, 14.5], end: [42.98, 26.22], dir: 51, endDir: 75, len: 15.3, num: [26.25, 13.5], part: 1 },
    { n: 2, d: "M72.67,12c0.26,1.14,0.07,2.23-0.52,3.19c-2.12,3.41-6.02,8.65-8.6,11.31", type: "㇒", start: [72.67, 12], end: [63.55, 26.5], dir: 122, endDir: 134, len: 17.5, num: [63.5, 10.5], part: 1 },
    { n: 3, d: "M13.38,33.24c2.63,0.72,7.46,0.94,10.08,0.72c21.67-1.83,39.8-3.58,62.68-4.61c4.37-0.2,7.01,0.34,9.2,0.7", type: "㇐", start: [13.38, 33.24], end: [95.34, 30.05], dir: -2, endDir: 9, len: 82.2, num: [6.5, 34.5], part: 0 },
    { n: 4, d: "M24.65,45.46c1.1,1.29,1.63,2.92,1.63,4.17c0,3.05,0.1,28.65,0.08,40.62c0,3.23-0.03,5.46-0.1,6", type: "㇑", start: [24.65, 45.46], end: [26.26, 96.25], dir: 88, endDir: 97, len: 51.2, num: [18.5, 52.63], part: 3 },
    { n: 5, d: "M27.01,46.8c2.3-0.41,13.37-2.3,17.2-2.9c2.2-0.34,3.51,1.1,3.51,3.24c0,1.02-0.16,30.82-0.16,44.63c0,5.48-3.79,2.98-5.93,0.53", type: "㇆a", start: [27.01, 46.8], end: [41.63, 92.3], dir: 72, endDir: -131, len: 76.9, num: [27.5, 44.5], part: 3 },
    { n: 6, d: "M27.65,60.01c5.72-0.76,13.63-1.81,18.59-2.32", type: "㇐a", start: [27.65, 60.01], end: [46.24, 57.69], dir: -7, endDir: -6, len: 18.7, num: [29.5, 57.13], part: 3 },
    { n: 7, d: "M27.57,73.47c4.41-0.51,13.3-1.54,18.4-1.89", type: "㇐a", start: [27.57, 73.47], end: [45.97, 71.58], dir: -6, endDir: -4, len: 18.5, num: [29.5, 72.5], part: 3 },
    { n: 8, d: "M62.27,47.58c1.2,1.2,1.76,2.67,1.76,4.58c0,8.93-0.01,15.1-0.09,18.59c-0.04,1.49-0.09,2.76-0.16,4.05", type: "㇑", start: [62.27, 47.58], end: [63.78, 74.8], dir: 87, endDir: 93, len: 27.7, num: [56.25, 45.5], part: 4 },
    { n: 9, d: "M78.85,39.25c1.26,1.26,2.01,2.88,2.01,5.02c0,14.56-0.01,42.91-0.01,47.87c0,8.62-5.96,1-7.46-0.25", type: "㇚", start: [78.85, 39.25], end: [73.39, 91.89], dir: 96, endDir: -140, len: 65.6, num: [70.5, 42.5], part: 4 },
  ],
  parts: [
    { position: "top" },
    { element: "八", radical: "nelson", parent: 0 },
    { position: "bottom" },
    { element: "月", parent: 2 },
    { element: "刂", radical: "tradit", parent: 2 },
  ],
};

export default data;
