/*
 * KanjiVG stroke data for 力 (U+529B) — release 20260714, source file kanji/0529b.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "力",
  code: "0529b",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M21.5,38.25c2.71,1.16,5.48,1.13,8.27,0.71c14.44-2.14,39.36-6.21,53.23-8.21c4.48-0.65,6.25,1.38,5.5,5.75c-2.81,16.37-9,38.75-20,53.25c-6.14,8.09-9.5,3-12.5-0.75", type: "㇆", start: [21.5, 38.25], end: [56, 89], dir: 56, endDir: -129, len: 145.8, num: [14.75, 38.63] },
    { n: 2, d: "M56.88,13.68c0.62,2.57,0.56,4.63,0,7.19c-4.11,18.97-16.53,49.27-43.49,68.79", type: "㇒", start: [56.88, 13.68], end: [13.39, 89.66], dir: 120, endDir: 144, len: 90.4, num: [46.75, 12.13] },
  ],
  parts: [

  ],
};

export default data;
