/*
 * KanjiVG stroke data for 北 (U+5317) — release 20260714, source file kanji/05317.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "北",
  code: "05317",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M13.25,48.75c2.61,0.5,3.52,0.51,6.12,0.25c3.76-0.38,14.13-3.38,17.63-3.75", type: "㇐c", start: [13.25, 48.75], end: [37, 45.25], dir: -8, endDir: -6, len: 24.2, num: [7.5, 51.5], part: 0 },
    { n: 2, d: "M37.25,21.5c1.19,1.19,2,3.25,2,4.75c0,1,0.25,48,0.25,50.75", type: "㇑a", start: [37.25, 21.5], end: [39.5, 77], dir: 88, endDir: 90, len: 56, num: [27.75, 22.5], part: 0 },
    { n: 3, d: "M12.75,88.75c1.88,1.12,4.29,0.87,6.5-0.25C32.5,81.75,36.5,80,43.5,76.25", type: "㇀", start: [12.75, 88.75], end: [43.5, 76.25], dir: -22, endDir: -28, len: 34, num: [3.5, 90.5], part: 0 },
    { n: 4, d: "M90.25,33c-0.25,1.75-1.13,3.26-2.19,4.07C82.12,41.62,73.75,46.5,65,49.75", type: "㇒", start: [90.25, 33], end: [65, 49.75], dir: 146, endDir: 160, len: 31.1, num: [81.5, 32.5], part: 1 },
    { n: 5, d: "M60.37,19.5c1.38,1.5,1.91,3.25,1.91,5.3c0,1.12-0.28,33.71-0.28,47.7c0,14,2,15.75,17.25,15.75c15.5,0,16.5-1.5,16.5-12.49", type: "㇟", start: [60.37, 19.5], end: [95.75, 75.76], dir: 58, endDir: -90, len: 107.6, num: [52.5, 20.5], part: 1 },
  ],
  parts: [
    { position: "left" },
    { element: "匕", position: "right", radical: "general" },
  ],
};

export default data;
