/*
 * KanjiVG stroke data for 半 (U+534A) — release 20260714, source file kanji/0534a.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "半",
  code: "0534a",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M26.02,22.58c3.9,2.41,10.07,9.89,11.04,13.63", type: "㇔", start: [26.02, 22.58], end: [37.06, 36.21], dir: 51, endDir: 75, len: 17.8, num: [19.5, 23.5], part: 0 },
    { n: 2, d: "M82.75,18.75c0.16,1.19-0.39,2.25-1.01,3.2c-2.57,3.96-7.16,8.76-12.62,12.92", type: "㇒", start: [82.75, 18.75], end: [69.12, 34.87], dir: 130, endDir: 143, len: 21.6, num: [73.5, 18.5] },
    { n: 3, d: "M28.3,48.57c1.78,0.38,5.07,0.21,6.83,0.03c10.62-1.09,29.12-2.99,38.5-3.67c2.97-0.22,4.75-0.17,6.24,0.02", type: "㇐", start: [28.3, 48.57], end: [79.87, 44.95], dir: -4, endDir: 7, len: 51.8, num: [21.5, 49.5], part: 1 },
    { n: 4, d: "M13.5,67.22c2.25,0.91,6.85,1.03,9.22,0.78c18.28-1.87,40.4-3.58,62.61-4.38c4-0.14,6.41,0.25,8.42,0.52", type: "㇐", start: [13.5, 67.22], end: [93.75, 64.14], dir: -2, endDir: 8, len: 80.5, num: [5.5, 68.5], part: 3 },
    { n: 5, d: "M52.67,11.5c1.23,1.23,1.85,3.17,1.85,4.4c0,7.6,0.1,54.35,0.1,75.1c0,3.18-0.07,5.46-0.11,6.5", type: "㇑", start: [52.67, 11.5], end: [54.51, 97.5], dir: 89, endDir: 92, len: 86.5, num: [44.5, 12.5], part: 2 },
  ],
  parts: [
    { element: "丶", radical: "nelson" },
    { element: "二", part: "1" },
    { element: "十", radical: "tradit" },
    { element: "二", part: "2", parent: 2 },
  ],
};

export default data;
