/*
 * KanjiVG stroke data for 午 (U+5348) — release 20260714, source file kanji/05348.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "午",
  code: "05348",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M37.5,9.14c0.06,0.7,0.22,1.85-0.11,2.83C35.25,18.25,27,29.62,17.5,39", type: "㇒", start: [37.5, 9.14], end: [17.5, 39], dir: 124, endDir: 135, len: 36.6, num: [29.5, 9.5], part: 1 },
    { n: 2, d: "M32.13,27.28c2.75,0.09,4.3-0.07,5.82-0.21c12.92-1.2,20.78-2.82,33.1-4.68c2.49-0.38,4.69-0.24,5.95,0.03", type: "㇐", start: [32.13, 27.28], end: [77, 22.42], dir: -6, endDir: 12, len: 45.2, num: [40.5, 23.5], part: 2 },
    { n: 3, d: "M13.88,54.53c3,0.72,7.23,0.71,9.74,0.46c19.64-1.99,42.64-4.99,63-6.16c4.22-0.24,6.77,0.22,8.89,0.45", type: "㇐", start: [13.88, 54.53], end: [95.51, 49.28], dir: -4, endDir: 6, len: 82, num: [6.5, 57.5], part: 4 },
    { n: 4, d: "M53.06,28.13c1.03,1.03,1.79,2.37,1.79,4.33c0,0.88-0.02,44.17-0.13,61.04c-0.02,2.88-0.03,4.96-0.05,5.88", type: "㇑", start: [53.06, 28.13], end: [54.67, 99.38], dir: 89, endDir: 91, len: 71.7, num: [46.5, 35.5], part: 4 },
  ],
  parts: [
    { position: "top" },
    { element: "丿", radical: "nelson", parent: 0 },
    { element: "干", part: "1", parent: 0 },
    { element: "干", position: "bottom", part: "2" },
    { element: "十", radical: "tradit", parent: 3 },
  ],
};

export default data;
