/*
 * KanjiVG stroke data for 十 (U+5341) — release 20260714, source file kanji/05341.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "十",
  code: "05341",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M11.88,50.98c3.18,0.89,6.62,0.61,9.87,0.35c19.92-1.58,45.23-4.76,63.38-5.82c3.85-0.23,7.23-0.07,11,0.56", type: "㇐", start: [11.88, 50.98], end: [96.13, 46.07], dir: -3, endDir: 9, len: 84.6, num: [5.5, 52.5] },
    { n: 2, d: "M52.22,11.63c1.4,1.4,2.2,3.96,2.2,6.26c0,1.13-0.03,51.22-0.19,73.41c-0.03,3.96-0.06,6.83-0.08,8.08", type: "㇑", start: [52.22, 11.63], end: [54.15, 99.38], dir: 89, endDir: 91, len: 88.3, num: [42.75, 12.5] },
  ],
  parts: [

  ],
};

export default data;
