/*
 * KanjiVG stroke data for 千 (U+5343) — release 20260714, source file kanji/05343.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "千",
  code: "05343",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M70.38,10.17c-0.13,1.58-0.83,2.64-2.17,3.67c-5.71,4.41-21.46,11.91-41.57,16.82", type: "㇒", start: [70.38, 10.17], end: [26.64, 30.66], dir: 155, endDir: 166, len: 49.5, num: [61.75, 8.13], part: 0 },
    { n: 2, d: "M12.13,50.83c3.36,0.94,7.21,0.75,10.63,0.49c17.76-1.34,37.63-4.16,66.24-4.94c3.08-0.08,6.08-0.14,9.13,0.38", type: "㇐", start: [12.13, 50.83], end: [98.13, 46.76], dir: -3, endDir: 10, len: 86.3, num: [5.25, 52.63], part: 1 },
    { n: 3, d: "M54.56,25.25c1.03,1.03,2.01,3,2.01,5.18c0,0.9-0.07,46.38-0.19,63.58c-0.02,2.93-0.04,5.04-0.06,5.99", type: "㇑", start: [54.56, 25.25], end: [56.32, 100], dir: 89, endDir: 91, len: 75.3, num: [48.5, 35.5], part: 1 },
  ],
  parts: [
    { element: "丿", position: "top", radical: "nelson" },
    { element: "十", position: "bottom", radical: "tradit" },
  ],
};

export default data;
