/*
 * KanjiVG stroke data for 南 (U+5357) — release 20260714, source file kanji/05357.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "南",
  code: "05357",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M27.38,28.25c1.82,0.38,4.2,0.45,7.22,0.2c11.52-0.95,28.37-3.2,40.58-3.7c3.03-0.12,4.92-0.23,6.82,0", type: "㇐", start: [27.38, 28.25], end: [82, 24.75], dir: -4, endDir: 7, len: 54.8, num: [20.5, 29.5], part: 0 },
    { n: 2, d: "M52.35,10.75c0.95,0.95,1.55,2.86,1.55,3.96c0,7.3,0,19.47,0,28.54", type: "㇑a", start: [52.35, 10.75], end: [53.9, 43.25], dir: 87, endDir: 90, len: 32.9, num: [44, 11.63], part: 0 },
    { n: 3, d: "M20.25,45.75c1.25,1.25,1.89,2.74,2,5c0.19,4.06,0.83,27.03,1.12,37.99c0.08,3.23,0.13,5.48,0.13,6.01", type: "㇑", start: [20.25, 45.75], end: [23.5, 94.75], dir: 86, endDir: 90, len: 49.5, num: [14.5, 57.5], part: 2 },
    { n: 4, d: "M22.78,47.6c16.31-1.76,59.32-6.35,60.97-6.35c5,0,6.25,1.62,6.25,6.75c0,5.25-0.25,37.3-0.25,43.05c0,7.7-3.5,6.45-9.5,0.95", type: "㇆a", start: [22.78, 47.6], end: [80.25, 92], dir: 38, endDir: -137, len: 130.3, num: [23.5, 44.5], part: 2 },
    { n: 5, d: "M38.5,49.38c2.58,1.74,6.66,7.14,7.31,9.84", type: "㇔", start: [38.5, 49.38], end: [45.81, 59.22], dir: 53, endDir: 76, len: 12.4, num: [32.5, 55.5], part: 1 },
    { n: 6, d: "M66.25,45.5c0.05,0.89-0.07,1.75-0.37,2.59c-0.8,2.73-2.75,6.92-5.26,9.66", type: "㇒", start: [66.25, 45.5], end: [60.62, 57.75], dir: 115, endDir: 132, len: 13.7, num: [56.25, 52.5], part: 1 },
    { n: 7, d: "M34.78,61.67c1.81,0.39,4.55,0.55,6.36,0.39c9.11-0.8,18.63-1.54,27.63-2.39c2.99-0.28,4.83-0.32,6.33-0.12", type: "㇐", start: [34.78, 61.67], end: [75.1, 59.55], dir: -3, endDir: 8, len: 40.5, num: [28.5, 63.5], part: 3 },
    { n: 8, d: "M33.13,74.19c1.81,0.49,4.55,0.83,6.38,0.74c10.73-0.56,22.66-1.94,31.04-2.66c3-0.26,4.82-0.02,6.33,0.23", type: "㇐", start: [33.13, 74.19], end: [76.88, 72.5], dir: -2, endDir: 9, len: 44, num: [27.5, 71.5], part: 4 },
    { n: 9, d: "M53.5,62.5c0.75,0.75,1,2.14,0.99,3.5c-0.04,6.22-0.15,18.46-0.21,25.26c-0.02,2.19-0.03,3.81-0.03,4.49", type: "㇑", start: [53.5, 62.5], end: [54.25, 95.75], dir: 89, endDir: 90, len: 33.5, num: [47.5, 70.5], part: 4 },
  ],
  parts: [
    { element: "十", position: "top", radical: "general" },
    { position: "bottom" },
    { element: "冂", parent: 1 },
    { element: "干", parent: 1 },
    { element: "十", parent: 3 },
  ],
};

export default data;
