/*
 * KanjiVG stroke data for 友 (U+53CB) — release 20260714, source file kanji/053cb.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "友",
  code: "053cb",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M17.88,37.23c2.13,0.54,5.78,0.58,7.89,0.29c17.48-2.39,35.98-4.39,54.65-5.48c3.54-0.21,5.68,0.01,7.46,0.28", type: "㇐", start: [17.88, 37.23], end: [87.88, 32.32], dir: -4, endDir: 9, len: 70.3, num: [10.5, 38.5], part: 0 },
    { n: 2, d: "M48.22,14.14c0.53,2.11,0.53,4.3,0.31,6.73C47,38,33,72.5,15.5,85.25", type: "㇒", start: [48.22, 14.14], end: [15.5, 85.25], dir: 115, endDir: 144, len: 80.7, num: [38.5, 14.5], part: 0 },
    { n: 3, d: "M42.66,54.86c1.09,0.27,2.51,0.28,3.59,0.14c6.88-0.88,16.62-3.25,22.43-4.88c3.45-0.97,4.6,1.45,3.11,4.55C66.5,65.62,48.12,87.75,24,96.5", type: "㇇", start: [42.66, 54.86], end: [24, 96.5], dir: 114, endDir: 160, len: 99.1, num: [46.5, 51.5], part: 1 },
    { n: 4, d: "M41.25,63.5c5.15,0.45,27.5,18.62,40.93,26.36c3.2,1.84,6.65,3.76,10.32,4.39", type: "㇏", start: [41.25, 63.5], end: [92.5, 94.25], dir: 31, endDir: 10, len: 60.1, num: [38.5, 71.5], part: 1 },
  ],
  parts: [
    { element: "𠂇", position: "kamae" },
    { element: "又", position: "kamaec", radical: "general" },
  ],
};

export default data;
