/*
 * KanjiVG stroke data for 古 (U+53E4) — release 20260714, source file kanji/053e4.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "古",
  code: "053e4",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M11.25,43.25c2.75,0.62,5.54,0.83,9.53,0.5c23.85-2,49.47-4.12,67.35-4.75c4.02-0.14,6.87,0,9.12,0.5", type: "㇐", start: [11.25, 43.25], end: [97.25, 39.5], dir: -2, endDir: 13, len: 86.3, num: [3.75, 40.63], part: 0 },
    { n: 2, d: "M52.41,12.5c1.42,1.42,2.13,3.25,2.13,5.06c0,17.05-0.14,39.31-0.14,48.94", type: "㇑a", start: [52.41, 12.5], end: [54.4, 66.5], dir: 88, endDir: 90, len: 54.6, num: [47.25, 7.63], part: 0 },
    { n: 3, d: "M31,67.77c1.12,1.12,2,2.73,2.24,4.48c0.61,4.43,1.87,12.12,3.22,20.93c0.2,1.31,0.39,2.59,0.57,3.83", type: "㇑", start: [31, 67.77], end: [37.03, 97.01], dir: 78, endDir: 82, len: 30.1, num: [23.25, 75.13], part: 1 },
    { n: 4, d: "M33.77,69.3c11.97-1.17,36.4-3.39,42.99-3.81c3.74-0.24,5.11,1.39,4.26,4.71c-1.18,4.63-3.81,13.6-5.23,20.06", type: "㇕b", start: [33.77, 69.3], end: [75.79, 90.26], dir: 27, endDir: 102, len: 71.9, num: [36.75, 64.63], part: 1 },
    { n: 5, d: "M37.88,94.42c7.81-0.36,23.99-1.88,35.14-2.65c1.87-0.13,3.61-0.24,5.18-0.32", type: "㇐b", start: [37.88, 94.42], end: [78.2, 91.45], dir: -4, endDir: -3, len: 40.4, num: [42.75, 90.13], part: 1 },
  ],
  parts: [
    { element: "十", position: "top", radical: "nelson" },
    { element: "口", position: "bottom", radical: "tradit" },
  ],
};

export default data;
