/*
 * KanjiVG stroke data for 口 (U+53E3) — release 20260714, source file kanji/053e3.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "口",
  code: "053e3",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M22.25,33.25c1.25,1.25,2,2.88,2.26,4.43c1.16,7.03,3.15,23.61,4.68,37.85C29.46,78.09,29.73,80.6,30,83", type: "㇑", start: [22.25, 33.25], end: [30, 83], dir: 81, endDir: 84, len: 50.7, num: [15.5, 40.5] },
    { n: 2, d: "M25.29,35.67c17.46-2.17,41.59-5.04,55.49-5.93c3.94-0.25,6.33,2.72,5.72,5.14c-2.25,8.87-6.62,26.5-9,38.87", type: "㇕b", start: [25.29, 35.67], end: [77.5, 73.75], dir: 36, endDir: 101, len: 104.6, num: [28.5, 30.5] },
    { n: 3, d: "M30.25,77.75c10.5-0.5,30.53-2.3,44.99-3.04c2.05-0.11,3.99-0.18,5.76-0.21", type: "㇐b", start: [30.25, 77.75], end: [81, 74.5], dir: -4, endDir: -1, len: 50.9, num: [34.5, 72.5] },
  ],
  parts: [

  ],
};

export default data;
