/*
 * KanjiVG stroke data for 右 (U+53F3) — release 20260714, source file kanji/053f3.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "右",
  code: "053f3",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M53.5,21.5c0.62,1.12,0.69,2.23,0.25,4C49.62,42,39.5,61,25.25,74.25", type: "㇒", start: [53.5, 21.5], end: [25.25, 74.25], dir: 118, endDir: 137, len: 61.3, num: [47, 20], part: 0 },
    { n: 2, d: "M13,42.15c1.9,0.56,5.9,0.52,7.79,0.34c23.41-2.24,49.76-5.74,67.67-6.3c3.24-0.1,6.45,0.31,9.17,0.81", type: "㇐", start: [13, 42.15], end: [97.63, 37], dir: -3, endDir: 10, len: 85, num: [8.25, 40], part: 0 },
    { n: 3, d: "M41.75,66.5c0.75,0.75,1.35,1.93,1.54,2.95c0.94,5,2.38,16.66,3.07,22.76c0.24,2.15,0.39,2.8,0.39,3.54", type: "㇑", start: [41.75, 66.5], end: [46.75, 95.75], dir: 80, endDir: 90, len: 29.9, num: [37.25, 78.63], part: 1 },
    { n: 4, d: "M43.25,68c5.25-0.5,29.75-3.25,37-3.75c1.75-0.12,3.24,1.52,3,2.75c-1,5.12-3.38,18-4.5,23.25", type: "㇕b", start: [43.25, 68], end: [78.75, 90.25], dir: 32, endDir: 102, len: 65.5, num: [45.75, 64.5], part: 1 },
    { n: 5, d: "M47,93.25c5.79-0.2,19.51-1.58,28.25-2.23c2.21-0.17,4.18-0.27,5.75-0.27", type: "㇐b", start: [47, 93.25], end: [81, 90.75], dir: -4, endDir: 0, len: 34.1, num: [51.75, 89.43], part: 1 },
  ],
  parts: [
    { element: "丆" },
    { element: "口", radical: "general" },
  ],
};

export default data;
