/*
 * KanjiVG stroke data for 名 (U+540D) — release 20260714, source file kanji/0540d.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "名",
  code: "0540d",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M54.2,12.64c0.3,1.61-0.07,2.99-0.69,4.24c-3.49,7.13-13.28,19.29-25.96,27.54", type: "㇒", start: [54.2, 12.64], end: [27.55, 44.42], dir: 130, endDir: 147, len: 42.6, num: [46.5, 12.5], part: 0 },
    { n: 2, d: "M53.25,24.16c0.88,0.47,1.95,0.5,3.28,0.37c4.37-0.43,11.99-2.47,17.81-4.1c4.18-1.17,5.46,1.02,4.41,3.51C72.25,39.38,43.88,69.62,16,77.5", type: "㇇", start: [53.25, 24.16], end: [16, 77.5], dir: 125, endDir: 164, len: 113.8, num: [60.5, 20.5], part: 0 },
    { n: 3, d: "M43.62,40.88c3.62,2,8,6,9.68,9.58", type: "㇔", start: [43.62, 40.88], end: [53.3, 50.46], dir: 45, endDir: 65, len: 13.8, num: [38.5, 48.5], part: 0 },
    { n: 4, d: "M42,67.81c0.91,0.91,1.62,2.19,1.83,3.33c0.5,2.82,2.15,14.38,3.05,20.86c0.3,2.12,0.52,3.7,0.59,4.25", type: "㇑", start: [42, 67.81], end: [47.47, 96.25], dir: 79, endDir: 83, len: 29.2, num: [37.5, 77.5], part: 1 },
    { n: 5, d: "M44.53,69.52c10.82-1.38,32.39-4.4,38.01-4.53c2.76-0.06,4.08,1.63,3.25,4.64c-1.13,4.06-3.52,14.04-4.64,20.36", type: "㇕b", start: [44.53, 69.52], end: [81.15, 89.99], dir: 29, endDir: 100, len: 66.1, num: [54.5, 64.5], part: 1 },
    { n: 6, d: "M47.99,93.99c7.26-0.61,19.65-1.61,29.54-2.37c2.19-0.17,4.24-0.28,6.04-0.31", type: "㇐b", start: [47.99, 93.99], end: [83.57, 91.31], dir: -4, endDir: -1, len: 35.7, num: [50.5, 90.5], part: 1 },
  ],
  parts: [
    { element: "夕", position: "top", radical: "nelson" },
    { element: "口", position: "bottom", radical: "tradit" },
  ],
};

export default data;
