/*
 * KanjiVG stroke data for 同 (U+540C) — release 20260714, source file kanji/0540c.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "同",
  code: "0540c",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M21.67,16.73c1.08,1.27,1.69,3.02,1.69,5.32c0,4.15-0.19,49.87-0.25,67.2c-0.01,3.37-0.02,5.63-0.02,6.25", type: "㇑", start: [21.67, 16.73], end: [23.09, 95.5], dir: 89, endDir: 90, len: 79.2, num: [15.5, 26.5], part: 0 },
    { n: 2, d: "M24.04,19.17c15.63-1.45,57.69-4.83,59.24-5c3.88-0.42,5.19,1.58,5.19,4.37c0,2.54-0.26,65.26-0.26,71.1c0,12.6-5.08,4.85-7.96,2.05", type: "㇆a", start: [24.04, 19.17], end: [80.25, 91.69], dir: 52, endDir: -136, len: 154.1, num: [27.5, 15.5], part: 0 },
    { n: 3, d: "M37.38,33.92c1.35,0.38,3.82,0.54,5.16,0.38c6.96-0.8,18.96-2.05,25.62-2.63c2.23-0.2,3.59,0.18,4.71,0.37", type: "㇐", start: [37.38, 33.92], end: [72.87, 32.04], dir: -3, endDir: 10, len: 35.7, num: [29.5, 35.5], part: 1 },
    { n: 4, d: "M38.83,48.39c0.82,0.55,1.53,1.56,1.76,2.49c1.15,4.62,2.13,10.46,3.01,16.32c0.27,1.8,0.52,2.78,0.76,4.3", type: "㇑", start: [38.83, 48.39], end: [44.36, 71.5], dir: 77, endDir: 81, len: 24.1, num: [32.5, 55.63], part: 2 },
    { n: 5, d: "M41.44,49.72c9.31-1.22,20.85-2.46,26.25-3.06c2.2-0.24,3.53,1.44,3.21,2.87c-1.09,4.92-2.33,9.95-3.83,16.33", type: "㇕b", start: [41.44, 49.72], end: [67.07, 65.86], dir: 32, endDir: 103, len: 48.2, num: [42.5, 46.5], part: 2 },
    { n: 6, d: "M45.09,69.33c5.52-0.48,12.6-1.51,20.15-2.26c1.19-0.12,2.51-0.07,3.84-0.1", type: "㇐b", start: [45.09, 69.33], end: [69.08, 66.97], dir: -6, endDir: -1, len: 24.1, num: [48.75, 66.13], part: 2 },
  ],
  parts: [
    { element: "冂", position: "kamae", radical: "nelson" },
    { element: "一" },
    { element: "口", radical: "tradit" },
  ],
};

export default data;
