/*
 * KanjiVG stroke data for 四 (U+56DB) — release 20260714, source file kanji/056db.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "四",
  code: "056db",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M14.5,31.48c1.51,1.51,2.25,3.27,2.53,5.2c1.14,7.9,2.61,25.18,4.39,40.83c0.29,2.55,0.34,3.81,0.64,6.24", type: "㇑", start: [14.5, 31.48], end: [22.06, 83.75], dir: 82, endDir: 83, len: 53.2, num: [8.75, 40.63], part: 0 },
    { n: 2, d: "M17.85,34.04c21.65-1.92,51.52-3.92,67.82-4.3c4.85-0.11,6.31,2.62,6.04,5.38c-0.9,9.02-4.17,28.29-6.41,39.62c-0.49,2.49-0.94,4.6-1.3,6.13", type: "㇕a", start: [17.85, 34.04], end: [84, 80.87], dir: 35, endDir: 103, len: 123.8, num: [20.75, 29.13], part: 0 },
    { n: 3, d: "M40.5,36c0.08,0.64,0.12,1.65-0.16,2.57c-2.22,7.3-5.1,14.55-13.35,22.68", type: "㇒", start: [40.5, 36], end: [26.99, 61.25], dir: 118, endDir: 135, len: 29.2, num: [31.25, 41.63], part: 2 },
    { n: 4, d: "M59.75,34.25c0.8,1.05,1.44,2.29,1.49,3.92c0.11,3.62,0.05,7.05,0.05,9.89c0,6.94,0.71,7.54,9.47,7.54c4.99,0,8.86-0.72,10.25-1.72", type: "㇟a", start: [59.75, 34.25], end: [81.01, 53.88], dir: 43, endDir: -36, len: 39.6, num: [52.25, 40.13], part: 1 },
    { n: 5, d: "M22.73,79.32c13.77-0.57,43.64-1.8,61.18-2.08", type: "㇐a", start: [22.73, 79.32], end: [83.91, 77.24], dir: -2, endDir: -1, len: 61.2, num: [27.25, 75.63], part: 3 },
  ],
  parts: [
    { element: "囗", position: "kamae", radical: "general", part: "1" },
    { element: "儿" },
    { element: "丿", parent: 1 },
    { element: "囗", position: "kamae", radical: "general", part: "2" },
  ],
};

export default data;
