/*
 * KanjiVG stroke data for 国 (U+56FD) — release 20260714, source file kanji/056fd.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "国",
  code: "056fd",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M19,16.82c1.09,1.09,1.61,2.51,1.61,4.41c0,14.65-0.22,44.9-0.22,71.53c0,1.95-0.06,3.86-0.09,5.75", type: "㇑", start: [19, 16.82], end: [20.3, 98.51], dir: 89, endDir: 91, len: 82.1, num: [12.5, 25.63], part: 0 },
    { n: 2, d: "M21.52,18.67C41.38,16.75,74.03,13.5,85,13.5c3.38,0,5,1.85,5,5.25c0,15.36-0.04,47.89-0.08,70.62c0,1.68,0,3.31,0,4.88", type: "㇕a", start: [21.52, 18.67], end: [89.92, 94.25], dir: 48, endDir: 90, len: 147.5, num: [22.5, 14.5], part: 0 },
    { n: 3, d: "M35.12,33.88c1.32,0.28,4.2,0.44,5.51,0.28c10.47-1.29,20.62-2.54,28.62-3.13c2.02-0.15,3.88-0.19,5.56,0.04", type: "㇐", start: [35.12, 33.88], end: [74.81, 31.07], dir: -4, endDir: 8, len: 39.9, num: [27.75, 35.5], part: 2 },
    { n: 4, d: "M52.8,34.89c0.96,0.97,1.47,2.48,1.47,3.81c0,3.99-0.13,24.74-0.09,33.55", type: "㇑a", start: [52.8, 34.89], end: [54.18, 72.25], dir: 88, endDir: 90, len: 37.7, num: [45.75, 43.5], part: 2 },
    { n: 5, d: "M37.58,52.16c1.79,0.22,3.41,0.14,5.36-0.08c7.56-0.83,17.56-1.99,25.38-2.8c1.25-0.13,4.02-0.15,5.89,0.17", type: "㇐", start: [37.58, 52.16], end: [74.21, 49.45], dir: -4, endDir: 10, len: 36.8, num: [30.5, 54.13], part: 2 },
    { n: 6, d: "M31.08,75.14c1.54,0.36,3.85,0.28,5.19,0.16c9.98-0.92,25.85-2.67,37.03-3.54c2.15-0.17,5.04-0.18,6.12,0.13", type: "㇐", start: [31.08, 75.14], end: [79.42, 71.89], dir: -4, endDir: 16, len: 48.6, num: [29.25, 70.63], part: 2 },
    { n: 7, d: "M67.75,56.62c3,1.75,6.12,5.12,8,8.38", type: "㇔", start: [67.75, 56.62], end: [75.75, 65], dir: 46, endDir: 60, len: 11.7, num: [77.25, 60.13], part: 3 },
    { n: 8, d: "M21.5,93.01c14.25-0.51,48.38-1.89,67-2.51", type: "㇐a", start: [21.5, 93.01], end: [88.5, 90.5], dir: -2, endDir: -2, len: 67, num: [25.5, 88.63], part: 4 },
  ],
  parts: [
    { element: "囗", position: "kamae", radical: "general", part: "1" },
    { element: "玉" },
    { element: "王", parent: 1 },
    { element: "丶", parent: 1 },
    { element: "囗", position: "kamae", radical: "general", part: "2" },
  ],
};

export default data;
