/*
 * KanjiVG stroke data for 土 (U+571F) — release 20260714, source file kanji/0571f.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "土",
  code: "0571f",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M26.63,50.89c1.63,0.4,4.64,0.6,6.26,0.4C43.5,50,62.12,48,75.66,46.92c2.71-0.22,4.36,0.19,5.72,0.39", type: "㇐", start: [26.63, 50.89], end: [81.38, 47.31], dir: -4, endDir: 8, len: 55, num: [19.5, 51.13] },
    { n: 2, d: "M52.17,17.37c1.17,1.17,2.02,3.13,2.02,4.64c0,10.25,0.14,61.06,0.14,63.36", type: "㇑a", start: [52.17, 17.37], end: [54.33, 85.37], dir: 88, endDir: 90, len: 68.5, num: [41.5, 17.5] },
    { n: 3, d: "M15.38,87.73c2.12,0.54,6.01,0.73,8.12,0.54C46,86.25,69,84.62,90.34,83.79c3.53-0.14,5.65,0.26,7.41,0.53", type: "㇐", start: [15.38, 87.73], end: [97.75, 84.32], dir: -2, endDir: 9, len: 82.6, num: [6.5, 86.5] },
  ],
  parts: [

  ],
};

export default data;
