/*
 * KanjiVG stroke data for 売 (U+58F2) — release 20260714, source file kanji/058f2.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "売",
  code: "058f2",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M28.63,24.35c1.4,0.29,2.87,0.9,5.36,0.79C44.78,24.68,60,22.5,72.74,21.61c2.32-0.16,3.97-0.11,5.14,0.04", type: "㇐", start: [28.63, 24.35], end: [77.88, 21.65], dir: -3, endDir: 7, len: 49.5, num: [21.5, 25.5], part: 0 },
    { n: 2, d: "M52.42,9.25c1.1,1.1,1.93,2.75,1.93,4.52c0,6.51-0.05,16.19-0.05,23.58", type: "㇑a", start: [52.42, 9.25], end: [54.3, 37.35], dir: 86, endDir: 90, len: 28.6, num: [44.5, 10.5], part: 0 },
    { n: 3, d: "M31.98,38.99c2.15,0.51,4.46,0.83,6.03,0.68c8.25-0.77,20.27-2.27,31.74-3.54c2.41-0.26,4.62-0.4,7.01-0.23", type: "㇐", start: [31.98, 38.99], end: [76.76, 35.9], dir: -4, endDir: 4, len: 45.1, num: [25.5, 40.5], part: 0 },
    { n: 4, d: "M18.62,52.5c-0.15,3.86-3.63,14.45-4.88,16.75", type: "㇔", start: [18.62, 52.5], end: [13.74, 69.25], dir: 106, endDir: 119, len: 17.5, num: [11.5, 55.5], part: 2 },
    { n: 5, d: "M19.75,54.73C40.38,52,69,49,86.69,48.5C99.5,48.14,88.5,57.88,85.5,60", type: "㇖b", start: [19.75, 54.73], end: [85.5, 60], dir: 5, endDir: 145, len: 86.3, num: [20.5, 51.13], part: 2 },
    { n: 6, d: "M41.25,62.5c0.37,1.12,0.29,2.43,0.16,3.65C40.25,77,35,90.25,25.64,97.65", type: "㇒", start: [41.25, 62.5], end: [25.64, 97.65], dir: 114, endDir: 142, len: 39.8, num: [32.5, 64.63], part: 4 },
    { n: 7, d: "M59.49,58.87c1.07,1.07,1.38,2.59,1.38,4.43c0,6.08-0.2,12.57-0.2,19.45c0,14,2.09,14.77,13.59,14.77c13,0,13.63-1.39,13.63-9.62", type: "㇟", start: [59.49, 58.87], end: [87.89, 87.9], dir: 46, endDir: -90, len: 69.3, num: [51.5, 61.5], part: 3 },
  ],
  parts: [
    { element: "士", position: "top", radical: "general" },
    { position: "bottom" },
    { element: "冖", parent: 1 },
    { element: "儿", parent: 1 },
    { element: "丿", parent: 3 },
  ],
};

export default data;
