/*
 * KanjiVG stroke data for 外 (U+5916) — release 20260714, source file kanji/05916.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "外",
  code: "05916",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M35.44,15.75c0.53,1.77,0.62,3.56,0.13,5.33C33.25,29.5,26.75,44.75,16.5,55", type: "㇒", start: [35.44, 15.75], end: [16.5, 55], dir: 116, endDir: 135, len: 44.7, num: [27.75, 13.63], part: 0 },
    { n: 2, d: "M36.72,28.81c1.47,0.25,3.12,0.16,4.56-0.14c3.52-0.72,5.83-1.04,9.45-2.2c3.61-1.17,4.39,1.7,3.77,3.54c-5.46,16.06-22.18,50.32-39.75,58.5", type: "㇇", start: [36.72, 28.81], end: [14.75, 88.51], dir: 110, endDir: 155, len: 93.2, num: [42.75, 24.13], part: 0 },
    { n: 3, d: "M27.5,47c3.71,1.68,9.57,6.89,10.5,9.5", type: "㇔", start: [27.5, 47], end: [38, 56.5], dir: 42, endDir: 70, len: 14.4, num: [33.75, 46.63], part: 0 },
    { n: 4, d: "M65.56,12.13c1.09,1.09,1.76,2.87,1.76,5.25c0,0.78-0.07,54.62-0.19,73.62c-0.02,3.16-0.04,5.33-0.06,6.13", type: "㇑", start: [65.56, 12.13], end: [67.07, 97.13], dir: 89, endDir: 91, len: 85.4, num: [57.5, 11.5], part: 1 },
    { n: 5, d: "M71.5,42.5c7.85,3.75,20.29,15.42,22.25,21.25", type: "㇔", start: [71.5, 42.5], end: [93.75, 63.75], dir: 44, endDir: 71, len: 31.2, num: [74.25, 40.63], part: 1 },
  ],
  parts: [
    { element: "夕", position: "left", radical: "general" },
    { element: "卜", position: "right" },
  ],
};

export default data;
