/*
 * KanjiVG stroke data for 多 (U+591A) — release 20260714, source file kanji/0591a.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "多",
  code: "0591a",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M45.82,11.92c0.18,1.08-0.22,2.3-0.66,3.01C42.5,19.25,37,26.33,28.5,31.25", type: "㇒", start: [45.82, 11.92], end: [28.5, 31.25], dir: 132, endDir: 150, len: 26.7, num: [38.5, 12.5], part: 0 },
    { n: 2, d: "M48.24,16.65c1.38,0.22,3.15,0.08,4.79-0.12c5.59-0.66,9.72-1.28,14.9-2.3c3.15-0.62,4.07,1.15,3.01,3.46c-4.46,9.74-24.82,31.44-44.28,37.66", type: "㇇", start: [48.24, 16.65], end: [26.66, 55.35], dir: 119, endDir: 162, len: 85.4, num: [51.75, 13.63], part: 0 },
    { n: 3, d: "M40,28.25c2.67,1.56,7,6.5,7.75,9", type: "㇔", start: [40, 28.25], end: [47.75, 37.25], dir: 49, endDir: 73, len: 12, num: [44.5, 28.5], part: 0 },
    { n: 4, d: "M58.5,42.25c0.25,1.5-0.11,2.78-0.48,3.6C55.25,52,48.75,59.5,33.75,68.5", type: "㇒", start: [58.5, 42.25], end: [33.75, 68.5], dir: 133, endDir: 149, len: 37.4, num: [49.5, 49.5], part: 1 },
    { n: 5, d: "M60.42,48.62c1.58,0.13,3.01,0.09,4.6-0.09c5.86-0.66,9.23-1.16,13.48-2.03c3.13-0.64,4.62,1.62,3.48,4.09c-5,10.79-23.61,34.91-54.73,48.16", type: "㇇", start: [60.42, 48.62], end: [27.25, 98.75], dir: 123, endDir: 157, len: 99.5, num: [64.5, 45.5], part: 1 },
    { n: 6, d: "M48.25,63c2.93,1.73,7.67,7.22,8.5,10", type: "㇔", start: [48.25, 63], end: [56.75, 73], dir: 50, endDir: 73, len: 13.3, num: [53.5, 63.13], part: 1 },
  ],
  parts: [
    { element: "夕", position: "top", radical: "general" },
    { element: "夕", position: "bottom" },
  ],
};

export default data;
