/*
 * KanjiVG stroke data for 夜 (U+591C) — release 20260714, source file kanji/0591c.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "夜",
  code: "0591c",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M52.27,10.5c1.24,1.24,1.92,2.75,1.92,4.26c0,4.29-0.12,5.13-0.12,8.81", type: "㇑a", start: [52.27, 10.5], end: [54.07, 23.57], dir: 82, endDir: 90, len: 13.6, num: [44.5, 11.5], part: 0 },
    { n: 2, d: "M20,27.47c2.58,0.33,5.52,0.3,9.16-0.04c17.5-1.67,34.28-3.92,51.31-4.98c3.54-0.22,5.63-0.21,8.28,0.33", type: "㇐", start: [20, 27.47], end: [88.75, 22.78], dir: -4, endDir: 12, len: 69, num: [12.5, 28.5], part: 0 },
    { n: 3, d: "M34.26,36c0.31,2-0.06,3.89-0.76,5.34c-4.44,9.2-10.07,17.85-20.25,29.05", type: "㇒", start: [34.26, 36], end: [13.25, 70.39], dir: 121, endDir: 132, len: 41, num: [25.5, 40.63], part: 2 },
    { n: 4, d: "M27.73,55.9c0.77,1.1,1.26,2.51,1.26,3.84c0,8.77,0.17,23.89,0.04,32.77C29,94.78,28.97,96.68,28.97,98", type: "㇑", start: [27.73, 55.9], end: [28.97, 98], dir: 88, endDir: 90, len: 42.4, num: [21.5, 71.5], part: 2 },
    { n: 5, d: "M60.5,32c0.13,1.12,0.18,2.04-0.15,2.89C57.86,41.41,52.87,50.32,45,57", type: "㇒", start: [60.5, 32], end: [45, 57], dir: 122, endDir: 140, len: 30.1, num: [51.5, 35.5], part: 3 },
    { n: 6, d: "M62.21,39.36c1.04,0.14,2.54,0.26,3.52,0.12c4.52-0.61,8.27-1.61,11.9-3.12c3-1.25,4.38,0.75,3.47,3.02C74.75,55.25,61,78.88,38.25,90", type: "㇇", start: [62.21, 39.36], end: [38.25, 90], dir: 115, endDir: 154, len: 90, num: [65.5, 35.5], part: 3 },
    { n: 7, d: "M56.75,49.12c2.73,1.25,7.04,5.14,7.73,7.08", type: "㇔", start: [56.75, 49.12], end: [64.48, 56.2], dir: 42, endDir: 70, len: 10.6, num: [60.5, 49.5], part: 3 },
    { n: 8, d: "M45,62.75c7.38,0.75,28.23,18.89,38.64,25.59c3.13,2.01,6.66,4,10.36,4.66", type: "㇏", start: [45, 62.75], end: [94, 93], dir: 32, endDir: 10, len: 58, num: [49.5, 62.5], part: 4 },
  ],
  parts: [
    { element: "亠", position: "top", radical: "nelson" },
    { position: "bottom" },
    { element: "亻", parent: 1 },
    { element: "夕", radical: "tradit", parent: 1 },
    { parent: 1 },
  ],
};

export default data;
