/*
 * KanjiVG stroke data for 天 (U+5929) — release 20260714, source file kanji/05929.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "天",
  code: "05929",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M21.63,24.83c1.81,0.46,5.14,0.4,6.94,0.21c14.55-1.53,35.18-4.16,50.1-5.25c3.01-0.22,4.83,0.22,6.34,0.45", type: "㇐", start: [21.63, 24.83], end: [85.01, 20.24], dir: -4, endDir: 9, len: 63.7, num: [12.75, 22.63], part: 0 },
    { n: 2, d: "M25.31,51.64c2.09,0.31,3.47,0.4,5.94,0.11c10.62-1.25,35.88-4.38,45.96-4.93c1.74-0.1,3.62,0.03,5.99,0.45", type: "㇐", start: [25.31, 51.64], end: [83.2, 47.27], dir: -4, endDir: 10, len: 58.2, num: [17.25, 51.13], part: 1 },
    { n: 3, d: "M50.32,26c0.68,1,1.3,3.43,1.29,5.37c-0.24,30.51-14.86,50.88-33.86,60.25", type: "㇒", start: [50.32, 26], end: [17.75, 91.62], dir: 116, endDir: 154, len: 78.5, num: [42.75, 36.13], part: 1 },
    { n: 4, d: "M50.1,51.39C58.71,60,75.07,78.48,86.59,87.05c2.33,1.73,4.41,3.08,7.91,4.2", type: "㇏", start: [50.1, 51.39], end: [94.5, 91.25], dir: 42, endDir: 18, len: 60.1, num: [65.25, 61.63], part: 1 },
  ],
  parts: [
    { element: "一", position: "top", radical: "nelson" },
    { element: "大", position: "bottom", radical: "tradit" },
  ],
};

export default data;
