/*
 * KanjiVG stroke data for 大 (U+5927) — release 20260714, source file kanji/05927.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "大",
  code: "05927",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M19.38,48.25c1.49,0.51,5.03,0.89,7.6,0.49C41.12,46.5,63,43,77.19,42.44c2.7-0.11,4.87-0.06,7.31,0.33", type: "㇐", start: [19.38, 48.25], end: [84.5, 42.77], dir: -5, endDir: 9, len: 65.6, num: [12.75, 49.63] },
    { n: 2, d: "M49.5,18c0.88,2.12,1.03,4.16,0.99,6.32C50,57,37.75,81.12,18,91.75", type: "㇒", start: [49.5, 18], end: [18, 91.75], dir: 113, endDir: 152, len: 84.9, num: [40.5, 18.5] },
    { n: 3, d: "M49.5,46c9,10.5,28.5,36.25,37.49,43.28c3.06,2.39,5.62,3.75,7.01,3.97", type: "㇏", start: [49.5, 46], end: [94, 93.25], dir: 47, endDir: 9, len: 65.4, num: [61.5, 55.63] },
  ],
  parts: [

  ],
};

export default data;
