/*
 * KanjiVG stroke data for 好 (U+597D) — release 20260714, source file kanji/0597d.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "好",
  code: "0597d",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M29.33,14.12c0.79,1.38,1.04,3.35,0.85,5.06c-0.94,8.36-4.83,32.78-8.96,42.56c-0.85,2.01,0.39,2.79,0.85,2.97c5.7,2.28,11.04,5.41,15.17,9.43c2.52,2.46,4.59,5.26,6.02,8.4", type: "㇛", start: [29.33, 14.12], end: [43.26, 82.54], dir: 78, endDir: 66, len: 80.6, num: [22.5, 14.5], part: 0 },
    { n: 2, d: "M41.12,35.88c0.5,1.4,0.71,2.83,0.35,4.75c-3.22,17.12-10.1,38.5-24.72,50.12", type: "㇒", start: [41.12, 35.88], end: [16.75, 90.75], dir: 114, endDir: 142, len: 61.8, num: [39.5, 32.5], part: 0 },
    { n: 3, d: "M9.75,47.46c0.75,0.99,1.88,1.17,3.01,0.99c2.15-0.34,22.82-5.19,33.86-7.59", type: "㇀/㇐", start: [9.75, 47.46], end: [46.62, 40.86], dir: -10, endDir: -12, len: 38, num: [1.99, 47.98], part: 0 },
    { n: 4, d: "M52.68,20.3c1.69,0.45,3.74,0.51,5.21,0.34c4.48-0.52,17.48-3.27,23.34-4.89c1.62-0.45,3.4,0.98,1.82,3.14C80.5,22.38,76.25,28.25,70,35", type: "㇖", start: [52.68, 20.3], end: [70, 35], dir: 40, endDir: 133, len: 54.9, num: [50.5, 17.5], part: 1 },
    { n: 5, d: "M67.57,36.74c9.05,8.89,10.3,31.39,6.43,49.14c-1.67,7.64-6.12,7.75-10.09,2.55", type: "㇁", start: [67.57, 36.74], end: [63.91, 88.43], dir: 94, endDir: -127, len: 66.2, num: [60.5, 41.5], part: 1 },
    { n: 6, d: "M46.03,52.68c1.46,0.61,5.04,0.84,7.65,0.42c12.32-1.98,26.07-4.36,37.44-4.33c2.64,0.01,4.97,0.2,6.73,0.81", type: "㇐", start: [46.03, 52.68], end: [97.85, 49.58], dir: -3, endDir: 19, len: 52.3, num: [47.5, 50.5], part: 1 },
  ],
  parts: [
    { element: "女", position: "left", radical: "general" },
    { element: "子", position: "right" },
  ],
};

export default data;
