/*
 * KanjiVG stroke data for 女 (U+5973) — release 20260714, source file kanji/05973.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "女",
  code: "05973",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M53.21,18.37c0.54,2.13,0.26,3.41-0.25,5.25C50.38,33,42.62,52.75,35.75,64c-1.39,2.27-1,3.5,1,3.5c11.63,0,28.46,7.48,38.83,16.41c2.56,2.21,4.68,4.51,6.17,6.84", type: "㇛", start: [53.21, 18.37], end: [81.75, 90.75], dir: 68, endDir: 57, len: 106.4, num: [45, 17.5] },
    { n: 2, d: "M69.62,42.18c0.5,1.7,0.63,3.57-0.01,5.93C65.93,61.8,54.61,81.6,27,91.75", type: "㇒", start: [69.62, 42.18], end: [27, 91.75], dir: 131, endDir: 160, len: 69.4, num: [68.5, 37.5] },
    { n: 3, d: "M13.88,50.43c3.48,1.39,7.26,0.85,10.88,0.53c19.52-1.7,42.04-4.08,60.61-4.63c3.66-0.11,7.21-0.1,10.62,1.42", type: "㇐", start: [13.88, 50.43], end: [95.99, 47.75], dir: -2, endDir: 24, len: 82.6, num: [5.5, 51.5] },
  ],
  parts: [

  ],
};

export default data;
