/*
 * KanjiVG stroke data for 妹 (U+59B9) — release 20260714, source file kanji/059b9.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "妹",
  code: "059b9",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M26.55,18.62c0.33,1.11,0.69,2.93,0.51,4.54c-1.3,11.72-3.8,28.84-6.37,38.68c-0.52,1.98,0.34,2.68,0.76,2.81c4.84,1.55,10.03,4.05,14,7.92c1.41,1.38,2.7,3.36,3.81,4.94", type: "㇛", start: [26.55, 18.62], end: [39.26, 77.51], dir: 78, endDir: 55, len: 69.5, num: [18.5, 19.5], part: 0 },
    { n: 2, d: "M39.73,34.75c0.77,1.78,0.65,3.07,0.36,5.01C37.71,55.44,30.1,78.2,13.12,89.88", type: "㇒", start: [39.73, 34.75], end: [13.12, 89.88], dir: 116, endDir: 145, len: 63.5, num: [37.5, 31.5], part: 0 },
    { n: 3, d: "M10,47.71c0.88,1.29,2.27,1.68,4.25,1.29c9-1.75,22.33-4.73,33.25-7.03", type: "㇀/㇐", start: [10, 47.71], end: [47.5, 41.97], dir: -9, endDir: -12, len: 38.7, num: [2.5, 49.63], part: 0 },
    { n: 4, d: "M51.84,34.46c1.19,0.2,3.14,0.08,4.33-0.05c6.08-0.66,16.08-2.15,22.4-2.91c1.96-0.23,3.18,0.1,4.18,0.19", type: "㇐", start: [51.84, 34.46], end: [82.75, 31.69], dir: -5, endDir: 5, len: 31.1, num: [50.5, 32.5], part: 1 },
    { n: 5, d: "M44.25,51.25c2.26,0.5,3.88,0.61,6.8,0.25c8.2-1,24.32-3.25,34.64-3.89c2.7-0.17,4.56,0.14,6.33,0.75", type: "㇐", start: [44.25, 51.25], end: [92.02, 48.36], dir: -3, endDir: 19, len: 48.1, num: [48.5, 48.5], part: 2 },
    { n: 6, d: "M65.14,13.25C66.38,14.49,67,16,67,17.72c0,4.53,0.07,51.14-0.14,71.53c-0.04,4.02-0.08,6.81-0.13,7.75", type: "㇑", start: [65.14, 13.25], end: [66.73, 97], dir: 89, endDir: 93, len: 84.3, num: [56.5, 14.5], part: 2 },
    { n: 7, d: "M64.75,51c0,1.5-0.42,2.54-0.8,3.33C57.88,66.75,48.5,80,36.25,87.5", type: "㇒", start: [64.75, 51], end: [36.25, 87.5], dir: 128, endDir: 149, len: 47.2, num: [54.5, 61.5], part: 2 },
    { n: 8, d: "M68,51c4.56,8.8,13.2,20.09,20.34,27.47c2.02,2.09,4.91,4.41,7.54,6.03", type: "㇏", start: [68, 51], end: [95.88, 84.5], dir: 50, endDir: 32, len: 44, num: [76.5, 60.13], part: 2 },
  ],
  parts: [
    { element: "女", position: "left", radical: "general" },
    { element: "未", position: "right" },
    { element: "木", parent: 1 },
  ],
};

export default data;
