/*
 * KanjiVG stroke data for 姉 (U+59C9) — release 20260714, source file kanji/059c9.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "姉",
  code: "059c9",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M28.12,20.37c0.38,1.13,0.57,2.99,0.38,4.63c-0.97,8.06-4.99,28-9.27,37.43c-0.88,1.94,0.37,2.8,0.88,2.87c6.05,0.78,13.68,5.27,19.13,12.22c1.21,1.54,2.32,3.21,3.27,4.98", type: "㇛", start: [28.12, 20.37], end: [42.51, 82.5], dir: 77, endDir: 62, len: 76, num: [19.5, 20.5], part: 0 },
    { n: 2, d: "M40.5,38.75c0.38,1.75,0.36,2.98,0.08,4.67C38.12,58.25,30,78.88,12.75,87.75", type: "㇒", start: [40.5, 38.75], end: [12.75, 87.75], dir: 120, endDir: 153, len: 58.9, num: [33.75, 35.5], part: 0 },
    { n: 3, d: "M10.25,48.71c1,0.92,2.53,1.24,4.5,0.79c7.12-1.62,19.5-5.25,30-7.78", type: "㇀/㇐", start: [10.25, 48.71], end: [44.75, 41.72], dir: -11, endDir: -14, len: 35.7, num: [2.25, 51.13], part: 0 },
    { n: 4, d: "M69.23,13c1.32,1.32,1.65,2.75,1.65,4.77c0,4.3-0.11,4.98-0.11,8.58", type: "㇑a", start: [69.23, 13], end: [70.77, 26.35], dir: 83, endDir: 90, len: 13.8, num: [60.5, 12.5], part: 2 },
    { n: 5, d: "M44.5,29.22c3.09,0.48,5.97,0.51,7.72,0.33c11.4-1.18,30.28-3.43,40.66-4.05c2.98-0.18,4.52,0.03,6.75,0.42", type: "㇐", start: [44.5, 29.22], end: [99.63, 25.92], dir: -3, endDir: 10, len: 55.4, num: [44.25, 26.5], part: 2 },
    { n: 6, d: "M53.38,46.06c0.78,0.78,1.16,2.19,1.16,3.98c0,4.71,0,13.1-0.09,20.96c-0.03,2.29-0.05,3.66-0.07,4.69", type: "㇑", start: [53.38, 46.06], end: [54.38, 75.69], dir: 88, endDir: 91, len: 29.9, num: [46.5, 53.5], part: 3 },
    { n: 7, d: "M55.52,47.9c8.95-1.14,30.63-4.27,32.52-4.4c3.59-0.25,4.49,0.75,4.49,4.91c0,8.97-0.3,15.52-0.81,23.17c-0.47,6.93-3.47,3.68-5.95-0.23", type: "㇆a", start: [55.52, 47.9], end: [85.77, 71.35], dir: 38, endDir: -122, len: 75, num: [55.5, 44.5], part: 3 },
    { n: 8, d: "M70.57,34.12c1.21,1.21,1.41,2.93,1.41,4.58c0,0.63-0.06,37.87-0.09,53.16c0,3.21-0.02,3.95-0.03,4.77", type: "㇑", start: [70.57, 34.12], end: [71.86, 96.63], dir: 89, endDir: 91, len: 62.9, num: [75.5, 37.63], part: 3 },
  ],
  parts: [
    { element: "女", position: "left", radical: "general" },
    { element: "市", position: "right" },
    { element: "亠", parent: 1 },
    { element: "巾", parent: 1 },
  ],
};

export default data;
