/*
 * KanjiVG stroke data for 子 (U+5B50) — release 20260714, source file kanji/05b50.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "子",
  code: "05b50",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M33.28,19.04c1.84,0.71,3.7,0.86,5.4,0.63c4.95-0.67,27.95-4.58,29.86-4.92c3.46-0.62,4.06,1.36,2.11,3.58c-1.95,2.22-11.41,13.17-16.35,17.19", type: "㇖", start: [33.28, 19.04], end: [54.3, 35.52], dir: 38, endDir: 141, len: 66.1, num: [25.5, 20.5] },
    { n: 2, d: "M52.48,37.74c6.42,2.97,11.75,30.73,5.24,52.57c-2.8,9.38-8.09,2.96-10.47,0.99", type: "㇁", start: [52.48, 37.74], end: [47.25, 91.3], dir: 96, endDir: -140, len: 69.3, num: [44.5, 42.5] },
    { n: 3, d: "M12.25,51.48c3.75,1.14,8.79,1.03,12.48,0.49c16.77-2.47,42.86-5.84,58.53-6.75c4.26-0.25,9.11-0.34,13.11,0.57", type: "㇐", start: [12.25, 51.48], end: [96.37, 45.79], dir: -4, endDir: 13, len: 84.7, num: [4.5, 53.5] },
  ],
  parts: [

  ],
};

export default data;
