/*
 * KanjiVG stroke data for 学 (U+5B66) — release 20260714, source file kanji/05b66.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "学",
  code: "05b66",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M29.5,17.25c3.5,3,6.5,7.25,7.75,9.75", type: "㇔", start: [29.5, 17.25], end: [37.25, 27], dir: 52, endDir: 63, len: 12.5, num: [20.25, 13.63], part: 1 },
    { n: 2, d: "M49,12c1.25,2,4.75,8.25,5.25,11.5", type: "㇔", start: [49, 12], end: [54.25, 23.5], dir: 65, endDir: 81, len: 12.7, num: [39.75, 8.5], part: 1 },
    { n: 3, d: "M75,11c0.25,1.75-0.12,2.75-0.75,4.25c-1.29,3.1-4.25,7.38-6.5,9.75", type: "㇒", start: [75, 11], end: [67.75, 25], dir: 117, endDir: 134, len: 16.2, num: [66.5, 8.5], part: 1 },
    { n: 4, d: "M21.25,33.75c-0.12,4.75-2,12.5-3.75,16.25", type: "㇔", start: [21.25, 33.75], end: [17.5, 50], dir: 103, endDir: 115, len: 16.8, num: [14.5, 34.63], part: 2 },
    { n: 5, d: "M23.5,36.5c17-1.62,42.38-5.5,60-5.75c9.5-0.13,4.12,5.12,0,9", type: "㇖b", start: [23.5, 36.5], end: [83.5, 39.75], dir: 3, endDir: 137, len: 75.4, num: [24.5, 32.5], part: 2 },
    { n: 6, d: "M37.25,46.5c1,0.25,3.75,0.25,5.5-0.25s18.25-4,20-4s2.75,0.75,1,2.25S54.5,53.5,53,54.75", type: "㇖", start: [37.25, 46.5], end: [53, 54.75], dir: 28, endDir: 140, len: 44.8, num: [29.25, 48.5], part: 3 },
    { n: 7, d: "M50.75,55.75c4,8.75,7.18,24.67,1.75,38c-2.75,6.75-7.75,1.25-9.75-2", type: "㇁", start: [50.75, 55.75], end: [42.75, 91.75], dir: 103, endDir: -122, len: 52.5, num: [44.5, 58.63], part: 3 },
    { n: 8, d: "M15.75,67.75c1.75,1,4.64,1.36,7.5,1c15.88-2,44.43-6.25,61.37-5.5c2.5,0.11,4.72,0.25,6.39,1", type: "㇐", start: [15.75, 67.75], end: [91.01, 64.25], dir: -3, endDir: 24, len: 75.9, num: [8.5, 72.5], part: 3 },
  ],
  parts: [
    { position: "top" },
    { element: "⺍", parent: 0 },
    { element: "冖", parent: 0 },
    { element: "子", position: "bottom", radical: "general" },
  ],
};

export default data;
