/*
 * KanjiVG stroke data for 安 (U+5B89) — release 20260714, source file kanji/05b89.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "安",
  code: "05b89",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M53.06,13.73c0.92,0.92,1.63,2.6,1.6,3.75c-0.09,3.62-0.09,7.03-0.09,10.33", type: "㇑a", start: [53.06, 13.73], end: [54.57, 27.81], dir: 84, endDir: 90, len: 14.5, num: [44.5, 14.5], part: 0 },
    { n: 2, d: "M26.67,28.85c0,3.6-3.32,13.5-4.83,15.9", type: "㇔", start: [26.67, 28.85], end: [21.84, 44.75], dir: 107, endDir: 122, len: 16.7, num: [18.75, 34.63], part: 1 },
    { n: 3, d: "M27.53,30.96c12.72-1.58,40.97-4.21,54.14-4.86c9.82-0.48,1.45,6.65-2.17,9.9", type: "㇖b", start: [27.53, 30.96], end: [79.5, 36], dir: 6, endDir: 138, len: 70.6, num: [30.5, 27.5], part: 1 },
    { n: 4, d: "M49.87,36.87c0.51,1.45,0.52,3.55,0,5.32c-2.74,9.22-7.03,20.09-13.85,30.42c-1.43,2.17-0.76,2.95,1.26,3.14c8.23,0.75,21.61,4.5,33.74,11.77c4.36,2.61,8.24,5.98,10.24,9.48", type: "㇛", start: [49.87, 36.87], end: [81.26, 97], dir: 62, endDir: 60, len: 93.7, num: [42.5, 39.13], part: 2 },
    { n: 5, d: "M70,50c0.38,1.48,0.22,3.46-0.26,5.13c-3.88,13.52-17.45,34.6-43.24,42.49", type: "㇒", start: [70, 50], end: [26.5, 97.62], dir: 132, endDir: 163, len: 68.2, num: [64.5, 45.5], part: 2 },
    { n: 6, d: "M15.13,60.22c2.85,0.74,6.22,0.42,9.12,0.2c11.33-0.85,40.73-4.55,64.72-4.64c2.27-0.01,6.19,0.33,8.03,0.96", type: "㇐", start: [15.13, 60.22], end: [97, 56.74], dir: -2, endDir: 19, len: 82.2, num: [7.5, 61.5], part: 2 },
  ],
  parts: [
    { element: "宀", position: "top", radical: "general" },
    { element: "冖", parent: 0 },
    { element: "女", position: "bottom" },
  ],
};

export default data;
