/*
 * KanjiVG stroke data for 家 (U+5BB6) — release 20260714, source file kanji/05bb6.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "家",
  code: "05bb6",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M52.44,11c0.97,0.97,1.69,2.25,1.69,3.68c0,3.42-0.08,4.99-0.08,8.1", type: "㇑a", start: [52.44, 11], end: [54.05, 22.78], dir: 82, endDir: 90, len: 12.3, num: [44.5, 12.5], part: 0 },
    { n: 2, d: "M27.09,23.28c0,3.73-2.77,13.98-4.03,16.47", type: "㇔", start: [27.09, 23.28], end: [23.06, 39.75], dir: 104, endDir: 117, len: 17, num: [20.25, 28.63], part: 1 },
    { n: 3, d: "M27.99,27.18C41.88,25,72.75,21.5,79.81,21.2c12.19-0.52,1.14,7.87-0.34,8.63", type: "㇖b", start: [27.99, 27.18], end: [79.47, 29.83], dir: 3, endDir: 153, len: 68, num: [31.5, 23.5], part: 1 },
    { n: 4, d: "M32.76,40.23c1.38,0.4,3.92,0.57,5.29,0.4c8.08-1,19.7-3.38,25.59-3.84c2.29-0.18,3.41-0.04,4.83-0.11", type: "㇐", start: [32.76, 40.23], end: [68.47, 36.68], dir: -6, endDir: -3, len: 36, num: [30.75, 36.13], part: 2 },
    { n: 5, d: "M51.26,41.5c0.18,1.1-0.06,2.08-0.72,2.94C47.84,48.63,38.92,55.58,26.5,60.5", type: "㇒", start: [51.26, 41.5], end: [26.5, 60.5], dir: 142, endDir: 158, len: 32.4, num: [36.75, 51.13], part: 2 },
    { n: 6, d: "M48.07,48.96c8.31,7.92,14.18,25.04,6.92,43.51c-2.42,6.16-8.12,0.9-9.3,0.05", type: "㇁", start: [48.07, 48.96], end: [45.69, 92.52], dir: 93, endDir: -144, len: 58.1, num: [55.5, 53.5], part: 2 },
    { n: 7, d: "M49,56c0.17,1.16-0.14,2.17-0.92,3.04c-2.78,3.84-10.78,9.86-22.33,14.21", type: "㇒", start: [49, 56], end: [25.75, 73.25], dir: 143, endDir: 159, len: 30, num: [36.75, 64.63], part: 2 },
    { n: 8, d: "M52.5,65.5c0.21,1.3-0.06,2.45-0.84,3.44c-3.27,5.04-13.97,13.61-29.91,19.56", type: "㇒", start: [52.5, 65.5], end: [21.75, 88.5], dir: 143, endDir: 160, len: 39.8, num: [33.75, 78.13], part: 2 },
    { n: 9, d: "M76.8,45.3c0.14,1.12-0.2,2.09-1.02,2.91c-2.55,3.35-9.29,8.72-18.05,12.19", type: "㇒", start: [76.8, 45.3], end: [57.73, 60.4], dir: 142, endDir: 158, len: 25.2, num: [68.5, 47.5], part: 2 },
    { n: 10, d: "M58.79,62.82c3.72,2.92,18.27,15.42,25.25,20.69c2.49,1.88,4.18,3.12,7.08,3.87", type: "㇏", start: [58.79, 62.82], end: [91.12, 87.38], dir: 37, endDir: 15, len: 40.8, num: [67.5, 67.63], part: 2 },
  ],
  parts: [
    { element: "宀", position: "top", radical: "general" },
    { element: "冖", parent: 0 },
    { element: "豕", position: "bottom" },
  ],
};

export default data;
