/*
 * KanjiVG stroke data for 小 (U+5C0F) — release 20260714, source file kanji/05c0f.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "小",
  code: "05c0f",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M54.71,18.37c1.4,1.4,2.26,3.13,2.26,5.77c0,14.56-0.26,54.91-0.26,59.87c0,11.25-7.21,1.5-8.71,0.25", type: "㇚", start: [54.71, 18.37], end: [48, 84.26], dir: 96, endDir: -140, len: 81, num: [45.5, 16.13] },
    { n: 2, d: "M31.95,47.68c0.17,0.82,0.1,1.72-0.34,2.9C29.5,56.38,24.38,66.25,16.75,73", type: "㇒", start: [31.95, 47.68], end: [16.75, 73], dir: 121, endDir: 139, len: 30.1, num: [31, 43.28] },
    { n: 3, d: "M80.96,47.12C86.62,52,95.25,64.62,97,72", type: "㇔", start: [80.96, 47.12], end: [97, 72], dir: 57, endDir: 77, len: 29.9, num: [72.5, 43.28] },
  ],
  parts: [

  ],
};

export default data;
