/*
 * KanjiVG stroke data for 少 (U+5C11) — release 20260714, source file kanji/05c11.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "少",
  code: "05c11",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M53.46,14c0.9,0.9,1.76,2.23,1.76,4.33c0,12.04-0.01,37.2-0.01,40.65c0,9.77-6.71,2.04-8.21,1.17", type: "㇚", start: [53.46, 14], end: [47, 60.15], dir: 98, endDir: -150, len: 58.5, num: [45.5, 14.5], part: 0 },
    { n: 2, d: "M36.65,29.04c0.12,1.26-0.02,2.17-0.58,3.32c-2.85,5.83-11.53,15.7-18.65,20.56", type: "㇒", start: [36.65, 29.04], end: [17.42, 52.92], dir: 129, endDir: 146, len: 31.4, num: [27.5, 28.5], part: 0 },
    { n: 3, d: "M77,30c7.23,2.73,16.13,9.04,19.25,14.5", type: "㇔", start: [77, 30], end: [96.25, 44.5], dir: 37, endDir: 60, len: 24.5, num: [67.5, 30.5], part: 0 },
    { n: 4, d: "M76.75,41c0.14,1.34,0.06,3.54-0.79,5.39C68.67,62.17,49.7,86.63,24,98", type: "㇒", start: [76.75, 41], end: [24, 98], dir: 133, endDir: 156, len: 80.1, num: [68.5, 42.5], part: 1 },
  ],
  parts: [
    { element: "小", radical: "tradit" },
    { element: "丿", radical: "nelson" },
  ],
};

export default data;
