/*
 * KanjiVG stroke data for 山 (U+5C71) — release 20260714, source file kanji/05c71.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "山",
  code: "05c71",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M52.49,15.5c1.38,1.38,2.26,3.5,2.26,5.75c0,0.75-0.22,58.3-0.25,59.25", type: "㇑a", start: [52.49, 15.5], end: [54.5, 80.5], dir: 88, endDir: 92, len: 65.6, num: [45.75, 10.63] },
    { n: 2, d: "M21.49,54.5c0.88,0.88,1.39,2.25,1.26,3.75c-0.58,6.99-1,16-2.5,23c-0.7,3.26,0.11,4,2,3.75c17-2.25,47.12-5.12,65.5-6", type: "㇄a", start: [21.49, 54.5], end: [87.75, 79], dir: 20, endDir: -3, len: 98.5, num: [12.75, 52.63] },
    { n: 3, d: "M89.24,49c0.94,0.94,1.64,2.38,1.51,4.25c-0.25,3.68-1.83,20.3-2.55,28.77c-0.22,2.64-0.39,4.51-0.45,4.98", type: "㇑", start: [89.24, 49], end: [87.75, 87], dir: 92, endDir: 97, len: 38.5, num: [83.25, 43.63] },
  ],
  parts: [

  ],
};

export default data;
