/*
 * KanjiVG stroke data for 川 (U+5DDD) — release 20260714, source file kanji/05ddd.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "川",
  code: "05ddd",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M27.22,25.68c0.91,1.57,1.18,3.45,1.19,5.37C28.5,43.5,28.5,69,17.39,84.15", type: "㇒", start: [27.22, 25.68], end: [17.39, 84.15], dir: 100, endDir: 126, len: 60.7, num: [18.5, 25.5] },
    { n: 2, d: "M53.75,23.63c0.94,0.94,1.41,2.37,1.41,3.9c0,0.58-0.01,28.48-0.08,41.71c-0.02,3.31-0.04,5.74-0.06,6.63", type: "㇑", start: [53.75, 23.63], end: [55.02, 75.87], dir: 89, endDir: 91, len: 52.6, num: [45.75, 23.5] },
    { n: 3, d: "M85.56,15.63c1.09,1.09,1.76,2.62,1.76,4.25c0,0.74,0.23,46.86,0.09,66.12c-0.03,4.31-0.06,7.61-0.09,8.63", type: "㇑", start: [85.56, 15.63], end: [87.32, 94.63], dir: 89, endDir: 92, len: 79.5, num: [75.5, 16.5] },
  ],
  parts: [

  ],
};

export default data;
