/*
 * KanjiVG stroke data for 左 (U+5DE6) — release 20260714, source file kanji/05de6.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "左",
  code: "05de6",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M20.75,40.17c2.95,0.49,5.68,0.29,8.64-0.05c14.5-1.68,29.75-4.47,47.22-5.96c2.83-0.24,5.87-0.58,8.64,0.26", type: "㇐", start: [20.75, 40.17], end: [85.25, 34.42], dir: -5, endDir: 17, len: 65, num: [10.5, 40.5], part: 0 },
    { n: 2, d: "M55.48,12.5c0.27,1.57,0.21,4.18-0.29,5.93C46.59,48.64,32.07,74.14,11.25,91", type: "㇒", start: [55.48, 12.5], end: [11.25, 91], dir: 119, endDir: 141, len: 92.1, num: [44.5, 13.5], part: 0 },
    { n: 3, d: "M43.25,64.59c1.25,0.29,2.38,0.29,3.86,0.17c4.86-0.37,17.91-2.17,26.92-3.77c1.88-0.33,3.97-0.5,5.97-0.11", type: "㇐", start: [43.25, 64.59], end: [80, 60.88], dir: -6, endDir: 11, len: 37.1, num: [45.5, 61.5], part: 1 },
    { n: 4, d: "M58.54,66.75c1.04,1.04,1.91,2.62,1.91,4.03c0,6.84,0.04,13.22,0.04,18.72", type: "㇑a", start: [58.54, 66.75], end: [60.49, 89.5], dir: 85, endDir: 90, len: 23.3, num: [51.5, 74.5], part: 1 },
    { n: 5, d: "M28.5,92.25c2.76,0.84,5.92,0.51,8.75,0.34c14.54-0.9,32.08-2.65,48.13-3.26c3.25-0.12,6.38-0.17,9.49,0.93", type: "㇐", start: [28.5, 92.25], end: [94.87, 90.26], dir: -2, endDir: 19, len: 66.6, num: [28.5, 89.13], part: 1 },
  ],
  parts: [
    { position: "kamae" },
    { element: "工", radical: "general" },
  ],
};

export default data;
