/*
 * KanjiVG stroke data for 帰 (U+5E30) — release 20260714, source file kanji/05e30.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "帰",
  code: "05e30",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M16.46,35.12c0.71,0.71,1.26,1.65,1.26,2.99c0,5.61-0.08,13.76-0.12,19.77c-0.01,1.77-0.02,3.35-0.02,4.63", type: "㇑", start: [16.46, 35.12], end: [17.58, 62.51], dir: 88, endDir: 90, len: 27.7, num: [6.75, 34.63], part: 0 },
    { n: 2, d: "M26.46,17.62c0.84,0.84,1.23,2.1,1.26,3.74c0.66,43.52-0.21,51.27-10.21,62.89", type: "㇒/㇚", start: [26.46, 17.62], end: [17.51, 84.25], dir: 98, endDir: 131, len: 69.4, num: [17.25, 18.13], part: 0 },
    { n: 3, d: "M45.75,15.5c1.01,0.24,2.51,0.63,4.18,0.43C57.5,15,71.38,13.38,78,12.25c1.52-0.26,3.42,0.75,3.05,2.44c-1.03,4.73-2.29,13.19-3.06,18.34c-0.22,1.49-0.41,2.74-0.54,3.62", type: "㇕", start: [45.75, 15.5], end: [77.45, 36.65], dir: 34, endDir: 98, len: 59.4, num: [38.25, 16.63], part: 2 },
    { n: 4, d: "M44.89,26.32c1.47,0.38,3.01,0.52,4.49,0.38c10.59-1,21.15-1.96,29.47-2.4", type: "㇐c", start: [44.89, 26.32], end: [78.85, 24.3], dir: -3, endDir: -3, len: 34.1, num: [36.75, 28.63], part: 2 },
    { n: 5, d: "M43.68,37.85c1.65,0.5,3.41,0.49,5.08,0.27c8.74-1.13,19.84-2.66,27.98-3.19", type: "㇐c", start: [43.68, 37.85], end: [76.74, 34.93], dir: -5, endDir: -4, len: 33.3, num: [36.75, 40.63], part: 2 },
    { n: 6, d: "M40.88,48.75c-0.09,3.63-2.32,9.83-3.12,12", type: "㇔", start: [40.88, 48.75], end: [37.76, 60.75], dir: 105, endDir: 110, len: 12.4, num: [33.75, 52.63], part: 3 },
    { n: 7, d: "M41.49,51.15c11.51-1.9,35.42-5.38,45.63-5.93C96,44.75,89.25,51,85.65,53.7", type: "㇖b", start: [41.49, 51.15], end: [85.65, 53.7], dir: 3, endDir: 143, len: 60.4, num: [42.75, 49.63], part: 3 },
    { n: 8, d: "M45.88,60.25c0.87,1,1.31,2.45,1.4,2.97c0.07,0.4,0,8.27-0.08,13.8c-0.02,1.64-0.04,2.48-0.06,3.22", type: "㇑", start: [45.88, 60.25], end: [47.14, 80.24], dir: 86, endDir: 92, len: 20.3, num: [39.75, 69.13], part: 4 },
    { n: 9, d: "M48.28,61.54c7.47-0.86,27.74-3.55,29.36-3.64c2.31-0.13,3.73,0.48,3.73,2.72c0,6.76-0.37,12.13-0.81,17.47c-0.51,6.28-4.2,0.04-5.08-0.87", type: "㇆a", start: [48.28, 61.54], end: [75.48, 77.22], dir: 30, endDir: -134, len: 61.1, num: [50.25, 58.63], part: 4 },
    { n: 10, d: "M61.84,50.88c0.91,1.12,1.15,2.12,1.15,3.47c0,0.44-0.01,27.54-0.08,38.66c-0.01,2.19-0.03,3.72-0.04,4.25", type: "㇑", start: [61.84, 50.88], end: [62.87, 97.26], dir: 89, endDir: 91, len: 46.7, num: [66.75, 55.63], part: 4 },
  ],
  parts: [
    { element: "刂", position: "left" },
    { element: "帚", position: "right" },
    { element: "⺕", radical: "nelson", parent: 1 },
    { element: "冖", parent: 1 },
    { element: "巾", radical: "tradit", parent: 1 },
  ],
};

export default data;
