/*
 * KanjiVG stroke data for 年 (U+5E74) — release 20260714, source file kanji/05e74.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "年",
  code: "05e74",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M40.01,11.89c0.24,1.61-0.01,2.86-0.84,4.46c-2.53,4.84-6.91,11.4-15.86,19.62", type: "㇒", start: [40.01, 11.89], end: [23.31, 35.97], dir: 125, endDir: 137, len: 30, num: [32.25, 11.5], part: 0 },
    { n: 2, d: "M39.13,23.62c2.25,0.38,4.4,0.18,5.79,0.03c11.7-1.27,21.33-2.9,33.22-4.07c2.3-0.23,4.2,0,5.35,0.26", type: "㇐", start: [39.13, 23.62], end: [83.49, 19.84], dir: -5, endDir: 13, len: 44.7, num: [46.5, 19.5], part: 1 },
    { n: 3, d: "M30.13,43.59c1.36,0.33,3.87,0.46,5.21,0.33c10.91-1.05,28.53-3.42,40.78-4.26c2.26-0.15,3.63,0.16,4.76,0.32", type: "㇐", start: [30.13, 43.59], end: [80.88, 39.98], dir: -4, endDir: 8, len: 51, num: [31.5, 41.5], part: 2 },
    { n: 4, d: "M33.75,44.5c1,1.25,1,1.97,1.01,3.5C34.8,52.33,35,65.29,35,66.25", type: "㇑a", start: [33.75, 44.5], end: [35, 66.25], dir: 87, endDir: 90, len: 22, num: [27.5, 53.5] },
    { n: 5, d: "M13.88,67.74c1.97,0.47,5.61,0.66,7.57,0.47c20.21-2.03,36.35-4.62,66.65-5.31c3.29-0.08,5.26,0.22,6.91,0.46", type: "㇐", start: [13.88, 67.74], end: [95.01, 63.36], dir: -3, endDir: 8, len: 81.4, num: [6.5, 69.5] },
    { n: 6, d: "M56.56,25.46c1.12,1.12,1.79,3.54,1.79,4.94c0,0.89-0.05,44.26-0.13,61.6c-0.01,3.12-0.03,5.39-0.05,6.38", type: "㇑", start: [56.56, 25.46], end: [58.17, 98.38], dir: 89, endDir: 91, len: 73.3, num: [50.5, 33.5], part: 3 },
  ],
  parts: [
    { element: "丿", radical: "nelson" },
    { element: "干", radical: "tradit", part: "1" },
    { element: "十", parent: 1 },
    { element: "干", radical: "tradit", part: "2" },
  ],
};

export default data;
