/*
 * KanjiVG stroke data for 店 (U+5E97) — release 20260714, source file kanji/05e97.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "店",
  code: "05e97",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M56.81,11.13c1.28,1.28,2.01,2.74,2.01,4.15c0,0.79,0.08,4.65-0.07,9.46", type: "㇑a", start: [56.81, 11.13], end: [58.75, 24.74], dir: 82, endDir: 92, len: 14.2, num: [48.5, 12.13], part: 0 },
    { n: 2, d: "M25.63,27.23c2.62,0.77,4.72,0.67,6.39,0.54C48,26.5,63.11,24.75,84.3,23.04c2.76-0.22,4.44,0.26,5.83,0.53", type: "㇐", start: [25.63, 27.23], end: [90.13, 23.57], dir: -3, endDir: 11, len: 64.8, num: [28.5, 24.5], part: 1 },
    { n: 3, d: "M28.99,28.5c0.88,0.88,1.18,2,1.16,3.38C29.88,54.88,27.25,78.75,14.5,91", type: "㇒", start: [28.99, 28.5], end: [14.5, 91], dir: 103, endDir: 136, len: 66.3, num: [22.5, 37.5], part: 1 },
    { n: 4, d: "M57.87,32.88c0.93,0.93,1.62,2.62,1.62,4.09c0,3.03-0.21,27.9-0.21,32.77", type: "㇑a", start: [57.87, 32.88], end: [59.28, 69.74], dir: 88, endDir: 90, len: 37.3, num: [48.5, 37.63], part: 3 },
    { n: 5, d: "M60.28,50.84c8.22-0.96,16.22-1.96,22.11-2.82c1.04-0.15,2.96,0,3.8,0.21", type: "㇐b", start: [60.28, 50.84], end: [86.19, 48.23], dir: -6, endDir: 14, len: 26.1, num: [63.5, 46.63], part: 3 },
    { n: 6, d: "M39.49,71.71c1,0.98,1.37,1.56,1.64,3c1.24,6.54,2.21,13.16,3.22,20.24c0.17,1.21,0.33,2.37,0.48,3.45", type: "㇑", start: [39.49, 71.71], end: [44.83, 98.4], dir: 79, endDir: 82, len: 27.5, num: [33.5, 79.5], part: 4 },
    { n: 7, d: "M41.78,73.18c12.31-1.73,32.97-3.68,39.91-4.33c3.3-0.31,4.47,2.39,4.16,3.79c-1.04,4.67-3.04,13.25-4.41,18.9", type: "㇕b", start: [41.78, 73.18], end: [81.44, 91.54], dir: 25, endDir: 104, len: 66.1, num: [42.5, 69.13], part: 4 },
    { n: 8, d: "M45.8,95.62C51.66,95,67.7,93.74,78,92.83c1.96-0.17,3.7-0.32,5.11-0.44", type: "㇐b", start: [45.8, 95.62], end: [83.11, 92.39], dir: -5, endDir: -5, len: 37.4, num: [48.5, 92.5], part: 4 },
  ],
  parts: [
    { element: "广", position: "tare", radical: "general" },
    { element: "厂", parent: 0 },
    { element: "占", position: "tarec" },
    { element: "卜", position: "top", parent: 2 },
    { element: "口", position: "bottom", parent: 2 },
  ],
};

export default data;
