/*
 * KanjiVG stroke data for 弟 (U+5F1F) — release 20260714, source file kanji/05f1f.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "弟",
  code: "05f1f",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M33.5,15c3.29,1.85,8.49,7.59,9.31,10.47", type: "㇔", start: [33.5, 15], end: [42.81, 25.47], dir: 48, endDir: 74, len: 14.2, num: [25.5, 13.5], part: 0 },
    { n: 2, d: "M67.75,11.5c0.08,0.89-0.06,1.73-0.43,2.54C66.1,17.24,62.6,22.58,58,26", type: "㇒", start: [67.75, 11.5], end: [58, 26], dir: 124, endDir: 143, len: 17.9, num: [60, 12], part: 0 },
    { n: 3, d: "M23.62,32.04c2.38,0.83,5.8,0.77,8.26,0.44C45,30.75,59,28.88,76.36,26.72c2.89-0.36,4.04,2.4,3.3,4.3c-0.76,1.96-2.56,7.92-3.16,10.73", type: "㇕c", start: [23.62, 32.04], end: [76.5, 41.75], dir: 10, endDir: 102, len: 71, num: [15.5, 30.13], part: 3 },
    { n: 4, d: "M24,47.5c1.5,0.38,3.38,0.43,5.25,0.3c11.25-0.8,31.63-2.92,45.15-4.55c1.54-0.19,3.11-0.25,4.36,0", type: "㇐", start: [24, 47.5], end: [78.76, 43.25], dir: -4, endDir: 11, len: 55, num: [26, 44.5], part: 3 },
    { n: 5, d: "M25.43,48.42c0.82,0.82,0.75,2.42,0,3.71c-1.68,2.87-3.6,6.04-4.12,6.84c-1.8,2.78-1.3,4.69,1.32,4.38c2.5-0.29,59.11-6.03,65.75-6.62c6.64-0.6,5.02,3.99,4.54,5.42C92,64.89,87.73,73.5,84.92,78.44c-4.17,7.31-6.92,1.31-8.67-0.98", type: "㇉", start: [25.43, 48.42], end: [76.25, 77.46], dir: 30, endDir: -127, len: 124.1, num: [17, 53], part: 3 },
    { n: 6, d: "M52.9,32.41c1.06,0.63,1.91,2.34,1.91,4.12c0,10.03,0.09,40.05-0.09,56.48c-0.03,2.78-0.07,5.16-0.12,7", type: "㇑", start: [52.9, 32.41], end: [54.6, 100.01], dir: 89, endDir: 92, len: 68.2, num: [45.5, 39.5], part: 4 },
    { n: 7, d: "M52.69,60.75c0.09,0.64,0.19,1.64-0.19,2.56c-2.22,5.39-16.5,20.21-34,27.44", type: "㇒", start: [52.69, 60.75], end: [18.5, 90.75], dir: 139, endDir: 158, len: 47, num: [38.25, 71.5], part: 5 },
  ],
  parts: [
    { element: "八", position: "top", radical: "nelson" },
    { position: "bottom" },
    { element: "弔", parent: 1 },
    { element: "弓", radical: "tradit", parent: 2 },
    { element: "丨", parent: 2 },
    { element: "丿", parent: 1 },
  ],
};

export default data;
