/*
 * KanjiVG stroke data for 後 (U+5F8C) — release 20260714, source file kanji/05f8c.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "後",
  code: "05f8c",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M34.25,18.38c0,1.3-0.24,2.26-0.93,3.05c-3.57,4.07-8.94,8.7-15.91,13.39", type: "㇒", start: [34.25, 18.38], end: [17.41, 34.82], dir: 136, endDir: 146, len: 24.1, num: [26.5, 18.5], part: 0 },
    { n: 2, d: "M38.75,36.62c0.14,1.32-0.42,2.67-1.13,3.79c-3.45,5.4-11.43,14.17-22.37,22.71", type: "㇒", start: [38.75, 36.62], end: [15.25, 63.12], dir: 132, endDir: 142, len: 36, num: [30.5, 39.5], part: 1 },
    { n: 3, d: "M28.4,54.36c0.81,0.81,1.38,2.02,1.38,3.28c0,0.68,0.03,25.57-0.07,35.86c-0.02,1.74-0.04,3.05-0.05,3.75", type: "㇑", start: [28.4, 54.36], end: [29.66, 97.25], dir: 88, endDir: 91, len: 43.3, num: [23.25, 66.5], part: 1 },
    { n: 4, d: "M61.16,12.62c0.29,1.07,0.21,2.43-0.39,3.54c-2.52,4.6-6.1,9.01-9.88,12.93c-1.01,1.05-1.26,2.17,0,2.68c2.96,1.19,6.3,3.11,8.88,5.07", type: "㇜", start: [61.16, 12.62], end: [59.77, 36.84], dir: 93, endDir: 37, len: 33.5, num: [52.5, 14.5], part: 3 },
    { n: 5, d: "M76.35,20.12c0.27,1.25-0.3,2.56-1,3.31c-7.6,8.19-16.6,16.57-26.61,25.32c-1.25,1.1-0.74,1.76,0.74,1.41C55.72,48.69,74.5,44.4,82.5,43", type: "㇜", start: [76.35, 20.12], end: [82.5, 43], dir: 75, endDir: -10, len: 77.1, num: [68.5, 21.5], part: 3 },
    { n: 6, d: "M77.88,36.25c3.66,2.21,9.46,9.07,10.38,12.5", type: "㇔", start: [77.88, 36.25], end: [88.26, 48.75], dir: 50, endDir: 75, len: 16.5, num: [78.5, 34.63], part: 3 },
    { n: 7, d: "M57.75,53c0.09,1.13,0.02,2.27-0.4,3.33c-2.2,5.51-7.08,13.22-15.6,20.92", type: "㇒", start: [57.75, 53], end: [41.75, 77.25], dir: 123, endDir: 138, len: 29.7, num: [49.5, 60.5], part: 4 },
    { n: 8, d: "M59.31,59.82c1.17,0.13,2.31,0.02,3.29-0.09c2.65-0.29,9.84-1.39,13.62-2.29c2.59-0.62,3.24,0.68,2.67,2.4C75.25,70.75,59.25,88.88,43.02,96.5", type: "㇇", start: [59.31, 59.82], end: [43.02, 96.5], dir: 114, endDir: 155, len: 74.3, num: [63.5, 56.5], part: 4 },
    { n: 9, d: "M54.75,67.5c2.52,0,19.5,15.75,31.17,24.23c2.31,1.68,4.74,3.38,7.58,4.01", type: "㇏", start: [54.75, 67.5], end: [93.5, 95.74], dir: 36, endDir: 13, len: 48.2, num: [53.25, 76.63], part: 4 },
  ],
  parts: [
    { element: "彳", position: "left", radical: "general" },
    { element: "亻", parent: 0 },
    { position: "right" },
    { element: "幺", parent: 2 },
    { element: "夂", parent: 2 },
  ],
};

export default data;
