/*
 * KanjiVG stroke data for 待 (U+5F85) — release 20260714, source file kanji/05f85.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "待",
  code: "05f85",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M35.33,15.25c0.15,1.08-0.22,1.8-0.92,2.65c-3.3,4-9.9,10.35-18.79,15.35", type: "㇒", start: [35.33, 15.25], end: [15.62, 33.25], dir: 138, endDir: 151, len: 27.3, num: [28.5, 15.5], part: 0 },
    { n: 2, d: "M35.84,32.75c0.07,0.75-0.17,2.1-0.64,3.03c-3.32,6.54-11.54,17.41-23.7,28.47", type: "㇒", start: [35.84, 32.75], end: [11.5, 64.25], dir: 128, endDir: 138, len: 40.3, num: [26.5, 37.5], part: 1 },
    { n: 3, d: "M25.97,52c1.01,1.01,1.41,2.5,1.41,3.88c0,5.46,0,27.73-0.05,37.12c-0.01,2.05-0.02,3.49-0.03,4", type: "㇑", start: [25.97, 52], end: [27.3, 97], dir: 88, endDir: 91, len: 45.4, num: [20.5, 65.5], part: 1 },
    { n: 4, d: "M48.11,27.78c2.02,0.35,3.66,0.24,5.4,0.02c6.01-0.75,17.57-2.51,25.74-2.93c1.72-0.09,3.42-0.18,5.11,0.21", type: "㇐", start: [48.11, 27.78], end: [84.36, 25.08], dir: -4, endDir: 13, len: 36.5, num: [40.5, 28.5], part: 3 },
    { n: 5, d: "M64.35,11.87c1.14,1.14,1.51,2.32,1.51,4c0,8.76-0.06,22.88-0.06,25.35", type: "㇑a", start: [64.35, 11.87], end: [65.8, 41.22], dir: 87, endDir: 90, len: 29.8, num: [54.5, 13.5], part: 3 },
    { n: 6, d: "M39.63,44.1c2.87,0.65,5.83,0.36,8.61,0.05c15.05-1.65,30.01-3.28,42.26-4.08c2.44-0.16,4.98-0.33,7.38,0.15", type: "㇐", start: [39.63, 44.1], end: [97.88, 40.22], dir: -4, endDir: 11, len: 58.5, num: [40.5, 41.5], part: 3 },
    { n: 7, d: "M40.03,60.99c2.22,0.51,4.77,0.43,6.99,0.25c10.69-0.9,30.7-3.37,41.36-4.03c2.47-0.15,4.91-0.3,7.34,0.29", type: "㇐", start: [40.03, 60.99], end: [95.72, 57.5], dir: -4, endDir: 14, len: 56, num: [34.5, 59.5], part: 4 },
    { n: 8, d: "M76.25,47.5c1,1.25,1.91,3,1.91,4.9c0,12.98-0.13,36.67-0.13,40.77c0,7.31-4.78,3.71-8.05-0.04", type: "㇚", start: [76.25, 47.5], end: [69.98, 93.13], dir: 98, endDir: -131, len: 58.9, num: [68.25, 54.13], part: 4 },
    { n: 9, d: "M54.03,70.38c2.91,1.83,7.51,7.53,8.24,10.38", type: "㇔", start: [54.03, 70.38], end: [62.27, 80.76], dir: 52, endDir: 76, len: 13.4, num: [45.75, 73.63], part: 4 },
  ],
  parts: [
    { element: "彳", position: "left", radical: "general" },
    { element: "亻", parent: 0 },
    { element: "寺", position: "right" },
    { element: "土", position: "top", parent: 2 },
    { element: "寸", position: "bottom", parent: 2 },
  ],
};

export default data;
