/*
 * KanjiVG stroke data for 心 (U+5FC3) — release 20260714, source file kanji/05fc3.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "心",
  code: "05fc3",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M16.88,52.75c0,6.32-1.46,17.69-3.75,23", type: "㇔", start: [16.88, 52.75], end: [13.13, 75.75], dir: 99, endDir: 113, len: 23.4, num: [11.25, 50.5] },
    { n: 2, d: "M31.25,49.25c9,22.75,27,35.5,53.25,32.25c7.75-0.96,7.25-4.75,3-9.5", type: "㇃", start: [31.25, 49.25], end: [87.5, 72], dir: 22, endDir: -132, len: 82.1, num: [27.75, 45] },
    { n: 3, d: "M50.25,26c2,5.12,7.5,13.75,8.75,7.75", type: "㇔a", start: [50.25, 26], end: [59, 33.75], dir: 42, endDir: -78, len: 15.3, num: [43.5, 23.5] },
    { n: 4, d: "M85.5,30c4,2.75,7.62,7,10.5,14", type: "㇔", start: [85.5, 30], end: [96, 44], dir: 53, endDir: 68, len: 17.8, num: [77.5, 29.5] },
  ],
  parts: [

  ],
};

export default data;
