/*
 * KanjiVG stroke data for 思 (U+601D) — release 20260714, source file kanji/0601d.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "思",
  code: "0601d",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M26.25,19.11c1.26,1.26,2.03,2.95,2.29,4.64c1.21,8.13,2.4,17.99,3.26,26.47c0.15,1.45,0.29,2.81,0.42,4.03", type: "㇑", start: [26.25, 19.11], end: [32.22, 54.25], dir: 80, endDir: 84, len: 36, num: [20.5, 26.5], part: 0 },
    { n: 2, d: "M28.75,21c18.13-2.25,36-4,48.68-4.52c3.81-0.16,4.75,2.83,4.54,4.23c-0.65,4.39-2.25,17.38-3.9,26.31c-0.28,1.5-0.57,2.9-0.86,4.15", type: "㇕a", start: [28.75, 21], end: [77.21, 51.17], dir: 32, endDir: 103, len: 86.9, num: [31.5, 17.5], part: 0 },
    { n: 3, d: "M53.32,19.5c0.84,0.84,1.3,2.42,1.29,3.6c-0.07,6.5,0.06,22.72,0.06,24.65", type: "㇑a", start: [53.32, 19.5], end: [54.67, 47.75], dir: 87, endDir: 90, len: 28.6, num: [46.5, 27.13], part: 0 },
    { n: 4, d: "M31.5,35.75c10.25-1.12,36.75-3.75,47.35-3.97", type: "㇐a", start: [31.5, 35.75], end: [78.85, 31.78], dir: -5, endDir: -1, len: 47.5, num: [34.5, 32.5], part: 0 },
    { n: 5, d: "M33.25,51.25C44.06,49.86,67.5,48,77.33,47.59", type: "㇐a", start: [33.25, 51.25], end: [77.33, 47.59], dir: -5, endDir: -2, len: 44.2, num: [36.5, 47.5], part: 0 },
    { n: 6, d: "M23.11,69.79C22.62,76,20.83,83.92,19,88.42", type: "㇔", start: [23.11, 69.79], end: [19, 88.42], dir: 102, endDir: 112, len: 19.1, num: [17.5, 67.63], part: 1 },
    { n: 7, d: "M34.35,64.42c5.15,15.83,21.36,30.41,47.26,28.12c8.89-0.79,8.39-2.79,3.2-8.1", type: "㇃", start: [34.35, 64.42], end: [84.81, 84.44], dir: 22, endDir: -134, len: 74.2, num: [27.75, 65.5], part: 1 },
    { n: 8, d: "M55.47,61.5c2.15,4.88,5.87,9.87,7.01,4.47", type: "㇔a", start: [55.47, 61.5], end: [62.48, 65.97], dir: 33, endDir: -78, len: 12, num: [48.5, 61.63], part: 1 },
    { n: 9, d: "M83,60.75c3.62,2.5,7.75,6.62,10.25,11.72", type: "㇔", start: [83, 60.75], end: [93.25, 72.47], dir: 49, endDir: 64, len: 15.7, num: [73.5, 61.63], part: 1 },
  ],
  parts: [
    { element: "田", position: "top", radical: "nelson" },
    { element: "心", position: "bottom", radical: "tradit" },
  ],
};

export default data;
