/*
 * KanjiVG stroke data for 手 (U+624B) — release 20260714, source file kanji/0624b.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "手",
  code: "0624b",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M61.48,11.5c0.02,1-0.61,1.88-1.67,2.9c-3.27,3.15-13.69,8.23-28.57,11.85", type: "㇒", start: [61.48, 11.5], end: [31.24, 26.25], dir: 154, endDir: 166, len: 34.6, num: [53.5, 11.5] },
    { n: 2, d: "M26.38,42.92c1.8,0.46,3.61,0.67,5.68,0.38C46,41.38,58.4,39,71.37,37.75c1.92-0.19,4.62-0.38,7.25,0.04", type: "㇐", start: [26.38, 42.92], end: [78.62, 37.79], dir: -6, endDir: 9, len: 52.7, num: [17.5, 45.5] },
    { n: 3, d: "M13.27,62.87c2.71,0.63,4.86,0.6,7.22,0.38c22.63-2.12,46.13-5.62,67.7-7c2.01-0.13,4.83,0,7.46,0.37", type: "㇐", start: [13.27, 62.87], end: [95.65, 56.62], dir: -4, endDir: 8, len: 82.8, num: [5.5, 66.5] },
    { n: 4, d: "M48.88,23.55C60.38,31,62.73,63.66,57.83,89.87c-2.08,11.13-8.64,2.34-9.89,1.17", type: "㇁", start: [48.88, 23.55], end: [47.94, 91.04], dir: 91, endDir: -137, len: 84.3, num: [44.5, 32.5] },
  ],
  parts: [

  ],
};

export default data;
