/*
 * KanjiVG stroke data for 持 (U+6301) — release 20260714, source file kanji/06301.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "持",
  code: "06301",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M15.67,37c1.46,0.5,3.09,0.44,5.08,0.25c2.19-0.21,12.99-2.13,19.01-2.92c1.19-0.16,2.19-0.25,2.9-0.25", type: "㇐", start: [15.67, 37], end: [42.66, 34.08], dir: -6, endDir: 0, len: 27.3, num: [9.5, 39.13], part: 0 },
    { n: 2, d: "M30.77,13.83c1.14,1.14,1.76,2.92,1.76,5.02c0,14.56-0.01,62.92-0.01,67.87c0,11.52-6.21,2.5-7.71,1.25", type: "㇚", start: [30.77, 13.83], end: [24.81, 87.97], dir: 95, endDir: -140, len: 87.4, num: [21.5, 15.5], part: 0 },
    { n: 3, d: "M14.38,65.87c1.37,0.45,2.71,0.29,4.2-0.74c1.55-1.08,12.99-10.2,19.55-15.38", type: "㇀", start: [14.38, 65.87], end: [38.13, 49.75], dir: -34, endDir: -38, len: 29.3, num: [6.75, 69.5], part: 0 },
    { n: 4, d: "M50.71,29.03c1.41,0.22,3.56,0.2,4.68,0.06c7.48-0.96,18.86-2.34,26.76-3.06c1.86-0.17,2.99,0.15,3.92,0.3", type: "㇐", start: [50.71, 29.03], end: [86.07, 26.33], dir: -4, endDir: 9, len: 35.6, num: [48.5, 26.5], part: 2 },
    { n: 5, d: "M66.95,11.62c0.78,0.78,1.36,1.99,1.36,3.5c0,8.26,0.02,26.13,0.02,28.6", type: "㇑a", start: [66.95, 11.62], end: [68.33, 43.72], dir: 88, endDir: 90, len: 32.5, num: [57.5, 13.5], part: 2 },
    { n: 6, d: "M44.63,45.35c1.53,0.44,4.32,0.6,5.85,0.44c12.52-1.29,26.9-3.16,39.07-3.99c2.53-0.17,4.06,0.21,5.34,0.43", type: "㇐", start: [44.63, 45.35], end: [94.89, 42.23], dir: -4, endDir: 10, len: 50.5, num: [46.5, 42.5], part: 2 },
    { n: 7, d: "M44.57,60.99c1.77,0.46,5.01,0.64,6.79,0.46c10.26-1.07,27.3-3.2,37.82-3.89c2.93-0.19,4.72,0.22,6.19,0.44", type: "㇐", start: [44.57, 60.99], end: [95.37, 58], dir: -3, endDir: 9, len: 51.1, num: [45.5, 58.5], part: 3 },
    { n: 8, d: "M77.06,46.08c1.12,1.12,1.72,3.04,1.72,4.56c0,12.03-0.09,34.43-0.09,38.52c0,10.21-5.31,3.08-7.24,0.71", type: "㇚", start: [77.06, 46.08], end: [71.45, 89.87], dir: 97, endDir: -129, len: 56.9, num: [71.5, 54.13], part: 3 },
    { n: 9, d: "M56.25,70.5c2.58,1.59,6.66,6.53,7.3,9", type: "㇔", start: [56.25, 70.5], end: [63.55, 79.5], dir: 51, endDir: 75, len: 11.7, num: [48.5, 72.5], part: 3 },
  ],
  parts: [
    { element: "扌", position: "left", radical: "general" },
    { element: "寺", position: "right" },
    { element: "土", parent: 1 },
    { element: "寸", parent: 1 },
  ],
};

export default data;
