/*
 * KanjiVG stroke data for 新 (U+65B0) — release 20260714, source file kanji/065b0.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "新",
  code: "065b0",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M33.72,12.76c0.88,0.88,1.53,2.49,1.53,4.35c0,2.63,0.01,1.9,0.02,9.04", type: "㇑a", start: [33.72, 12.76], end: [35.27, 26.15], dir: 83, endDir: 90, len: 13.8, num: [26.25, 13.5], part: 2 },
    { n: 2, d: "M18.32,28.69c1.19,0.11,2.61,0.17,3.79,0.03c7.4-0.84,18.02-2.59,25.62-3.22c1.98-0.16,3.19-0.03,4.18,0.02", type: "㇐", start: [18.32, 28.69], end: [51.91, 25.52], dir: -5, endDir: 3, len: 33.8, num: [10.5, 29.5], part: 2 },
    { n: 3, d: "M23.62,34.38c3.39,4.82,4.03,8.08,4.34,11.36", type: "㇔", start: [23.62, 34.38], end: [27.96, 45.74], dir: 69, endDir: 85, len: 12.3, num: [17.5, 39.5], part: 3 },
    { n: 4, d: "M45.59,29.5c0.62,1.09,0.38,2.59-0.08,3.75c-1.65,4.12-4.74,10.59-5.88,12.61", type: "㇒", start: [45.59, 29.5], end: [39.63, 45.86], dir: 110, endDir: 119, len: 17.8, num: [37.5, 35.5], part: 3 },
    { n: 5, d: "M14.17,50.95c1.78,0.27,3.57,0.27,5.34,0.05c7.96-1.02,21.06-2.74,29.12-3.36c1.96-0.15,3.91-0.03,5.87,0.11", type: "㇐", start: [14.17, 50.95], end: [54.5, 47.75], dir: -5, endDir: 4, len: 40.5, num: [6.75, 52.63], part: 3 },
    { n: 6, d: "M16.76,63.42c0.83,0.22,3.05,0.44,5.23,0.18c8.88-1.09,17.01-2.34,26.08-3.01c2.2-0.16,2.76-0.23,4.13,0", type: "㇐", start: [16.76, 63.42], end: [52.2, 60.59], dir: -5, endDir: 10, len: 35.7, num: [9.5, 66.5], part: 4 },
    { n: 7, d: "M34.38,51c1.12,1.12,1.5,2.75,1.5,4.22c0,1.31-0.15,24.25-0.25,34.78c-0.02,2.8-0.05,4.69-0.06,5", type: "㇑", start: [34.38, 51], end: [35.57, 95], dir: 88, endDir: 92, len: 44.4, num: [28.5, 59.5], part: 4 },
    { n: 8, d: "M34.25,62.84c0,1.41-0.35,2.47-0.87,3.37c-4.25,7.45-12.94,17.12-19.63,21.04", type: "㇒", start: [34.25, 62.84], end: [13.75, 87.25], dir: 130, endDir: 150, len: 32.5, num: [21.5, 73.5], part: 4 },
    { n: 9, d: "M39.25,68.5c4.71,2.98,7.9,5.97,9.49,8.43", type: "㇔/㇏", start: [39.25, 68.5], end: [48.74, 76.93], dir: 42, endDir: 57, len: 12.8, num: [45.5, 70.5], part: 4 },
    { n: 10, d: "M82.74,17.44c-0.12,0.93-0.46,2.3-1.27,3.21C76.25,26.5,70.5,30.62,61.69,35.7", type: "㇒", start: [82.74, 17.44], end: [61.69, 35.7], dir: 139, endDir: 150, len: 28.5, num: [71.5, 18.5], part: 5 },
    { n: 11, d: "M59.2,35.14c0.83,0.83,1.53,2.28,1.53,3.96c0,29.15-2.36,38.52-8.98,48.4", type: "㇒", start: [59.2, 35.14], end: [51.75, 87.5], dir: 98, endDir: 124, len: 54.4, num: [50.5, 42.13], part: 5 },
    { n: 12, d: "M62.89,47.36c1.98-0.11,3.36-0.31,4.54-0.48c7.82-1.13,18.82-2.38,26.29-3.3c1.18-0.15,3.25-0.17,3.99,0", type: "㇐", start: [62.89, 47.36], end: [97.71, 43.58], dir: -6, endDir: 13, len: 35.1, num: [64.5, 44.5], part: 5 },
    { n: 13, d: "M80.32,48.54c0.95,0.95,1.59,2.21,1.59,3.8c0,0.93,0.24,27.72,0.16,40.16c-0.02,2.33-0.04,4.17-0.06,5.25", type: "㇑", start: [80.32, 48.54], end: [82.01, 97.75], dir: 88, endDir: 91, len: 49.6, num: [71.5, 56.5], part: 5 },
  ],
  parts: [
    { position: "left" },
    { element: "立", parent: 0 },
    { element: "亠", position: "top", parent: 1 },
    { position: "bottom", parent: 1 },
    { element: "木", parent: 0 },
    { element: "斤", position: "right", radical: "general" },
  ],
};

export default data;
