/*
 * KanjiVG stroke data for 方 (U+65B9) — release 20260714, source file kanji/065b9.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "方",
  code: "065b9",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M52.86,12c1.07,1.07,1.73,2.5,1.73,4.41c0,4.84-0.15,7.84-0.15,11.65", type: "㇑a", start: [52.86, 12], end: [54.44, 28.06], dir: 84, endDir: 90, len: 16.5, num: [44.25, 12.5], part: 0 },
    { n: 2, d: "M15.5,31.61c2.5,0.64,6.38,0.89,10.02,0.55C43.97,30.41,67.12,28,85.87,27.2c3.88-0.16,6.36,0.05,9.25,0.7", type: "㇐", start: [15.5, 31.61], end: [95.12, 27.9], dir: -3, endDir: 13, len: 79.9, num: [8.5, 32.5], part: 0 },
    { n: 3, d: "M53.48,47.2c6.64,1.17,13.39,0.92,18.51,0.41c3.41-0.34,5.18,1.75,4.67,4.36c-2.03,10.4-10.53,33.53-16.54,41.1c-4.79,6.04-7.12,1.17-10.09-2.07", type: "㇆a", start: [53.48, 47.2], end: [50.03, 91], dir: 95, endDir: -133, len: 83.9, num: [58.5, 45.13], part: 1 },
    { n: 4, d: "M54.51,32.75c0.49,1.5,0.39,3.19-0.19,4.88C50.3,49.29,38.68,72.85,20.62,83.88", type: "㇒", start: [54.51, 32.75], end: [20.62, 83.88], dir: 124, endDir: 149, len: 63.2, num: [45.5, 39.5], part: 1 },
  ],
  parts: [
    { element: "亠", position: "top" },
    { position: "bottom" },
  ],
};

export default data;
