/*
 * KanjiVG stroke data for 日 (U+65E5) — release 20260714, source file kanji/065e5.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "日",
  code: "065e5",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M31.5,24.5c1.12,1.12,1.74,2.75,1.74,4.75c0,1.6-0.16,38.11-0.09,53.5c0.02,3.82,0.05,6.35,0.09,6.75", type: "㇑", start: [31.5, 24.5], end: [33.24, 89.5], dir: 88, endDir: 84, len: 65.4, num: [25.25, 32.63] },
    { n: 2, d: "M33.48,26c0.8-0.05,37.67-3.01,40.77-3.25c3.19-0.25,5,1.75,5,4.25c0,4-0.22,40.84-0.23,56c0,3.48,0,5.72,0,6", type: "㇕a", start: [33.48, 26], end: [79.02, 89], dir: 54, endDir: 90, len: 110.4, num: [34.5, 22.5] },
    { n: 3, d: "M34.22,55.25c7.78-0.5,35.9-2.5,44.06-2.75", type: "㇐a", start: [34.22, 55.25], end: [78.28, 52.5], dir: -4, endDir: -2, len: 44.1, num: [37.5, 51.5] },
    { n: 4, d: "M34.23,86.5c10.52-0.75,34.15-2.12,43.81-2.25", type: "㇐a", start: [34.23, 86.5], end: [78.04, 84.25], dir: -3, endDir: -1, len: 43.9, num: [37.5, 83.5] },
  ],
  parts: [

  ],
};

export default data;
