/*
 * KanjiVG stroke data for 時 (U+6642) — release 20260714, source file kanji/06642.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "時",
  code: "06642",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M16,29.84c0.75,0.66,1.21,1.62,1.21,3.07c0,1.18-0.16,30.08-0.21,40.85c-0.01,2.42-0.02,3.95-0.02,4.08", type: "㇑", start: [16, 29.84], end: [16.98, 77.84], dir: 89, endDir: 90, len: 48.3, num: [9.75, 39.13], part: 0 },
    { n: 2, d: "M17.78,30.74c4.65-0.63,16.12-2.07,17.6-2.25c1.52-0.18,3,1.5,2.88,2.57c-0.24,2.17-0.36,24.9-0.35,40.79c0,1.63-0.12,3.35-0.12,4.43", type: "㇕a", start: [17.78, 30.74], end: [37.79, 76.28], dir: 66, endDir: 90, len: 67.3, num: [18.5, 27.5], part: 0 },
    { n: 3, d: "M18.75,52c4.5-0.75,13.5-2.12,18.22-2.35", type: "㇐a", start: [18.75, 52], end: [36.97, 49.65], dir: -7, endDir: -3, len: 18.4, num: [21.5, 48.13], part: 0 },
    { n: 4, d: "M17.8,74.52c6.2-0.92,11.45-1.89,18.94-2.7", type: "㇐a", start: [17.8, 74.52], end: [36.74, 71.82], dir: -8, endDir: -6, len: 19.1, num: [21.33, 70.5], part: 0 },
    { n: 5, d: "M51.44,29.03c1.37,0.44,3.63,0.34,5,0.19c9.79-1.09,16.34-2.34,25.62-3.08c2.27-0.18,3.9-0.04,5.04,0.18", type: "㇐", start: [51.44, 29.03], end: [87.1, 26.32], dir: -4, endDir: 11, len: 35.9, num: [45.5, 27.13], part: 2 },
    { n: 6, d: "M67.59,11.37c0.89,0.9,1.59,2.24,1.59,3.75c0,8.39,0.03,27.02,0.03,27.6", type: "㇑a", start: [67.59, 11.37], end: [69.21, 42.72], dir: 87, endDir: 90, len: 31.8, num: [58.5, 11.5], part: 2 },
    { n: 7, d: "M45.38,45.35c1.49,0.44,4.21,0.59,5.71,0.44c11.29-1.16,25.66-3.29,39.2-3.99c2.48-0.13,3.97,0.21,5.21,0.43", type: "㇐", start: [45.38, 45.35], end: [95.5, 42.23], dir: -4, endDir: 10, len: 50.4, num: [45.75, 42.13], part: 2 },
    { n: 8, d: "M46,60.99c1.43,0.46,4.04,0.58,5.49,0.46c12.01-1.07,26.89-3.07,39.07-3.89c2.38-0.16,4.41,0.22,5.6,0.44", type: "㇐", start: [46, 60.99], end: [96.16, 58], dir: -3, endDir: 10, len: 50.4, num: [44.25, 57.13], part: 3 },
    { n: 9, d: "M78.07,46.08c1.11,1.11,1.66,2.56,1.71,5.06c0.23,12.03-0.09,34.43-0.09,38.52c0,9.83-5.42,2.19-7.66-0.04", type: "㇚", start: [78.07, 46.08], end: [72.03, 89.62], dir: 98, endDir: -135, len: 57.5, num: [71.25, 54.13], part: 3 },
    { n: 10, d: "M56.75,70.38c2.87,1.76,6.55,6.38,7.27,9.12", type: "㇔", start: [56.75, 70.38], end: [64.02, 79.5], dir: 51, endDir: 75, len: 11.9, num: [47.25, 76.63], part: 3 },
  ],
  parts: [
    { element: "日", position: "left", radical: "general" },
    { element: "寺", position: "right" },
    { element: "土", parent: 1 },
    { element: "寸", parent: 1 },
  ],
};

export default data;
