/*
 * KanjiVG stroke data for 曜 (U+66DC) — release 20260714, source file kanji/066dc.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "曜",
  code: "066dc",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M15.5,29.81c1,0.69,1.61,2.1,1.61,3.52c0,1.42-0.2,40.33-0.2,41.04c0,0.71-0.05,1.76-0.05,2.88", type: "㇑", start: [15.5, 29.81], end: [16.86, 77.25], dir: 88, endDir: 90, len: 47.9, num: [8.25, 37.63], part: 0 },
    { n: 2, d: "M18.06,31.1c4.41-0.66,14.19-2.61,15.41-2.61c1.78,0,2.54,1.75,2.54,3.02c0,2.14-0.31,25.27-0.3,40.9c0,1.61-0.1,2.31-0.1,3.38", type: "㇕a", start: [18.06, 31.1], end: [35.61, 75.79], dir: 69, endDir: 90, len: 64.3, num: [18.5, 27.13], part: 0 },
    { n: 3, d: "M18.42,51.59c3.71-0.46,11.71-1.59,15.98-2.03", type: "㇐a", start: [18.42, 51.59], end: [34.4, 49.56], dir: -7, endDir: -6, len: 16.1, num: [21.5, 47.5], part: 0 },
    { n: 4, d: "M18.12,74.29c4.38-0.42,10.63-1.67,16.08-2.17", type: "㇐a", start: [18.12, 74.29], end: [34.2, 72.12], dir: -8, endDir: -5, len: 16.2, num: [21.75, 69.13], part: 0 },
    { n: 5, d: "M41.5,16.5c1.5,0.75,2.5,0.75,4.75,0.5S56.5,15.5,58,15.25s3.5,1.5,3.5,3c0,1.22-0.17,14.07-0.23,20c-0.01,1.35-0.02,2.33-0.02,2.75", type: "㇆", start: [41.5, 16.5], end: [61.25, 41], dir: 51, endDir: 90, len: 44.6, num: [38.5, 13.5], part: 3 },
    { n: 6, d: "M43.75,28.25c1.25,0.38,2.98,0.16,4,0c2.38-0.38,9.75-2,12-2.25", type: "㇐c/㇔", start: [43.75, 28.25], end: [59.75, 26], dir: -8, endDir: -6, len: 16.2, num: [39.5, 26.5], part: 3 },
    { n: 7, d: "M45,38.75c1.25,0.38,2.5,0.25,3.5,0s9.25-2,11.5-2.25", type: "㇐c/㇀", start: [45, 38.75], end: [60, 36.5], dir: -9, endDir: -6, len: 15.3, num: [39.5, 39.13], part: 3 },
    { n: 8, d: "M70.75,14.75c1.5,0.75,2.75,1,5,0.75s12.5-1.75,14-2s3.5,1.5,3.5,3c0,1.19-0.16,13.38-0.22,19.5C93.01,37.6,93,38.78,93,39.25", type: "㇆", start: [70.75, 14.75], end: [93, 39.25], dir: 48, endDir: 90, len: 47.1, num: [68.5, 11.5], part: 4 },
    { n: 9, d: "M74.25,24.5c1.25,0.5,2.99,0.45,4,0.25c2.5-0.5,11.25-2,13.5-2.25", type: "㇐c/㇔", start: [74.25, 24.5], end: [91.75, 22.5], dir: -7, endDir: -6, len: 17.7, num: [68.25, 24.13], part: 4 },
    { n: 10, d: "M74,35.75c1.5,0.38,3,0.25,4,0s11.5-2,13.75-2.25", type: "㇐c/㇀", start: [74, 35.75], end: [91.75, 33.5], dir: -7, endDir: -6, len: 18, num: [66.75, 34.5], part: 4 },
    { n: 11, d: "M54.25,45c0.15,1.27-0.04,2.93-0.52,4.02c-3.07,6.93-6.95,12.8-13.98,21.23", type: "㇒", start: [54.25, 45], end: [39.75, 70.25], dir: 120, endDir: 130, len: 29.6, num: [42.75, 49.63], part: 6 },
    { n: 12, d: "M50.55,57.79c0.45,0.96,0.65,1.7,0.7,2.95c0.24,7.07-0.2,22.81-0.27,31.26c-0.02,2.51-0.01,4.47,0.06,5.5", type: "㇑", start: [50.55, 57.79], end: [51.04, 97.5], dir: 89, endDir: 86, len: 39.8, num: [39.75, 75], part: 6 },
    { n: 13, d: "M74.25,42.75c0.05,0.54-0.01,1.25-0.17,1.72c-1,2.96-2.27,5.25-4.57,8.86", type: "㇒", start: [74.25, 42.75], end: [69.51, 53.33], dir: 114, endDir: 123, len: 11.7, num: [77, 45], part: 5 },
    { n: 14, d: "M50.98,56.53c5.87-0.68,25.46-2.41,34.02-3.27c1.92-0.19,3.25-0.26,4.86,0.08", type: "㇐b", start: [50.98, 56.53], end: [89.86, 53.34], dir: -5, endDir: 12, len: 39.1, num: [55, 53.5], part: 5 },
    { n: 15, d: "M69.83,55.88c0.67,1.12,1.12,2.27,1.12,2.83c0,5.71,0.29,22.65,0.08,31.64", type: "㇑a", start: [69.83, 55.88], end: [71.03, 90.35], dir: 88, endDir: 91, len: 34.7, num: [73, 62.38], part: 5 },
    { n: 16, d: "M52.51,68.36c5.25-0.53,21.05-2.1,29.5-2.84c2-0.17,3.25-0.02,4.91,0.03", type: "㇐b", start: [52.51, 68.36], end: [86.92, 65.55], dir: -5, endDir: 2, len: 34.6, num: [54.12, 65.75], part: 5 },
    { n: 17, d: "M52.18,79.71c5.66-0.46,22.39-1.91,31.08-2.66c2.3-0.2,3.23-0.05,4.61,0.09", type: "㇐b", start: [52.18, 79.71], end: [87.87, 77.14], dir: -4, endDir: 6, len: 35.8, num: [54.12, 76.88], part: 5 },
    { n: 18, d: "M52.11,93.02c5.61-0.65,26.25-2.06,36.63-2.86c2.93-0.23,4.26-0.16,5.7,0", type: "㇐b", start: [52.11, 93.02], end: [94.44, 90.16], dir: -4, endDir: 6, len: 42.5, num: [53.88, 90], part: 5 },
  ],
  parts: [
    { element: "日", position: "left", radical: "general" },
    { element: "翟", position: "right" },
    { element: "羽", position: "top", parent: 1 },
    { position: "left", parent: 2 },
    { position: "right", parent: 2 },
    { element: "隹", position: "bottom", parent: 1 },
    { element: "亻", parent: 5 },
  ],
};

export default data;
