/*
 * KanjiVG stroke data for 書 (U+66F8) — release 20260714, source file kanji/066f8.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "書",
  code: "066f8",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M30.74,20.63c2.01,0.49,3.84,0.58,5.91,0.39c9.45-0.89,28.54-2.97,37.54-3.64c2.92-0.22,4.18,1.24,3.66,3.55c-0.4,1.76-2.56,9.62-3.88,16.56", type: "㇕c", start: [30.74, 20.63], end: [73.97, 37.49], dir: 21, endDir: 101, len: 66.9, num: [23.5, 21.5], part: 1 },
    { n: 2, d: "M11.89,32.34c3.17,0.66,5.87,0.47,9.58,0.19c20.16-1.52,48.41-3.9,67.91-4.64c4.08-0.16,7.07,0.26,8.91,0.59", type: "㇐", start: [11.89, 32.34], end: [98.29, 28.48], dir: -3, endDir: 10, len: 86.6, num: [4.5, 33.5], part: 1 },
    { n: 3, d: "M29.86,41.38c1.64,0.49,3.39,0.52,4.84,0.44c9.67-0.57,27.55-2.07,37.43-2.85c1.93-0.15,3.14-0.08,4.59,0.07", type: "㇐", start: [29.86, 41.38], end: [76.72, 39.04], dir: -3, endDir: 6, len: 47, num: [22.5, 41.5], part: 1 },
    { n: 4, d: "M30.04,52.06c1.47,0.26,3.65,0.54,5.12,0.43c12.34-0.98,25.59-2.23,36.78-3.31c2.43-0.23,4.41-0.19,5.63-0.07", type: "㇐", start: [30.04, 52.06], end: [77.57, 49.11], dir: -4, endDir: 6, len: 47.7, num: [21.75, 52.5], part: 0 },
    { n: 5, d: "M17,63.44c2,0.58,5.67,0.57,7.66,0.41c20.78-1.7,42.92-3.93,61.09-4.48c3.33-0.1,5.33,0.15,6.99,0.42", type: "㇐", start: [17, 63.44], end: [92.74, 59.79], dir: -3, endDir: 9, len: 76, num: [9.5, 64.5], part: 0 },
    { n: 6, d: "M52.69,9.52c1.33,1.33,1.95,2.98,1.95,4.71c0,5.67,0.22,33.72,0.31,45.77", type: "㇑a", start: [52.69, 9.52], end: [54.95, 60], dir: 87, endDir: 90, len: 51, num: [42.5, 10.5], part: 2 },
    { n: 7, d: "M31.25,71.75c0.43,0.46,1.24,1.44,1.43,2.7c1.11,7.42,2.22,14.33,3.18,20.74c0.18,1.2,0.34,2.38,0.49,3.57", type: "㇑", start: [31.25, 71.75], end: [36.35, 98.76], dir: 79, endDir: 83, len: 27.7, num: [23.5, 77.5], part: 3 },
    { n: 8, d: "M33.75,73.75c14.98-2.05,36.1-3.71,44.41-4.26c3.33-0.22,5.09,1.76,4.6,4.33c-0.99,5.22-2.01,11.55-3.81,19.41c-0.3,1.31-0.74,2.55-1.15,3.72", type: "㇕a", start: [33.75, 73.75], end: [77.8, 96.95], dir: 28, endDir: 109, len: 75.8, num: [35.5, 70.5], part: 3 },
    { n: 9, d: "M35.5,83.75C46.79,83.03,65.75,81.5,80.25,81", type: "㇐a", start: [35.5, 83.75], end: [80.25, 81], dir: -4, endDir: -2, len: 44.8, num: [38.5, 81.5], part: 3 },
    { n: 10, d: "M37.25,95.25c10.7-0.68,26.5-1.38,40.5-2", type: "㇐a", start: [37.25, 95.25], end: [77.75, 93.25], dir: -3, endDir: -3, len: 40.5, num: [38.5, 92.5], part: 3 },
  ],
  parts: [
    { element: "聿", position: "top", radical: "nelson" },
    { element: "⺕", parent: 0 },
    { element: "丨", parent: 0 },
    { element: "日", position: "bottom", radical: "tradit" },
  ],
};

export default data;
