/*
 * KanjiVG stroke data for 月 (U+6708) — release 20260714, source file kanji/06708.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "月",
  code: "06708",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M34.25,16.25c1,1,1.48,2.38,1.5,4c0.38,33.62,2.38,59.38-11,73.25", type: "㇓", start: [34.25, 16.25], end: [24.75, 93.5], dir: 97, endDir: 134, len: 80.1, num: [27.5, 23.43] },
    { n: 2, d: "M36.25,19c4.12-0.62,31.49-4.78,33.25-5c4-0.5,5.5,1.12,5.5,4.75c0,2.76-0.5,49.25-0.5,69.5c0,13-6.25,4-8.75,1.75", type: "㇆a", start: [36.25, 19], end: [65.75, 90], dir: 67, endDir: -138, len: 128, num: [37.5, 15.5] },
    { n: 3, d: "M37.25,38c10.25-1.5,27.25-3.75,36.25-4.5", type: "㇐a", start: [37.25, 38], end: [73.5, 33.5], dir: -7, endDir: -5, len: 36.5, num: [40, 33.5] },
    { n: 4, d: "M37,58.25c8.75-1.12,27-3.5,36.25-4", type: "㇐a", start: [37, 58.25], end: [73.25, 54.25], dir: -6, endDir: -3, len: 36.5, num: [40, 54.5] },
  ],
  parts: [

  ],
};

export default data;
