/*
 * KanjiVG stroke data for 木 (U+6728) — release 20260714, source file kanji/06728.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "木",
  code: "06728",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M19.5,39.86c2.45,0.57,5.23,0.8,8.04,0.57C40.75,39.38,63,36.5,79.78,36.15c2.8-0.06,4.54,0.1,7.34,0.5", type: "㇐", start: [19.5, 39.86], end: [87.12, 36.65], dir: -3, endDir: 8, len: 67.9, num: [12.5, 41.5] },
    { n: 2, d: "M51.75,10.5c1.19,1.19,2,3,2,5c0,8.65,0,55.15-0.14,74.75c-0.03,4.19-0.07,7.15-0.11,8.25", type: "㇑", start: [51.75, 10.5], end: [53.5, 98.5], dir: 89, endDir: 92, len: 88.5, num: [42.5, 11.5] },
    { n: 3, d: "M50.75,39.5c0,1.12-0.61,2.44-1.42,3.95C41.75,57.5,26.7,73.93,15.75,80.25", type: "㇒", start: [50.75, 39.5], end: [15.75, 80.25], dir: 131, endDir: 150, len: 54.5, num: [37.5, 50.5] },
    { n: 4, d: "M54.5,39c4.62,6,23,25.75,31.76,34.61c2.27,2.29,4.61,4.39,7.49,5.64", type: "㇏", start: [54.5, 39], end: [93.75, 79.25], dir: 46, endDir: 23, len: 56.4, num: [66.5, 49.5] },
  ],
  parts: [

  ],
};

export default data;
