/*
 * KanjiVG stroke data for 本 (U+672C) — release 20260714, source file kanji/0672c.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "本",
  code: "0672c",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M20.5,33.5c1.93,0.62,4.91,1.07,8.1,0.75C42.43,32.88,66,30.75,79.64,30c3.2-0.18,7.22,0.25,9.23,0.5", type: "㇐", start: [20.5, 33.5], end: [88.87, 30.5], dir: -3, endDir: 7, len: 68.7, num: [13.5, 34.5], part: 0 },
    { n: 2, d: "M52.1,11.12c1.25,1.25,2.05,3.23,2.05,4.99c0,0.84,0,57.16-0.02,76.76c-0.01,3.96-0.01,6.42-0.02,6.62", type: "㇑", start: [52.1, 11.12], end: [54.11, 99.49], dir: 89, endDir: 93, len: 88.9, num: [42.5, 11.5], part: 1 },
    { n: 3, d: "M51.75,33.5c0,1-0.41,2.22-1.29,3.88C43.62,50.25,30.12,65.5,13.25,75.5", type: "㇒", start: [51.75, 33.5], end: [13.25, 75.5], dir: 133, endDir: 149, len: 58, num: [38.5, 44.5], part: 0 },
    { n: 4, d: "M54.75,35.5c4.92,5.74,23.48,23.33,32.85,31.27c2.58,2.18,5.16,4.41,8.52,5.23", type: "㇏", start: [54.75, 35.5], end: [96.12, 72], dir: 41, endDir: 14, len: 55.5, num: [66.5, 43.5], part: 0 },
    { n: 5, d: "M33.88,73.92c1.5,0.46,2.74,0.75,5.3,0.59c9.95-0.63,21.2-2.13,27.96-2.95c1.93-0.23,3.62-0.31,6-0.02", type: "㇐", start: [33.88, 73.92], end: [73.14, 71.54], dir: -3, endDir: 7, len: 39.5, num: [26.5, 77.5] },
  ],
  parts: [
    { element: "木", radical: "tradit" },
    { element: "丨", radical: "nelson", parent: 0 },
  ],
};

export default data;
