/*
 * KanjiVG stroke data for 来 (U+6765) — release 20260714, source file kanji/06765.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "来",
  code: "06765",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M25.54,28.33c1.61,0.39,4.58,0.53,6.19,0.39c16.32-1.46,27.01-3.46,43.69-3.67c2.69-0.03,4.31,0.18,5.65,0.38", type: "㇐", start: [25.54, 28.33], end: [81.07, 25.43], dir: -3, endDir: 8, len: 55.8, num: [18.5, 28.5] },
    { n: 2, d: "M30.12,37.62c2.85,2.07,7.16,7.91,7.88,11.12", type: "㇔", start: [30.12, 37.62], end: [38, 48.74], dir: 55, endDir: 77, len: 13.8, num: [23.5, 40.63], part: 0 },
    { n: 3, d: "M74.52,33c0.08,0.98-0.11,1.9-0.58,2.77c-1.33,3.04-4.7,7.77-9.06,10.86", type: "㇒", start: [74.52, 33], end: [64.88, 46.63], dir: 125, endDir: 145, len: 17.2, num: [65.5, 35.5], part: 0 },
    { n: 4, d: "M16.62,57c2.28,0.5,4.9,0.74,8.42,0.5c14.81-1,39.08-3.5,58.03-4.25c3.54-0.14,6.33,0.25,8.55,0.5", type: "㇐", start: [16.62, 57], end: [91.62, 53.75], dir: -2, endDir: 6, len: 75.2, num: [9.5, 58.5], part: 1 },
    { n: 5, d: "M51.67,10.75c1.33,1,2.18,2.75,2.18,4.5c0,0.9,0.06,58.96-0.17,78c-0.03,2.77-0.07,4.71-0.1,5.5", type: "㇑", start: [51.67, 10.75], end: [53.58, 98.75], dir: 89, endDir: 92, len: 88.7, num: [42.5, 13.63], part: 1 },
    { n: 6, d: "M49.75,56.5c0,1.5-0.44,2.48-0.82,3.11C42.37,70.49,29,83.75,15.75,90.5", type: "㇒", start: [49.75, 56.5], end: [15.75, 90.5], dir: 135, endDir: 153, len: 49.1, num: [35.5, 67.5], part: 2 },
    { n: 7, d: "M55,56.25c4.38,3.88,19.75,19,29.73,26.28c2.82,2.06,6.52,4.5,10.02,5.22", type: "㇏", start: [55, 56.25], end: [94.75, 87.75], dir: 38, endDir: 12, len: 51.1, num: [70.5, 66.5], part: 1 },
  ],
  parts: [
    { element: "米" },
    { element: "木", radical: "tradit", parent: 0 },
    { element: "丿", radical: "nelson", parent: 1 },
  ],
};

export default data;
