/*
 * KanjiVG stroke data for 東 (U+6771) — release 20260714, source file kanji/06771.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "東",
  code: "06771",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M30.63,25.23c2.36,0.62,4.86,0.47,7.25,0.22c8.24-0.86,22.7-2.7,32.4-3.57c2.38-0.21,4.51-0.14,6.85,0.22", type: "㇐", start: [30.63, 25.23], end: [77.13, 22.1], dir: -4, endDir: 9, len: 46.8, num: [23.25, 21.7], part: 0 },
    { n: 2, d: "M26.77,37.86c1.03,1.03,1.78,2.05,2.07,3.44c0.86,4.14,3.61,16.02,4.97,21.91c0.43,1.87,0.72,3.14,0.76,3.36", type: "㇑", start: [26.77, 37.86], end: [34.57, 66.57], dir: 75, endDir: 80, len: 30, num: [17.25, 45.7], part: 1 },
    { n: 3, d: "M29.55,39.31c14.7-2.12,34.45-4.37,48.18-5.5c2.89-0.24,4.02,2.01,3.49,4.2c-1.33,5.48-2.84,12.21-5.27,19.87c-0.52,1.65-1.08,3.3-1.7,4.94", type: "㇕a", start: [29.55, 39.31], end: [74.25, 62.82], dir: 28, endDir: 111, len: 80.8, num: [30.75, 36.7], part: 1 },
    { n: 4, d: "M32.25,51.07c8.12-0.88,37.75-4.12,45.57-4.4", type: "㇐a", start: [32.25, 51.07], end: [77.82, 46.67], dir: -6, endDir: -2, len: 45.8, num: [35.25, 48.7], part: 1 },
    { n: 5, d: "M35.76,63.99c8.99-1.05,28.37-2.68,38.3-3.23", type: "㇐a", start: [35.76, 63.99], end: [74.06, 60.76], dir: -5, endDir: -3, len: 38.4, num: [38.25, 60.7], part: 1 },
    { n: 6, d: "M51.25,12.32c1.5,1.5,2.25,3.5,2.25,5.25c0,4.5,0.06,55.21-0.14,75.75c-0.04,3.7-0.07,5.29-0.11,6.25", type: "㇑", start: [51.25, 12.32], end: [53.25, 99.57], dir: 89, endDir: 92, len: 87.9, num: [45.75, 6.7], part: 2 },
    { n: 7, d: "M51.62,63.94c-0.24,1.91-0.81,2.76-1.27,3.45c-6.59,9.83-20.19,21.12-31.6,26.42", type: "㇒", start: [51.62, 63.94], end: [18.75, 93.81], dir: 138, endDir: 155, len: 45.3, num: [33.75, 78.7], part: 3 },
    { n: 8, d: "M55,64.44c7.5,7.2,21.77,17.49,29.78,22.16c2.81,1.64,6.1,3.51,9.34,4.09", type: "㇏", start: [55, 64.44], end: [94.12, 90.69], dir: 34, endDir: 10, len: 47.4, num: [71.25, 74.2], part: 2 },
  ],
  parts: [
    { element: "木", radical: "tradit", part: "1" },
    { element: "日" },
    { element: "木", radical: "tradit", part: "2" },
    { element: "丿", radical: "nelson", parent: 2 },
  ],
};

export default data;
