/*
 * KanjiVG stroke data for 校 (U+6821) — release 20260714, source file kanji/06821.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "校",
  code: "06821",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M11.53,40.68c1.1,0.32,2.6,0.45,4.53,0.32c5.4-0.35,16.57-3,23.14-4.04c1.25-0.2,2.3-0.18,3.07,0", type: "㇐", start: [11.53, 40.68], end: [42.27, 36.96], dir: -7, endDir: 13, len: 31.2, num: [5.5, 41.5], part: 0 },
    { n: 2, d: "M28.99,17.25c1.07,1.07,1.76,3.25,1.76,5.25c0,0.77-0.03,48.09-0.18,65.25c-0.03,3.03-0.05,5.16-0.07,6", type: "㇑", start: [28.99, 17.25], end: [30.5, 93.75], dir: 89, endDir: 91, len: 76.9, num: [18.75, 16.5], part: 0 },
    { n: 3, d: "M30.25,40.75c0,1.25-0.49,2.66-0.96,3.77C25.28,53.91,20.88,62.25,15,70", type: "㇒", start: [30.25, 40.75], end: [15, 70], dir: 118, endDir: 127, len: 33.2, num: [19.5, 52.5], part: 0 },
    { n: 4, d: "M33.75,51.25c2.75,1.5,6,5.25,7.25,7.75", type: "㇔/㇏", start: [33.75, 51.25], end: [41, 59], dir: 47, endDir: 63, len: 10.7, num: [35.5, 49.5], part: 0 },
    { n: 5, d: "M66.39,15.5c0.99,0.99,1.38,1.88,1.38,3.62c0,4.25-0.02,7.62-0.08,10.41", type: "㇑a", start: [66.39, 15.5], end: [67.69, 29.53], dir: 85, endDir: 91, len: 14.4, num: [58.5, 12.5], part: 2 },
    { n: 6, d: "M48.12,31.71c2.3,0.29,3.9,0.44,6.09,0.2c10.28-1.16,20.32-2.66,32.45-3.53c2.35-0.17,4.03-0.01,5.33,0.32", type: "㇐", start: [48.12, 31.71], end: [91.99, 28.7], dir: -4, endDir: 14, len: 44.1, num: [47.25, 28.5], part: 2 },
    { n: 7, d: "M59.24,38.93c0.2,0.53,0.06,2.27-0.4,3.14C57,45.5,53.75,49.5,50,52.5", type: "㇒", start: [59.24, 38.93], end: [50, 52.5], dir: 124, endDir: 141, len: 17, num: [50.5, 41.5], part: 3 },
    { n: 8, d: "M79.27,38.5c4.34,3.07,8.73,8.68,10.9,12.41", type: "㇔", start: [79.27, 38.5], end: [90.17, 50.91], dir: 49, endDir: 60, len: 16.6, num: [70.5, 40.5], part: 3 },
    { n: 9, d: "M79.15,49.18c0.35,1.32,0.17,2.62-0.54,4.18C72.25,67.25,58.75,83.25,44,91.25", type: "㇒", start: [79.15, 49.18], end: [44, 91.25], dir: 130, endDir: 152, len: 56.4, num: [71.5, 50.5], part: 3 },
    { n: 10, d: "M55.95,55.88c6.3,3.37,21.64,22.12,31.45,30.33c2.64,2.21,5.07,4.15,8.6,4.44", type: "㇏", start: [55.95, 55.88], end: [96, 90.65], dir: 41, endDir: 5, len: 53.6, num: [61.5, 58.5], part: 3 },
  ],
  parts: [
    { element: "木", position: "left", radical: "general" },
    { element: "交", position: "right" },
    { element: "亠", parent: 1 },
    { element: "父", parent: 1 },
  ],
};

export default data;
