/*
 * KanjiVG stroke data for 歩 (U+6B69) — release 20260714, source file kanji/06b69.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "歩",
  code: "06b69",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M54.39,10.75c1.37,1.12,2.13,2.5,2.13,4.14c0,4.86,0.22,13.86,0.22,22.97", type: "㇑a", start: [54.39, 10.75], end: [56.74, 37.86], dir: 85, endDir: 90, len: 27.8, num: [45.5, 11.5], part: 1 },
    { n: 2, d: "M57.65,24.41c8.23-1.41,12.73-2.16,19.44-3.17c1.66-0.25,3.1-0.24,4.15-0.04", type: "㇐b/㇔", start: [57.65, 24.41], end: [81.24, 21.2], dir: -8, endDir: 11, len: 23.9, num: [61.5, 20.5], part: 1 },
    { n: 3, d: "M32.24,21.98c0.76,0.77,1.81,1.92,1.91,2.81c0.35,3.2,0.6,9.08,0.77,15.17", type: "㇑a", start: [32.24, 21.98], end: [34.92, 39.96], dir: 82, endDir: 88, len: 18.6, num: [22.5, 22.5], part: 0 },
    { n: 4, d: "M18,41.5c2.84,0.69,5.62,0.68,8.51,0.4c14.37-1.4,40.92-4.27,56.01-5.59c3.09-0.27,6.08-0.29,9.16,0.19", type: "㇐", start: [18, 41.5], end: [91.68, 36.5], dir: -4, endDir: 9, len: 74, num: [11.5, 42.13], part: 0 },
    { n: 5, d: "M56.13,42c0.75,0.75,1.22,1.99,1.22,3.5c0,8.5,0,18.47,0,20.94c0,7.06-3.73,3.18-7.1-0.19", type: "㇚", start: [56.13, 42], end: [50.25, 66.25], dir: 104, endDir: -135, len: 36.4, num: [49.5, 49.5], part: 3 },
    { n: 6, d: "M38.75,50.75c0.12,1.1-0.06,1.76-0.62,2.73C35.6,57.9,29.25,63.5,22,68.75", type: "㇒", start: [38.75, 50.75], end: [22, 68.75], dir: 133, endDir: 144, len: 25.2, num: [29.5, 51.5], part: 3 },
    { n: 7, d: "M77,45.5c5.88,2.29,11.62,6.88,14.5,11.51", type: "㇔", start: [77, 45.5], end: [91.5, 57.01], dir: 38, endDir: 58, len: 18.8, num: [69.5, 46.5], part: 3 },
    { n: 8, d: "M76.65,55.64c0.14,0.97-0.09,2.53-0.78,3.91C70.15,70.94,48.14,89.35,25.81,97", type: "㇒", start: [76.65, 55.64], end: [25.81, 97], dir: 141, endDir: 161, len: 67.7, num: [68.5, 56.5], part: 4 },
  ],
  parts: [
    { element: "止", position: "top", radical: "general" },
    { element: "卜", parent: 0 },
    { element: "少", position: "bottom" },
    { element: "小", parent: 2 },
    { element: "丿", parent: 2 },
  ],
};

export default data;
