/*
 * KanjiVG stroke data for 母 (U+6BCD) — release 20260714, source file kanji/06bcd.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "母",
  code: "06bcd",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M34.82,19.37c1.14,1.02,1.72,3.42,1.41,6.09c-1.46,12.62-8.22,32.3-13.04,44.1c-1.47,3.6-0.44,5.27,3.63,5.2c11.37-0.18,27.52,2.13,40.68,7.24c4.98,1.93,9.54,4.26,13.25,7.01", type: "㇗", start: [34.82, 19.37], end: [80.75, 89.01], dir: 57, endDir: 37, len: 117.5, num: [27.5, 26.5], part: 0 },
    { n: 2, d: "M37.32,22.07c4.81,0.56,13.81-1.32,39.18-6.07c4-0.75,5.92,0.77,5.5,4.25c-2.25,18.62-7,49-16.06,69.18c-3.36,7.49-9.86,1.68-11.42,0", type: "㇆a", start: [37.32, 22.07], end: [54.52, 89.43], dir: 76, endDir: -133, len: 133.8, num: [39.5, 18.5], part: 0 },
    { n: 3, d: "M49,28.5c3.88,1.98,10.03,8.16,11,11.25", type: "㇔", start: [49, 28.5], end: [60, 39.75], dir: 46, endDir: 73, len: 16, num: [41.5, 32.5] },
    { n: 4, d: "M45.25,57.62c3.79,1.96,9.8,8.07,10.75,11.12", type: "㇔", start: [45.25, 57.62], end: [56, 68.74], dir: 46, endDir: 73, len: 15.7, num: [37.5, 60.5] },
    { n: 5, d: "M9.88,51.45c2.21,0.63,6.26,0.87,8.46,0.63C46.77,49,67.12,47,90.65,46.07c3.68-0.15,5.89,0.3,7.72,0.61", type: "㇐", start: [9.88, 51.45], end: [98.37, 46.68], dir: -3, endDir: 10, len: 88.9, num: [2.5, 54.13], part: 1 },
  ],
  parts: [
    { element: "毋", radical: "general", part: "1" },
    { element: "毋", radical: "general", part: "2" },
  ],
};

export default data;
