/*
 * KanjiVG stroke data for 気 (U+6C17) — release 20260714, source file kanji/06c17.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "気",
  code: "06c17",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M37.75,9.25c0.25,1.62-0.25,2.75-1,4.25C35.63,15.74,28,25.25,24,29", type: "㇒", start: [37.75, 9.25], end: [24, 29], dir: 125, endDir: 137, len: 24.6, num: [29.5, 10.5], part: 1 },
    { n: 2, d: "M36.5,21.25c1.33-0.03,3.29-0.05,4.8-0.32c9.2-1.68,18.17-3.46,26.98-5.27c1.63-0.33,3.71-0.64,5.21-0.91", type: "㇐", start: [36.5, 21.25], end: [73.49, 14.75], dir: -10, endDir: -10, len: 37.6, num: [43.5, 17.5], part: 1 },
    { n: 3, d: "M31.25,32.75c1.5,0.38,3.3,0.26,4.96,0.08c7.67-0.83,19.54-2.58,29.14-4.39c1.94-0.37,3.64-0.41,4.91-0.45", type: "㇐", start: [31.25, 32.75], end: [70.26, 27.99], dir: -7, endDir: -2, len: 39.4, num: [35.25, 30.13], part: 0 },
    { n: 4, d: "M18.5,47c1.88,0.75,4,0.88,6.25,0.5c15.08-2.51,35-5.62,48.25-8c4.73-0.85,5.6,0.47,4.5,6.25c-4,21,0.71,40.32,11.5,50c7.25,6.5,6.5,0.75,6-5.25", type: "㇈a", start: [18.5, 47], end: [95, 90.5], dir: 30, endDir: -95, len: 133.7, num: [10.5, 48.13], part: 0 },
    { n: 5, d: "M57,51.75c0.12,1.62-0.17,3.03-1,4.75C49.5,70,40.25,82.75,25.75,93.25", type: "㇒", start: [57, 51.75], end: [25.75, 93.25], dir: 127, endDir: 144, len: 53, num: [48.5, 53.5], part: 3 },
    { n: 6, d: "M30,63.75C41.5,68,54.5,78,62.25,90.5", type: "㇔/㇒", start: [30, 63.75], end: [62.25, 90.5], dir: 40, endDir: 58, len: 42.6, num: [20.5, 63.13], part: 2 },
  ],
  parts: [
    { element: "气", position: "kamae", radical: "general" },
    { element: "𠂉", parent: 0 },
    { element: "乂" },
    { element: "丿", parent: 2 },
  ],
};

export default data;
