/*
 * KanjiVG stroke data for 水 (U+6C34) — release 20260714, source file kanji/06c34.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "水",
  code: "06c34",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M52.77,15.08c1.08,1.08,1.67,2.49,1.76,5.52c0.4,14.55-0.26,62.16-0.26,67.12c0,9.78-7.52,0.03-9.02-1.22", type: "㇚", start: [52.77, 15.08], end: [45.25, 86.5], dir: 96, endDir: -140, len: 87.4, num: [43.75, 15.38] },
    { n: 2, d: "M17.5,45.75c1.75,0.62,3.73,0.43,5.25,0C25.88,44.88,36.09,41,38.59,40s4.47,1.24,3.75,3.5C39,54,28.25,69,19,74.75", type: "㇇", start: [17.5, 45.75], end: [19, 74.75], dir: 87, endDir: 148, len: 68.3, num: [10.25, 47.28] },
    { n: 3, d: "M81.22,27.5c-0.22,1.25-0.72,2.25-1.52,2.97c-5.64,5.1-12.45,9.78-22.45,13.78", type: "㇒", start: [81.22, 27.5], end: [57.25, 44.25], dir: 145, endDir: 158, len: 29.9, num: [83.75, 24.28] },
    { n: 4, d: "M57,46c8.82,10.73,19.23,21.46,28.42,27.42c2.16,1.4,4.52,3,7.08,3.58", type: "㇏", start: [57, 46], end: [92.5, 77], dir: 41, endDir: 13, len: 47.6, num: [64, 51.03] },
  ],
  parts: [

  ],
};

export default data;
