/*
 * KanjiVG stroke data for 火 (U+706B) — release 20260714, source file kanji/0706b.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "火",
  code: "0706b",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M24.25,34c3.27,3.33,8.5,13,9.5,17.75", type: "㇔", start: [24.25, 34], end: [33.75, 51.75], dir: 62, endDir: 78, len: 20.3, num: [16.5, 32.5] },
    { n: 2, d: "M83,27.25c0.5,1.38,0.22,2.74-0.5,4.25c-2.38,5-7.5,12.12-12.75,17.25", type: "㇒", start: [83, 27.25], end: [69.75, 48.75], dir: 122, endDir: 136, len: 25.9, num: [74.5, 26.5] },
    { n: 3, d: "M52.5,14.25c1,1.25,1.5,3.12,1.5,5C54,69,39.62,80,21,91.5", type: "㇒", start: [52.5, 14.25], end: [21, 91.5], dir: 112, endDir: 148, len: 89.6, num: [41.5, 14.5] },
    { n: 4, d: "M52.75,50c12.49,14.06,25.01,28.42,33.62,36.13c2.7,2.42,4.9,4.02,8.38,4.87", type: "㇏", start: [52.75, 50], end: [94.75, 91], dir: 44, endDir: 14, len: 59.2, num: [55.25, 67.13] },
  ],
  parts: [

  ],
};

export default data;
