/*
 * KanjiVG stroke data for 父 (U+7236) — release 20260714, source file kanji/07236.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "父",
  code: "07236",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M38.49,18.25c0.39,1.38,0.07,2.89-0.59,4.16C32,33.91,26.32,39.13,18.75,45.62", type: "㇒", start: [38.49, 18.25], end: [18.75, 45.62], dir: 126, endDir: 139, len: 34.6, num: [30.5, 18.5], part: 0 },
    { n: 2, d: "M69.38,19.5c7.25,4,14.29,9.68,18.88,15.5", type: "㇔", start: [69.38, 19.5], end: [88.26, 35], dir: 39, endDir: 52, len: 24.6, num: [61.25, 19.5], part: 0 },
    { n: 3, d: "M67.7,39.68c0.55,1.57,0.31,3.8-0.42,5.92C60.63,64.87,48,80.25,23,90.25", type: "㇒", start: [67.7, 39.68], end: [23, 90.25], dir: 131, endDir: 158, len: 71.1, num: [57.5, 41.5], part: 1 },
    { n: 4, d: "M34.25,47c4.83,0,29,25.38,45.99,37.02c3.54,2.43,7.39,4.55,11.51,5.77", type: "㇏", start: [34.25, 47], end: [91.75, 89.79], dir: 37, endDir: 16, len: 72.2, num: [34.5, 44.63], part: 1 },
  ],
  parts: [
    { position: "top" },
    { position: "bottom" },
  ],
};

export default data;
