/*
 * KanjiVG stroke data for 犬 (U+72AC) — release 20260714, source file kanji/072ac.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "犬",
  code: "072ac",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M18.38,46.36c2.37,0.64,5.38,0.73,7.74,0.47c14.39-1.58,36.51-4.46,51.25-5.75c2.51-0.22,6-0.33,7.89,0.42", type: "㇐", start: [18.38, 46.36], end: [85.26, 41.5], dir: -4, endDir: 22, len: 67.3, num: [11.5, 47.5], part: 0 },
    { n: 2, d: "M50.25,15.75c1,1.08,1.61,2.16,1.74,4.32C53.75,48.25,46.5,79.75,17,92.25", type: "㇒", start: [50.25, 15.75], end: [17, 92.25], dir: 113, endDir: 157, len: 90.7, num: [39.75, 15.5], part: 0 },
    { n: 3, d: "M51.5,45c8.29,11.97,23.78,31.58,35.16,41.85c2.37,2.14,4.59,4.15,8.09,5.4", type: "㇏", start: [51.5, 45], end: [94.75, 92.25], dir: 48, endDir: 20, len: 64.6, num: [62.5, 55.63], part: 0 },
    { n: 4, d: "M67.33,20.25c6.9,3.89,8.78,6.85,10.92,10.5", type: "㇔", start: [67.33, 20.25], end: [78.25, 30.75], dir: 44, endDir: 60, len: 15.4, num: [60.5, 19.5], part: 1 },
  ],
  parts: [
    { element: "大" },
    { element: "丶" },
  ],
};

export default data;
