/*
 * KanjiVG stroke data for 猫 (U+732B) — release 20260714, source file kanji/0732b.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "猫",
  code: "0732b",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M36.05,19.5c0.07,0.61-0.17,1.57-0.63,2.21C30,29.25,23.75,36.25,11.25,45.29", type: "㇒", start: [36.05, 19.5], end: [11.25, 45.29], dir: 134, endDir: 144, len: 36.3, num: [29.25, 19.5], part: 0 },
    { n: 2, d: "M19,19.25c28.25,23.5,17.71,84.53,6,71.5", type: "㇁", start: [19, 19.25], end: [25, 90.75], dir: 85, endDir: -132, len: 85, num: [11.5, 19.63], part: 0 },
    { n: 3, d: "M31.33,46.75c0.05,0.63-0.01,1.58-0.36,2.26c-4.44,8.62-8.69,14.71-19.47,24.03", type: "㇒", start: [31.33, 46.75], end: [11.5, 73.04], dir: 127, endDir: 139, len: 33.5, num: [23.5, 47.5], part: 0 },
    { n: 4, d: "M42.25,32.18c2.75,0.45,4.5,0.33,6.63,0.07c12.24-1.5,29.24-3.12,40.87-3.86c2.16-0.14,4.37-0.17,6.49,0.26", type: "㇐", start: [42.25, 32.18], end: [96.24, 28.65], dir: -4, endDir: 11, len: 54.2, num: [40.5, 29.5], part: 2 },
    { n: 5, d: "M55.26,17.76c0.99,0.99,1.55,2.3,1.67,3.39C58.1,31.32,59.11,41.3,59.44,45", type: "㇑a", start: [55.26, 17.76], end: [59.44, 45], dir: 81, endDir: 85, len: 27.8, num: [46.5, 16.5], part: 2 },
    { n: 6, d: "M79.98,16.5c0.65,1,0.77,1.88,0.58,3.07c-1.66,10.51-2.17,14.72-4.17,24.58", type: "㇑a", start: [79.98, 16.5], end: [76.39, 44.15], dir: 97, endDir: 101, len: 28.1, num: [71.25, 15.13], part: 2 },
    { n: 7, d: "M47.32,52.24c0.97,0.97,1.36,2.43,1.5,3.5c1.06,8.64,2.3,20.37,3.03,31.5c0.13,1.92,0.24,3.8,0.35,5.59", type: "㇑", start: [47.32, 52.24], end: [52.2, 92.83], dir: 83, endDir: 86, len: 41.1, num: [41.5, 61.5], part: 3 },
    { n: 8, d: "M49.78,54.28c12.83-1.32,25.34-2.9,36.47-3.46c3.89-0.19,6.42,0.53,6.01,4.81c-0.62,6.5-2.2,19.8-3.89,30.68c-0.35,2.25-0.7,4.4-1.05,6.36", type: "㇕a", start: [49.78, 54.28], end: [87.32, 92.67], dir: 46, endDir: 100, len: 83.3, num: [51.5, 51.5], part: 3 },
    { n: 9, d: "M67.8,53.84c0.87,0.87,1.08,2.01,1.08,3.16c0,8-0.01,25.49-0.01,31.62", type: "㇑a", start: [67.8, 53.84], end: [68.87, 88.62], dir: 88, endDir: 90, len: 35.1, num: [61.5, 61.63], part: 3 },
    { n: 10, d: "M51.47,70.33c5.4-0.58,35.24-2.33,38.19-2.39", type: "㇐a", start: [51.47, 70.33], end: [89.66, 67.94], dir: -4, endDir: -1, len: 38.3, num: [53.5, 67.63], part: 3 },
    { n: 11, d: "M53.28,90.49c9.97-0.62,22.66-1,33.57-1.4", type: "㇐a", start: [53.28, 90.49], end: [86.85, 89.09], dir: -2, endDir: -2, len: 33.6, num: [54.5, 87.05], part: 3 },
  ],
  parts: [
    { element: "⺨", position: "left", radical: "general" },
    { element: "苗", position: "right" },
    { element: "艹", position: "top", parent: 1 },
    { element: "田", position: "bottom", parent: 1 },
  ],
};

export default data;
