/*
 * KanjiVG stroke data for 生 (U+751F) — release 20260714, source file kanji/0751f.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "生",
  code: "0751f",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M31.26,25.89c0.36,1.36,0.35,2.65-0.05,3.79c-2.34,6.69-7.24,17.22-14.96,24.19", type: "㇒", start: [31.26, 25.89], end: [16.25, 53.87], dir: 118, endDir: 138, len: 32.6, num: [22.75, 25.63] },
    { n: 2, d: "M31.13,40.67c2.37,0.33,4.03,0.07,5.64-0.12c9.5-1.1,25.15-4.12,35.35-5.83c2.51-0.42,4.86-0.73,7.38-0.33", type: "㇐", start: [31.13, 40.67], end: [79.5, 34.39], dir: -7, endDir: 9, len: 48.9, num: [36, 37.28] },
    { n: 3, d: "M52.31,12.63c1.28,1.28,2.01,3.12,2.01,5.23c0,4.01,0,65.14,0,69.77", type: "㇑a", start: [52.31, 12.63], end: [54.32, 87.63], dir: 88, endDir: 90, len: 75.5, num: [42.5, 10.5] },
    { n: 4, d: "M29.38,64.03c2.64,0.67,5.38,0.31,8.04-0.02C49.45,62.51,62.16,61,72.5,59.86c2.38-0.26,4.99-0.76,7.38-0.23", type: "㇐", start: [29.38, 64.03], end: [79.88, 59.63], dir: -5, endDir: 13, len: 50.8, num: [21.5, 66.13] },
    { n: 5, d: "M15.75,90.25c3.04,0.75,6.21,0.94,8.4,0.8C40.62,90,68.12,86.5,83.3,85.75c3.63-0.18,7.68,0,10.07,0.73", type: "㇐", start: [15.75, 90.25], end: [93.37, 86.48], dir: -3, endDir: 17, len: 78, num: [8.5, 89.5] },
  ],
  parts: [

  ],
};

export default data;
