/*
 * KanjiVG stroke data for 男 (U+7537) — release 20260714, source file kanji/07537.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "男",
  code: "07537",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M26.5,14.25c0.88,0.88,1.56,1.99,1.73,2.98c0.84,4.77,2.47,16.75,3.34,26.04c0.18,1.95,0.37,2.37,0.55,4.23", type: "㇑", start: [26.5, 14.25], end: [32.12, 47.5], dir: 80, endDir: 84, len: 34, num: [18.75, 19.5], part: 0 },
    { n: 2, d: "M29,15.95c11.38-1.45,41.21-4.57,49.56-4.71c3.9-0.07,5.44,1.51,4.91,5.29c-0.45,3.21-3.15,15.19-4.94,22.23c-0.41,1.62-0.79,2.99-1.4,4.19", type: "㇕a", start: [29, 15.95], end: [77.13, 42.95], dir: 29, endDir: 117, len: 85.7, num: [31.5, 12.5], part: 0 },
    { n: 3, d: "M54,15.97c0.77,0.77,1,1.91,1,2.79c0.02,6.32,0.2,22,0.2,22.75", type: "㇑a", start: [54, 15.97], end: [55.2, 41.51], dir: 87, endDir: 90, len: 25.8, num: [47.5, 24.13], part: 0 },
    { n: 4, d: "M30.98,30.82C45,29.12,57.12,28,80.53,26.34", type: "㇐a", start: [30.98, 30.82], end: [80.53, 26.34], dir: -5, endDir: -4, len: 49.8, num: [34, 27.5], part: 0 },
    { n: 5, d: "M32.87,44.74c11.38-1.24,28.38-2.99,44.14-3.7", type: "㇐a", start: [32.87, 44.74], end: [77.01, 41.04], dir: -5, endDir: -3, len: 44.3, num: [34.5, 41.5], part: 0 },
    { n: 6, d: "M19.98,60.98c2.15,0.67,4.58,0.78,6.77,0.53c13.46-1.53,42.24-5.66,51.88-6.86c5.26-0.66,6.86,1.04,5.72,6.27c-1.92,8.83-9,27.39-15.66,33.19c-5.11,4.45-7.44,2.14-9.69-0.86", type: "㇆", start: [19.98, 60.98], end: [59, 93.25], dir: 40, endDir: -127, len: 119, num: [11.5, 63.5], part: 1 },
    { n: 7, d: "M53.22,46.43c0.28,1.32,0.29,3.04-0.2,4.57C49.12,63.12,38,81.25,17.14,92.06", type: "㇒", start: [53.22, 46.43], end: [17.14, 92.06], dir: 128, endDir: 153, len: 60.5, num: [45.5, 52.5], part: 1 },
  ],
  parts: [
    { element: "田", position: "top", radical: "general" },
    { element: "力", position: "bottom" },
  ],
};

export default data;
