/*
 * KanjiVG stroke data for 町 (U+753A) — release 20260714, source file kanji/0753a.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "町",
  code: "0753a",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M11.25,30.5c1.12,1.12,1.5,2.12,1.65,3.26C13.69,39.98,13.97,58,14.54,71c0.08,1.89,0.16,2.49,0.23,4.25", type: "㇑", start: [11.25, 30.5], end: [14.77, 75.25], dir: 86, endDir: 88, len: 45.3, num: [5.25, 37.63], part: 0 },
    { n: 2, d: "M13.75,32.29c7.37-0.79,21.04-2.87,25.07-3.05c2-0.09,3.01,1.91,2.9,3.93c-0.35,6.55-1.51,24.68-2.05,36.33c-0.07,1.5-0.18,2.62-0.43,3.75", type: "㇕a", start: [13.75, 32.29], end: [39.24, 73.25], dir: 58, endDir: 102, len: 71, num: [15.75, 29.13], part: 0 },
    { n: 3, d: "M25.31,31.8c0.94,0.95,1.48,2.28,1.47,3.7c-0.02,6.52,0.13,33.79,0.13,34.55", type: "㇑a", start: [25.31, 31.8], end: [26.91, 70.05], dir: 88, endDir: 90, len: 38.6, num: [29.5, 39.5], part: 0 },
    { n: 4, d: "M14.43,51.84c2.37-0.37,23.45-2.56,25.41-2.56", type: "㇐a", start: [14.43, 51.84], end: [39.84, 49.28], dir: -6, endDir: 0, len: 25.5, num: [17.25, 48.13], part: 0 },
    { n: 5, d: "M15.15,71.79c6.98-0.42,15.85-1.42,24.06-1.88", type: "㇐a", start: [15.15, 71.79], end: [39.21, 69.91], dir: -4, endDir: -3, len: 24.1, num: [17.5, 67.63], part: 0 },
    { n: 6, d: "M49,27.6c1.48,0.42,4.18,0.56,5.66,0.42c10.97-1.02,25.72-2.9,37.18-3.63c2.45-0.16,3.91-0.01,5.16,0.41", type: "㇐", start: [49, 27.6], end: [97, 24.8], dir: -3, endDir: 19, len: 48.3, num: [47.25, 24.5], part: 2 },
    { n: 7, d: "M71.77,29.08c1.2,1.2,2,2.75,2,5.81c0,17.98,0,51.3,0,56.3c0,11.06-6.02,2.81-9.21-0.25", type: "㇚", start: [71.77, 29.08], end: [64.56, 90.94], dir: 97, endDir: -136, len: 78.5, num: [65.5, 38.5], part: 3 },
  ],
  parts: [
    { element: "田", position: "left", radical: "general" },
    { element: "丁", position: "right" },
    { element: "一", parent: 1 },
    { element: "亅", parent: 1 },
  ],
};

export default data;
