/*
 * KanjiVG stroke data for 田 (U+7530) — release 20260714, source file kanji/07530.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "田",
  code: "07530",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M18.25,27.48c1.2,1.2,2.11,2.68,2.28,3.95C22,42.25,23.52,62.11,24.81,80c0.17,2.4,0.34,3.75,0.49,6", type: "㇑", start: [18.25, 27.48], end: [25.3, 86], dir: 83, endDir: 86, len: 59.4, num: [11.5, 34.63] },
    { n: 2, d: "M20.85,29.29c8.52-0.54,50.04-3.17,61.58-4.05c4.84-0.37,7.32,2.01,7.04,5.63c-0.69,8.8-2.83,30.69-3.99,46.64c-0.18,2.44-0.34,4.75-0.47,6.86", type: "㇕a", start: [20.85, 29.29], end: [85.01, 84.37], dir: 41, endDir: 94, len: 125.9, num: [23.5, 25.5] },
    { n: 3, d: "M53.25,29c0.88,0.88,1.19,2.12,1.19,3.5c0,9.52,0.31,46.37,0.31,47.25", type: "㇑a", start: [53.25, 29], end: [54.75, 79.75], dir: 88, endDir: 90, len: 51, num: [46.5, 37.5] },
    { n: 4, d: "M24,55.5c5.75-0.5,55.12-3.25,62.5-3.5", type: "㇐a", start: [24, 55.5], end: [86.5, 52], dir: -3, endDir: -2, len: 62.6, num: [27.5, 52.5] },
    { n: 5, d: "M25.98,83.07c14.77-0.82,39.39-2.07,58.18-2.83", type: "㇐a", start: [25.98, 83.07], end: [84.16, 80.24], dir: -3, endDir: -2, len: 58.2, num: [28.5, 79.5] },
  ],
  parts: [

  ],
};

export default data;
