/*
 * KanjiVG stroke data for 白 (U+767D) — release 20260714, source file kanji/0767d.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "白",
  code: "0767d",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M55,13c0.38,1.5,0,3.25-0.57,4.29C51.32,22.93,46,31.12,36.81,40.22", type: "㇒", start: [55, 13], end: [36.81, 40.22], dir: 124, endDir: 135, len: 33.4, num: [46.5, 13.5], part: 0 },
    { n: 2, d: "M25.5,40.47c1.14,1.14,1.63,2.81,1.63,4.63c0,1.55,0.95,32.47,1.32,47.14c0.06,2.58,0.13,4.66,0.18,6", type: "㇑", start: [25.5, 40.47], end: [28.63, 98.24], dir: 87, endDir: 88, len: 58.2, num: [17.5, 48.13], part: 1 },
    { n: 3, d: "M28.27,43.98c13.98-1.73,39.08-4.47,49.67-5.48c5.19-0.5,7.37,0.76,7.06,5.38c-0.62,9.12-2.09,30.3-3.29,46.88c-0.17,2.42-0.33,4.65-0.46,6.57", type: "㇕a", start: [28.27, 43.98], end: [81.25, 97.33], dir: 45, endDir: 94, len: 114.4, num: [29.5, 40.5], part: 1 },
    { n: 4, d: "M29.13,67.44C42.25,66,72.38,63.62,82.57,63.4", type: "㇐a", start: [29.13, 67.44], end: [82.57, 63.4], dir: -4, endDir: -1, len: 53.6, num: [32.5, 63], part: 1 },
    { n: 5, d: "M29.69,94.49C43,93.75,66.62,92,80.19,91.41", type: "㇐a", start: [29.69, 94.49], end: [80.19, 91.41], dir: -3, endDir: -2, len: 50.6, num: [32.5, 91.5], part: 1 },
  ],
  parts: [
    { position: "top" },
    { element: "日", position: "bottom" },
  ],
};

export default data;
