/*
 * KanjiVG stroke data for 百 (U+767E) — release 20260714, source file kanji/0767e.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "百",
  code: "0767e",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M16.13,20.23c2.22,0.54,6.29,0.75,8.51,0.54c21.49-2.02,41.86-4.39,59.22-4.98c3.7-0.12,5.92,0.26,7.77,0.53", type: "㇐", start: [16.13, 20.23], end: [91.63, 16.32], dir: -3, endDir: 8, len: 75.8, num: [8.25, 21.5], part: 0 },
    { n: 2, d: "M52.31,21.75c0.19,1.38,0.19,2.5-0.38,3.93c-1.65,4.19-4.81,9.19-8.66,14.68", type: "㇔", start: [52.31, 21.75], end: [43.27, 40.36], dir: 116, endDir: 125, len: 21.1, num: [42.5, 28.63], part: 2 },
    { n: 3, d: "M30.75,42.82c0.96,0.96,1.64,2.45,1.72,4.19c0.41,8.74,0.96,32.92,1.18,43.74c0.05,2.48,0.08,4.12,0.1,4.5", type: "㇑", start: [30.75, 42.82], end: [33.75, 95.25], dir: 87, endDir: 87, len: 52.9, num: [23.5, 51.5], part: 3 },
    { n: 4, d: "M33.55,44.8c10.35-1.37,35.73-4.38,38.78-4.59c3.15-0.22,4.92,1.17,4.92,4.24c0,4.48-0.68,32-0.92,44.06c-0.06,3.02-0.1,5.05-0.11,5.48", type: "㇕a", start: [33.55, 44.8], end: [76.22, 93.99], dir: 49, endDir: 91, len: 96.2, num: [33.5, 41.5], part: 3 },
    { n: 5, d: "M34.14,66.95c10.24-1.08,32.11-3.2,41.44-3.57", type: "㇐a", start: [34.14, 66.95], end: [75.58, 63.38], dir: -5, endDir: -2, len: 41.6, num: [37.5, 63.1], part: 3 },
    { n: 6, d: "M34.97,92.87c8.78-0.87,30.53-2.12,40.06-2.39", type: "㇐a", start: [34.97, 92.87], end: [75.03, 90.48], dir: -3, endDir: -2, len: 40.1, num: [37.5, 89.5], part: 3 },
  ],
  parts: [
    { element: "一", position: "top", radical: "nelson" },
    { element: "白", position: "bottom", radical: "tradit" },
    { position: "top", parent: 1 },
    { element: "日", position: "bottom", parent: 1 },
  ],
};

export default data;
