/*
 * KanjiVG stroke data for 目 (U+76EE) — release 20260714, source file kanji/076ee.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "目",
  code: "076ee",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M29.75,19.05c1.35,1.35,1.86,3.21,1.86,5.47c0,1.77,0.19,42.37,0.06,60.23c-0.04,4.91-0.06,8.11-0.06,8.36", type: "㇑", start: [29.75, 19.05], end: [31.61, 93.11], dir: 89, endDir: 90, len: 74.5, num: [22.5, 26.5] },
    { n: 2, d: "M32.54,21.39c10.92-1.23,38.33-4.11,41.42-4.38c3.25-0.28,5.54,1.25,5.54,4.18c0,8.95-0.26,39.93-0.26,64.82c0,3,0.01,3.75,0.01,6", type: "㇕a", start: [32.54, 21.39], end: [79.25, 92.01], dir: 57, endDir: 90, len: 120.4, num: [36.5, 17.5] },
    { n: 3, d: "M33.05,43.64c12.45-1.51,34.83-3.51,45.18-4.09", type: "㇐a", start: [33.05, 43.64], end: [78.23, 39.55], dir: -5, endDir: -3, len: 45.4, num: [37.5, 39.5] },
    { n: 4, d: "M32.9,65.95C44.25,65,66,62.88,77.72,62.56", type: "㇐a", start: [32.9, 65.95], end: [77.72, 62.56], dir: -4, endDir: -2, len: 45, num: [37.5, 62] },
    { n: 5, d: "M33,90.5c9.75-0.5,33.25-2.5,44.79-2.53", type: "㇐a", start: [33, 90.5], end: [77.79, 87.97], dir: -3, endDir: 0, len: 44.9, num: [37.5, 86] },
  ],
  parts: [

  ],
};

export default data;
