/*
 * KanjiVG stroke data for 知 (U+77E5) — release 20260714, source file kanji/077e5.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "知",
  code: "077e5",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M30.39,16.21c0.61,1.29,0.5,2.73,0.07,4.09C28.5,26.5,25,35.25,18.01,44.16", type: "㇒", start: [30.39, 16.21], end: [18.01, 44.16], dir: 114, endDir: 128, len: 31.3, num: [22.5, 14.5], part: 0 },
    { n: 2, d: "M28.91,33.73c1.79,0,2.19,0.14,3.08,0c4.13-0.63,8.18-1.52,14.78-2.89c1.91-0.39,3.86-0.47,5.48-0.1", type: "㇐", start: [28.91, 33.73], end: [52.25, 30.74], dir: -7, endDir: 13, len: 23.7, num: [33.5, 29.5], part: 1 },
    { n: 3, d: "M12.22,57.18c2.49,0.51,4.9,0.46,7.41,0.15c7.62-0.95,19.62-2.58,29.51-3.78c1.72-0.21,3.85-0.05,5.35,0.26", type: "㇐", start: [12.22, 57.18], end: [54.49, 53.81], dir: -5, endDir: 12, len: 42.6, num: [4.5, 59.5], part: 2 },
    { n: 4, d: "M37.98,36c0.4,1.32,0.59,2.61,0.58,4.24c-0.18,25.01-8.68,42.88-24.75,51.93", type: "㇒", start: [37.98, 36], end: [13.81, 92.17], dir: 113, endDir: 151, len: 64.7, num: [30.5, 42.5], part: 2 },
    { n: 5, d: "M39.25,65.75c6,4.25,11.62,10.88,14.25,16.75", type: "㇔/㇏", start: [39.25, 65.75], end: [53.5, 82.5], dir: 50, endDir: 66, len: 22.2, num: [44.25, 66.13], part: 2 },
    { n: 6, d: "M59,44.94c0.97,0.97,1.74,1.85,2.09,3.35c1.19,4.97,2.18,15.35,3.25,24.19c0.16,1.32,0.31,2.58,0.45,3.77", type: "㇑", start: [59, 44.94], end: [64.79, 76.25], dir: 80, endDir: 83, len: 32.2, num: [51.5, 48.5], part: 3 },
    { n: 7, d: "M61.73,46.38c8.56-1.22,21.16-2.76,27.52-3.48c2.02-0.23,4.12,0.97,3.69,3.33c-0.86,4.66-3.05,17.02-4.36,23.59", type: "㇕b", start: [61.73, 46.38], end: [88.58, 69.82], dir: 41, endDir: 101, len: 57.6, num: [63.5, 42.5], part: 3 },
    { n: 8, d: "M65,73.56c6.55-0.93,14.12-1.62,22.04-2.45c1.14-0.12,2.29-0.24,3.46-0.37", type: "㇐b", start: [65, 73.56], end: [90.5, 70.74], dir: -6, endDir: -6, len: 25.7, num: [68.5, 69.13], part: 3 },
  ],
  parts: [
    { element: "矢", position: "left", radical: "general" },
    { element: "天", parent: 0 },
    { element: "大", parent: 1 },
    { element: "口", position: "right" },
  ],
};

export default data;
