/*
 * KanjiVG stroke data for 社 (U+793E) — release 20260714, source file kanji/0793e.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "社",
  code: "0793e",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M29.5,15.25c3.41,2.06,6.75,4.75,10,8.75", type: "㇔", start: [29.5, 15.25], end: [39.5, 24], dir: 41, endDir: 51, len: 13.4, num: [21.75, 13.63], part: 0 },
    { n: 2, d: "M15.5,39c2,0.75,3.05,0.8,5.55,0.17c6.2-1.55,15.6-4.05,17.7-4.67c2.5-0.75,4.46,1.23,3,3.5c-4.75,7.38-13.88,18.62-25,28.75", type: "㇇", start: [15.5, 39], end: [16.75, 66.75], dir: 87, endDir: 138, len: 68.5, num: [8.5, 40.5], part: 0 },
    { n: 3, d: "M30.82,55.37C32,56.5,32.21,58,32.21,59.94c0,8.57-0.15,21.05-0.3,29.06c-0.06,3.28-0.12,5.81-0.12,7", type: "㇑", start: [30.82, 55.37], end: [31.79, 96], dir: 89, endDir: 90, len: 41, num: [24.75, 68.5], part: 0 },
    { n: 4, d: "M36.25,54.5c3.67,2.41,7.6,6.03,10.75,10.25", type: "㇔", start: [36.25, 54.5], end: [47, 64.75], dir: 44, endDir: 53, len: 14.9, num: [38.5, 53.5], part: 0 },
    { n: 5, d: "M52.13,52.03c1.49,0.39,4.23,0.31,5.71,0.14c7.92-0.91,19.17-2.04,28.02-2.68c2.48-0.18,3.97-0.07,5.22,0.13", type: "㇐", start: [52.13, 52.03], end: [91.08, 49.62], dir: -4, endDir: 9, len: 39.1, num: [50.5, 48.13], part: 1 },
    { n: 6, d: "M69.31,17.87c1.23,1.23,1.81,3.13,1.81,5.13c0,14.25,0.13,62.57,0.13,63.07", type: "㇑a", start: [69.31, 17.87], end: [71.25, 86.07], dir: 88, endDir: 90, len: 68.6, num: [59.5, 17.5], part: 1 },
    { n: 7, d: "M42.25,88.97c1.92,0.55,5.44,0.76,7.36,0.55c12.39-1.39,28.51-3.64,41.04-4.03c3.2-0.1,6.09,0.14,7.72,0.79", type: "㇐", start: [42.25, 88.97], end: [98.37, 86.28], dir: -3, endDir: 22, len: 56.5, num: [40.5, 85.63], part: 1 },
  ],
  parts: [
    { element: "礻", position: "left", radical: "general" },
    { element: "土", position: "right" },
  ],
};

export default data;
