/*
 * KanjiVG stroke data for 私 (U+79C1) — release 20260714, source file kanji/079c1.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "私",
  code: "079c1",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M45.24,13.5c0.01,1-0.5,2.25-1.43,2.99C39.75,19.75,31.75,23.88,18.75,29", type: "㇒", start: [45.24, 13.5], end: [18.75, 29], dir: 150, endDir: 159, len: 31.5, num: [37.5, 13.63], part: 1 },
    { n: 2, d: "M11.62,44.6c2.63,0.78,5.51,0.5,7.28,0.17c9.98-1.89,22.62-3.29,30.72-4.06c1.29-0.12,3.13-0.21,4.36,0.12", type: "㇐", start: [11.62, 44.6], end: [53.98, 40.83], dir: -5, endDir: 15, len: 42.7, num: [4.5, 45.5], part: 2 },
    { n: 3, d: "M36.08,26.66c0.95,0.95,1.41,2.84,1.41,4.69c0,3.83,0,40.18-0.04,55.4c-0.01,3.25-0.02,5.59-0.03,6.5", type: "㇑", start: [36.08, 26.66], end: [37.42, 93.25], dir: 89, endDir: 91, len: 66.9, num: [28.5, 34.63], part: 2 },
    { n: 4, d: "M35.93,43.47c0,1.03-0.71,2.97-1.36,4.2C29.27,57.83,21.15,69.5,10.5,77.5", type: "㇒", start: [35.93, 43.47], end: [10.5, 77.5], dir: 127, endDir: 143, len: 43.1, num: [23.5, 54.5], part: 2 },
    { n: 5, d: "M41,49.75c4.4,2.51,8.13,7.52,10.5,10.75", type: "㇔/㇏", start: [41, 49.75], end: [51.5, 60.5], dir: 46, endDir: 54, len: 15.1, num: [47.25, 50.5], part: 2 },
    { n: 6, d: "M73.3,31.9c0.32,1.22,0.34,2.31-0.06,3.51C68.25,50.5,59.75,65.25,52.08,78.31c-2.12,3.61-1.6,5.03,1.88,3.89C66,78.25,76.62,74.12,88.28,69.98", type: "㇜", start: [73.3, 31.9], end: [88.28, 69.98], dir: 69, endDir: -20, len: 95.2, num: [64.5, 31.5], part: 3 },
    { n: 7, d: "M82.81,60.54c4.45,4.37,11.49,17.97,12.61,24.77", type: "㇔", start: [82.81, 60.54], end: [95.42, 85.31], dir: 63, endDir: 81, len: 28.1, num: [76.5, 61.5], part: 3 },
  ],
  parts: [
    { element: "禾", position: "left", radical: "general" },
    { element: "丿", position: "top", parent: 0 },
    { element: "木", position: "bottom", parent: 0 },
    { element: "厶", position: "right" },
  ],
};

export default data;
