/*
 * KanjiVG stroke data for 立 (U+7ACB) — release 20260714, source file kanji/07acb.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "立",
  code: "07acb",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M51.51,15c1.43,1.43,2.24,3.25,2.24,5.81c0,4.06,0,9.56,0,13.69", type: "㇑a", start: [51.51, 15], end: [53.75, 34.5], dir: 83, endDir: 90, len: 20.1, num: [42.75, 15.5], part: 0 },
    { n: 2, d: "M22,37.86c2.62,0.51,4.75,0.34,7,0.16c11.38-0.9,36.13-3.4,50.65-4.26c2.38-0.14,4.86-0.01,6.86,0.4", type: "㇐", start: [22, 37.86], end: [86.51, 34.16], dir: -3, endDir: 12, len: 64.7, num: [13.5, 38.5], part: 0 },
    { n: 3, d: "M32,49c4.75,9.75,8.25,22.5,9.5,31.5", type: "㇔", start: [32, 49], end: [41.5, 80.5], dir: 73, endDir: 82, len: 33, num: [24.25, 49.5], part: 1 },
    { n: 4, d: "M74,39c0.75,1.38,0.81,3.29,0.5,4.5c-2.88,11.12-8.5,30.38-12.75,42", type: "㇒", start: [74, 39], end: [61.75, 85.5], dir: 105, endDir: 110, len: 48.5, num: [64.75, 44.63], part: 1 },
    { n: 5, d: "M15.25,88.8c2.33,0.45,5.89,0.53,7.82,0.39c18.3-1.32,40.31-1.94,64.83-2.75c3.24-0.11,6.14,0.05,8.47,0.88", type: "㇐", start: [15.25, 88.8], end: [96.37, 87.32], dir: -1, endDir: 20, len: 81.3, num: [7.5, 91.5], part: 1 },
  ],
  parts: [
    { element: "亠", position: "top" },
    { position: "bottom" },
  ],
};

export default data;
