/*
 * KanjiVG stroke data for 米 (U+7C73) — release 20260714, source file kanji/07c73.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "米",
  code: "07c73",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M26.64,25.46c4.03,2.47,10.1,9.45,11.11,13.29", type: "㇔", start: [26.64, 25.46], end: [37.75, 38.75], dir: 50, endDir: 75, len: 17.6, num: [20.5, 26.5] },
    { n: 2, d: "M78.52,19.64c0.1,0.85-0.21,2.19-0.63,2.91C75.25,27,72.25,30.5,66.56,35.22", type: "㇒", start: [78.52, 19.64], end: [66.56, 35.22], dir: 128, endDir: 140, len: 20.1, num: [69.5, 19.5] },
    { n: 3, d: "M18,49.25c2.25,0.62,4.8,0.83,8.24,0.5c19.67-1.88,38.77-4.5,52.75-5.25c3.46-0.19,6.13-0.12,8.51,0.5", type: "㇐", start: [18, 49.25], end: [87.5, 45], dir: -3, endDir: 15, len: 69.9, num: [10.5, 49.5] },
    { n: 4, d: "M51.75,13.25C53.06,14.56,54,17,54,18.75c0,4.75,0.06,50.93-0.14,70.51c-0.04,3.54-0.07,5.54-0.11,6.49", type: "㇑", start: [51.75, 13.25], end: [53.75, 95.75], dir: 89, endDir: 92, len: 83.1, num: [42.5, 14.5] },
    { n: 5, d: "M49.38,48.25c0,1.47-0.81,3.5-1.26,4.29C41,64.89,27.22,78.84,13.5,85.75", type: "㇒", start: [49.38, 48.25], end: [13.5, 85.75], dir: 134, endDir: 153, len: 53.1, num: [36.5, 59.5] },
    { n: 6, d: "M55.75,48.25C60,53,75.38,68.74,83.7,76.96c2.8,2.77,5.74,5.16,9.43,6.79", type: "㇏", start: [55.75, 48.25], end: [93.13, 83.75], dir: 44, endDir: 24, len: 51.8, num: [67.5, 57.5] },
  ],
  parts: [

  ],
};

export default data;
