/*
 * KanjiVG stroke data for 耳 (U+8033) — release 20260714, source file kanji/08033.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "耳",
  code: "08033",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M20.25,20c3.03,0.85,6.17,0.58,9.24,0.21c14.62-1.76,31.45-3.95,48.12-5.06c3.33-0.22,6.59-0.2,9.89,0.35", type: "㇐", start: [20.25, 20], end: [87.5, 15.5], dir: -4, endDir: 9, len: 67.6, num: [12.5, 21.5] },
    { n: 2, d: "M36.68,22.5c1.1,1.1,1.64,2.71,1.64,4.73c0,1.6-0.33,40.02-0.33,41.52", type: "㇑a", start: [36.68, 22.5], end: [37.99, 68.75], dir: 88, endDir: 90, len: 46.7, num: [29.5, 30.5] },
    { n: 3, d: "M39.5,35.5c6.75-0.88,24-2.75,32.25-3.25", type: "㇐a", start: [39.5, 35.5], end: [71.75, 32.25], dir: -6, endDir: -3, len: 32.4, num: [43.5, 31.5] },
    { n: 4, d: "M39.25,51.25c7-0.5,24.62-2.75,32.25-3", type: "㇐a", start: [39.25, 51.25], end: [71.5, 48.25], dir: -5, endDir: -2, len: 32.4, num: [43.5, 48] },
    { n: 5, d: "M17.25,71c0.75,1.12,2.01,1.81,3.75,1.5c7-1.25,48-8.75,58.75-10.75", type: "㇀", start: [17.25, 71], end: [79.75, 61.75], dir: -8, endDir: -11, len: 64, num: [8.5, 76.5] },
    { n: 6, d: "M71,18.5c1,1,1.75,2.5,1.75,4.25c0,1.05,0.18,44.73,0.23,64.75c0.01,3.74,0.02,6.64,0.02,8.25", type: "㇑", start: [71, 18.5], end: [73, 95.75], dir: 89, endDir: 90, len: 77.7, num: [64.5, 25.5] },
  ],
  parts: [

  ],
};

export default data;
