/*
 * KanjiVG stroke data for 聞 (U+805E) — release 20260714, source file kanji/0805e.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "聞",
  code: "0805e",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M16.14,17.97c0.94,0.94,1.51,2.16,1.51,3.25c0,0.77-0.03,48.45-0.18,66.29c-0.03,3.16-0.05,5.37-0.07,6.21", type: "㇑", start: [16.14, 17.97], end: [17.4, 93.72], dir: 89, endDir: 91, len: 76.2, num: [10.5, 26.5], part: 1 },
    { n: 2, d: "M19.01,19.6c6.86-1.22,18.49-3.1,21.08-3.39c1.9-0.21,3.03,0.79,3,2.46c-0.04,1.84-0.59,10.46-1.44,20.02c-0.09,1.04-0.15,2-0.15,2.69", type: "㇕a", start: [19.01, 19.6], end: [41.5, 41.38], dir: 44, endDir: 90, len: 48.6, num: [19.5, 16.5], part: 1 },
    { n: 3, d: "M18.81,30.43c6.94-1.05,15.82-2.55,22.41-2.9", type: "㇐a", start: [18.81, 30.43], end: [41.22, 27.53], dir: -7, endDir: -3, len: 22.6, num: [21.5, 27.13], part: 1 },
    { n: 4, d: "M17.86,42.57C26.25,41.25,33,40,40.42,39.4", type: "㇐a", start: [17.86, 42.57], end: [40.42, 39.4], dir: -8, endDir: -5, len: 22.8, num: [21.5, 39.13], part: 1 },
    { n: 5, d: "M66.21,14.22c0.66,0.66,1.17,1.78,1.17,2.93c0,0.56,0.12,13.19,0.17,19.1c0.02,1.71,0.03,2.83,0.03,2.91", type: "㇑", start: [66.21, 14.22], end: [67.58, 39.16], dir: 87, endDir: 90, len: 25.2, num: [59.5, 21.5], part: 2 },
    { n: 6, d: "M68.51,16.1c6.89-1.1,19.28-3.26,21.17-3.36c1.96-0.1,3.57,1.38,3.57,2.98c0,18.78-0.26,60.28-0.26,73.89c0,11.13-6.37,2.13-8.21,0.25", type: "㇆a", start: [68.51, 16.1], end: [84.78, 89.86], dir: 78, endDir: -134, len: 115.1, num: [69.5, 12.5], part: 2 },
    { n: 7, d: "M68.59,25.94c5.16-0.69,18.16-2.44,23-2.71", type: "㇐a", start: [68.59, 25.94], end: [91.59, 23.23], dir: -7, endDir: -3, len: 23.2, num: [71.5, 23.5], part: 2 },
    { n: 8, d: "M69.13,36.75c6.37-0.75,15.12-2,22.15-2.53", type: "㇐a", start: [69.13, 36.75], end: [91.28, 34.22], dir: -7, endDir: -4, len: 22.3, num: [71.5, 34.63], part: 2 },
    { n: 9, d: "M33.5,51.24c1.71,0.31,4.02,0.25,5.71,0.06c9.6-1.05,20.21-3.05,30.66-4.05c2.83-0.27,4.57-0.1,6,0.05", type: "㇐", start: [33.5, 51.24], end: [75.87, 47.3], dir: -5, endDir: 6, len: 42.7, num: [26.25, 53.5], part: 3 },
    { n: 10, d: "M42.71,53c0.89,0.89,1.3,2.26,1.3,3.51S44,79.31,44,83.84", type: "㇑a", start: [42.71, 53], end: [44, 83.84], dir: 88, endDir: 90, len: 31.2, num: [33.5, 61.5], part: 3 },
    { n: 11, d: "M45.13,61.43c4.49-0.43,13.74-2.05,19.78-2.36", type: "㇐a", start: [45.13, 61.43], end: [64.91, 59.07], dir: -7, endDir: -3, len: 19.9, num: [47.5, 58.5], part: 3 },
    { n: 12, d: "M44.81,71.67c5.72-0.67,12.31-1.92,20.12-2.95", type: "㇐a", start: [44.81, 71.67], end: [64.93, 68.72], dir: -8, endDir: -8, len: 20.3, num: [47.5, 68.5], part: 3 },
    { n: 13, d: "M32.51,85.14c0.99,0.86,2.2,1.23,3.25,0.92c4.87-1.43,28.2-7.83,34.76-9.39", type: "㇀", start: [32.51, 85.14], end: [70.52, 76.67], dir: -13, endDir: -13, len: 39.5, num: [23.5, 92.5], part: 3 },
    { n: 14, d: "M64.84,49.66c0.62,0.63,1.05,1.71,1.05,2.99c0,0.66,0.12,27.55,0.15,39.1c0.01,1.88,0.01,3.36,0.01,4.25", type: "㇑", start: [64.84, 49.66], end: [66.05, 96], dir: 89, endDir: 90, len: 46.6, num: [56.5, 55.5], part: 3 },
  ],
  parts: [
    { element: "門", position: "kamae", radical: "nelson" },
    { position: "left", parent: 0 },
    { position: "right", parent: 0 },
    { element: "耳", radical: "tradit" },
  ],
};

export default data;
