/*
 * KanjiVG stroke data for 肉 (U+8089) — release 20260714, source file kanji/08089.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "肉",
  code: "08089",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M19,30.27c1.11,1.11,1.44,2.82,1.44,4.56c0,5.46,0.16,39.85,0.21,53.67c0.01,3.04,0.02,5.09,0.02,5.61", type: "㇑", start: [19, 30.27], end: [20.67, 94.11], dir: 89, endDir: 90, len: 64.2, num: [13.5, 39.5] },
    { n: 2, d: "M21.01,32.11c16.09-1.31,61.86-4.76,63.38-4.76c3.86,0,5.92,1.9,5.92,5.3c0,1.91,0.24,54.28,0.24,58.68c0,9.67-6.04,2.42-9.44-0.71", type: "㇆a", start: [21.01, 32.11], end: [81.11, 90.62], dir: 44, endDir: -137, len: 146.5, num: [24.5, 28.5] },
    { n: 3, d: "M53.28,12.75C54,14,54.03,15.33,54.1,16.79c0.65,13.46-8.35,34.46-24.6,38.71", type: "㇒", start: [53.28, 12.75], end: [29.5, 55.5], dir: 119, endDir: 165, len: 53.2, num: [44.5, 14.5] },
    { n: 4, d: "M54.5,37.25c8.56,3.18,22.11,13.06,24.25,18", type: "㇔", start: [54.5, 37.25], end: [78.75, 55.25], dir: 37, endDir: 67, len: 30.6, num: [61.5, 39.13] },
    { n: 5, d: "M52,51.38c0.12,1.22,0.05,2.34-0.47,3.45c-3.28,7.05-11.03,17.05-21.23,22.4", type: "㇒", start: [52, 51.38], end: [30.3, 77.23], dir: 130, endDir: 152, len: 34.9, num: [44.5, 55.5] },
    { n: 6, d: "M52,62.25C60.47,65.03,73.88,73.68,76,78", type: "㇔", start: [52, 62.25], end: [76, 78], dir: 33, endDir: 64, len: 29.1, num: [56.5, 62.5] },
  ],
  parts: [

  ],
};

export default data;
