/*
 * KanjiVG stroke data for 花 (U+82B1) — release 20260714, source file kanji/082b1.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "花",
  code: "082b1",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M17,29.77c3,0.73,6.35,0.54,9.37,0.29c16.22-1.35,36.31-4.64,56.76-4.79c2.4-0.02,4.77,0.04,7.12,0.51", type: "㇐", start: [17, 29.77], end: [90.25, 25.78], dir: -3, endDir: 11, len: 73.6, num: [9.5, 30.13], part: 0 },
    { n: 2, d: "M32.25,16c1.25,0.5,2.25,1.62,2.5,2.75c1.33,5.97,4.86,19.92,5,20.75", type: "㇑a", start: [32.25, 16], end: [39.75, 39.5], dir: 72, endDir: 80, len: 25.2, num: [22.5, 15.5], part: 0 },
    { n: 3, d: "M71.25,12.5c0.42,1.18,0.47,3.05,0,4.5c-2.19,6.77-6.14,19.12-6.75,20.75", type: "㇑a", start: [71.25, 12.5], end: [64.5, 37.75], dir: 105, endDir: 111, len: 26.4, num: [62.5, 12.5], part: 0 },
    { n: 4, d: "M38.25,48.25c0.25,1.75-0.37,3.31-0.98,4.44C33.25,60,24.8,69.67,19.5,74.5", type: "㇒", start: [38.25, 48.25], end: [19.5, 74.5], dir: 126, endDir: 138, len: 32.9, num: [28.5, 48.5], part: 2 },
    { n: 5, d: "M30.75,65.5c0.75,1,1.12,1.97,1.12,3c0,6.64-0.08,16.47-0.11,24c-0.01,1.96-0.01,3.82-0.01,5.5", type: "㇑", start: [30.75, 65.5], end: [31.75, 98], dir: 88, endDir: 90, len: 32.8, num: [24.5, 78.5], part: 2 },
    { n: 6, d: "M84.25,50.25c-0.12,1.62-0.84,2.87-2,3.75c-4.62,3.5-11,6.75-19,9.75", type: "㇒", start: [84.25, 50.25], end: [63.25, 63.75], dir: 147, endDir: 159, len: 25.8, num: [74.5, 49.5], part: 3 },
    { n: 7, d: "M58.25,43.75c1.06,1.06,1.5,2.5,1.5,4.75c0,2.96-0.22,20.59-0.22,31.25C59.53,93,63,94.15,77,94.15c16.25,0,18-2.65,18-11.15", type: "㇟", start: [58.25, 43.75], end: [95, 83], dir: 47, endDir: -90, len: 89, num: [50.5, 44.5], part: 3 },
  ],
  parts: [
    { element: "艹", position: "top", radical: "general" },
    { element: "化", position: "bottom" },
    { element: "亻", parent: 1 },
    { element: "匕", parent: 1 },
  ],
};

export default data;
