/*
 * KanjiVG stroke data for 英 (U+82F1) — release 20260714, source file kanji/082f1.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "英",
  code: "082f1",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M21.25,25.52c2.62,0.61,5.04,0.45,7.5,0.26c12.73-0.97,38.06-2.66,51.75-2.97c2.6-0.06,5.2-0.16,7.75,0.47", type: "㇐", start: [21.25, 25.52], end: [88.25, 23.28], dir: -2, endDir: 14, len: 67.2, num: [14.5, 27.13], part: 0 },
    { n: 2, d: "M38,14c1.01,0.63,1.87,1.83,1.98,2.7c0.94,7.23,1.85,13.14,2.52,18.92", type: "㇑a", start: [38, 14], end: [42.5, 35.62], dir: 78, endDir: 83, len: 22.5, num: [28.5, 15.5], part: 0 },
    { n: 3, d: "M67.61,11.62c0.62,0.88,0.96,2.15,0.68,3.52c-1.79,8.8-2.07,11.06-3.79,19.36", type: "㇑a", start: [67.61, 11.62], end: [64.5, 34.5], dir: 98, endDir: 102, len: 23.4, num: [58.5, 13.5], part: 0 },
    { n: 4, d: "M31.82,44.53c1.06,0.93,1.7,2.4,1.85,3.53c1.08,7.94,1.83,13.56,2.09,16.43", type: "㇑a", start: [31.82, 44.53], end: [35.76, 64.49], dir: 79, endDir: 85, len: 20.6, num: [25.99, 52.41], part: 1 },
    { n: 5, d: "M33.78,46.09c3.6-0.37,34-3.9,38.89-4.18c2.82-0.16,5.32,0.84,4.54,4.43c-0.91,4.17-2.93,14.03-3.35,16.09", type: "㇕b", start: [33.78, 46.09], end: [73.86, 62.43], dir: 22, endDir: 102, len: 63.3, num: [35.25, 42.13], part: 1 },
    { n: 6, d: "M18.05,65.13c2.77,1.11,5.8,0.75,8.69,0.56c14-0.94,37.44-2.18,55.15-3.25c3.63-0.22,8.35-0.18,11.43,0.62", type: "㇐", start: [18.05, 65.13], end: [93.32, 63.06], dir: -2, endDir: 15, len: 75.5, num: [11.25, 67.63], part: 2 },
    { n: 7, d: "M53.05,33.5c0.79,0.79,1.18,2.07,1.18,3.9c0,38.26-9.73,46.22-31.42,57.85", type: "㇒", start: [53.05, 33.5], end: [22.81, 95.25], dir: 116, endDir: 152, len: 75.1, num: [56.5, 32.5], part: 2 },
    { n: 8, d: "M54.12,64.88c7.38,7.75,18.62,17.55,26.7,23.84c2.36,1.84,5.49,3.89,8.3,5.03", type: "㇏", start: [54.12, 64.88], end: [89.12, 93.75], dir: 40, endDir: 22, len: 45.6, num: [68.5, 73.5], part: 2 },
  ],
  parts: [
    { element: "艹", position: "top", radical: "general" },
    { element: "央", position: "bottom" },
    { element: "大", parent: 1 },
  ],
};

export default data;
