/*
 * KanjiVG stroke data for 茶 (U+8336) — release 20260714, source file kanji/08336.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "茶",
  code: "08336",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M18.5,27.02c2.2,0.53,4.76,0.73,6.96,0.53C41.88,26,68,23.62,82.68,23.01c3.66-0.15,5.87,0.25,7.7,0.51", type: "㇐", start: [18.5, 27.02], end: [90.38, 23.52], dir: -3, endDir: 8, len: 72.1, num: [11.5, 28.5], part: 0 },
    { n: 2, d: "M36.75,15.5c1.05,1.18,1.51,1.78,1.76,3.44c1.05,6.91,1.94,13.8,2.24,16.31", type: "㇑a", start: [36.75, 15.5], end: [40.75, 35.25], dir: 79, endDir: 83, len: 20.4, num: [27.75, 16.5], part: 0 },
    { n: 3, d: "M67.75,12.25c0.41,1.59,0.43,2.77,0.06,4.37c-1.62,7.05-2.18,9.88-4.06,18.13", type: "㇑a", start: [67.75, 12.25], end: [63.75, 34.75], dir: 100, endDir: 103, len: 23, num: [59.25, 13.5], part: 0 },
    { n: 4, d: "M51.5,34.75c0.35,1.84-0.35,3.08-1.28,4.64c-4.89,8.2-14.99,21.54-32.97,31.11", type: "㇒", start: [51.5, 34.75], end: [17.25, 70.5], dir: 134, endDir: 152, len: 50.8, num: [38.5, 45.5], part: 2 },
    { n: 5, d: "M52.5,38.25c5.9,4.37,23.65,17.47,32.05,23.16c3.11,2.1,5.98,3.44,9.7,4.09", type: "㇏", start: [52.5, 38.25], end: [94.25, 65.5], dir: 33, endDir: 10, len: 50.2, num: [65.5, 45.5], part: 2 },
    { n: 6, d: "M34.53,68.21c1.1,0.15,4.05,0.54,6.95,0.19c7.4-0.9,18.9-2.4,28.02-3.17c2.9-0.24,3.66-0.15,5.48,0", type: "㇐", start: [34.53, 68.21], end: [74.98, 65.23], dir: -4, endDir: 5, len: 40.7, num: [28.5, 73.63], part: 3 },
    { n: 7, d: "M52.32,53.94c1.18,1.31,1.81,3.06,1.81,6.15c0,0.46,0,19.56-0.06,30.66c-0.02,3.5-0.05,6.13-0.08,7", type: "㇑", start: [52.32, 53.94], end: [53.99, 97.75], dir: 88, endDir: 92, len: 44.2, num: [45.5, 60.5], part: 3 },
    { n: 8, d: "M38.52,79.14c0.11,1-0.1,1.94-0.64,2.8c-1.7,3.35-6.13,7.94-12.38,12.31", type: "㇒", start: [38.52, 79.14], end: [25.5, 94.25], dir: 131, endDir: 145, len: 20.5, num: [30.5, 82.5], part: 3 },
    { n: 9, d: "M68.5,78.75c4.79,2.51,12.36,10.32,13.56,14.22", type: "㇔/㇏", start: [68.5, 78.75], end: [82.06, 92.97], dir: 46, endDir: 73, len: 19.9, num: [60.5, 78.5], part: 3 },
  ],
  parts: [
    { element: "艹", position: "top", radical: "general" },
    { position: "bottom" },
    { element: "人", parent: 1 },
    { element: "木", parent: 1 },
  ],
};

export default data;
