/*
 * KanjiVG stroke data for 行 (U+884C) — release 20260714, source file kanji/0884c.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "行",
  code: "0884c",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M32.49,12c-0.12,1-0.45,1.9-1.1,2.62C28.29,18.06,22.2,22.6,12.5,28", type: "㇒", start: [32.49, 12], end: [12.5, 28], dir: 141, endDir: 151, len: 26.1, num: [25.75, 10.5], part: 0 },
    { n: 2, d: "M36.5,31.75c0.07,0.73,0.08,2.28-0.39,3.18C32.12,42.5,23.83,52.5,11,62.75", type: "㇒", start: [36.5, 31.75], end: [11, 62.75], dir: 129, endDir: 141, len: 41, num: [28.5, 31.5], part: 1 },
    { n: 3, d: "M25.57,51.75c0.9,0.9,1.23,2.25,1.23,3.26c0,0.72,0.04,24.47-0.07,35.49c-0.02,2.19-0.04,3.87-0.07,4.75", type: "㇑", start: [25.57, 51.75], end: [26.66, 95.25], dir: 89, endDir: 92, len: 43.8, num: [19.5, 65.5], part: 1 },
    { n: 4, d: "M50.5,18.45c1.44,0.35,3.81,0.52,5.23,0.35c7.14-0.8,16.01-2.43,24.49-3.06c2.38-0.18,3.83-0.06,5.02,0.11", type: "㇐", start: [50.5, 18.45], end: [85.24, 15.85], dir: -4, endDir: 8, len: 35, num: [49.5, 15.5], part: 2 },
    { n: 5, d: "M43.13,41.42c1.5,0.38,4.27,0.58,5.76,0.38c12.86-1.67,28.86-4.05,41.85-5.38c2.49-0.26,4.01,0.18,5.26,0.37", type: "㇐", start: [43.13, 41.42], end: [96, 36.79], dir: -5, endDir: 9, len: 53.3, num: [43.5, 38.5], part: 2 },
    { n: 6, d: "M71.52,41.33c1.26,1.26,1.76,2.79,1.76,5.27c0,14.56-0.26,38.66-0.26,43.62c0,8.03-7.21-0.5-8.71-1.75", type: "㇚", start: [71.52, 41.33], end: [64.31, 88.47], dir: 99, endDir: -140, len: 62.4, num: [64.5, 50.5], part: 2 },
  ],
  parts: [
    { element: "彳", position: "left" },
    { element: "亻", parent: 0 },
    { position: "right" },
  ],
};

export default data;
