/*
 * KanjiVG stroke data for 西 (U+897F) — release 20260714, source file kanji/0897f.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "西",
  code: "0897f",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M20.63,24.22c2.31,0.34,6.05,0.3,8.35,0.09c15.15-1.43,36.18-3.38,49.83-4.02c3.84-0.18,6.66-0.09,8.58,0.08", type: "㇐", start: [20.63, 24.22], end: [87.39, 20.37], dir: -3, endDir: 5, len: 66.9, num: [13.5, 25.63] },
    { n: 2, d: "M18.25,48.63c1.25,1.25,2.14,3.42,2.33,4.49c1.25,6.77,3.24,20.18,5.12,33.35c0.27,1.87,0.53,3.72,0.77,5.53", type: "㇑", start: [18.25, 48.63], end: [26.47, 92], dir: 79, endDir: 82, len: 44.4, num: [9.5, 55.63] },
    { n: 3, d: "M20.75,50.26c17.77-1.6,53.73-5.05,63.68-5.27c4.51-0.1,7.27,2.79,6.55,6.54c-1.6,8.35-4.1,21.97-6.49,32.97c-0.36,1.68-0.61,2.5-1.13,4.6", type: "㇕a", start: [20.75, 50.26], end: [83.36, 89.1], dir: 32, endDir: 104, len: 113, num: [20.5, 46.5] },
    { n: 4, d: "M42.75,26.75c0.5,1.25,0.81,3.99,0.85,5.73C43.98,48.84,42,64.5,30.64,73.77", type: "㇒", start: [42.75, 26.75], end: [30.64, 73.77], dir: 104, endDir: 141, len: 50.7, num: [35.5, 33.5] },
    { n: 5, d: "M60.6,24.46c0.94,1.12,1.74,2.94,1.74,4.67c0,13.33-0.45,21.61-0.45,27.37c0,10.25,0.62,11.14,11.36,11.14c6.38,0,8.94-0.54,10.55-1.53", type: "㇟a", start: [60.6, 24.46], end: [83.8, 66.11], dir: 61, endDir: -32, len: 63.1, num: [54.5, 33.5] },
    { n: 6, d: "M27.34,88.55C40.75,88,66.69,86.2,83,85.97", type: "㇐a", start: [27.34, 88.55], end: [83, 85.97], dir: -3, endDir: -1, len: 55.7, num: [30.5, 85.5] },
  ],
  parts: [

  ],
};

export default data;
