/*
 * KanjiVG stroke data for 見 (U+898B) — release 20260714, source file kanji/0898b.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "見",
  code: "0898b",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M32.5,15.46c0.96,0.96,1.18,2.1,1.18,3.52c0,1.12,0.07,27.43-0.02,39.27c-0.02,3.12-0.02,5.21,0.02,5.5", type: "㇑", start: [32.5, 15.46], end: [33.68, 63.75], dir: 89, endDir: 82, len: 48.6, num: [26.5, 23.5], part: 0 },
    { n: 2, d: "M34.65,17.15c9.23-1.27,22.23-2.65,31.1-3.65c2.99-0.34,4.26,1.01,4.26,3.55c0,2.5-0.1,28.08-0.14,38.96c-0.01,2.91-0.02,4.75-0.02,4.79", type: "㇕a", start: [34.65, 17.15], end: [69.85, 60.8], dir: 51, endDir: 90, len: 81.6, num: [35.5, 13.5], part: 0 },
    { n: 3, d: "M34.84,31.1c7.28-0.6,25.03-2.98,33.9-3.38", type: "㇐a", start: [34.84, 31.1], end: [68.74, 27.72], dir: -6, endDir: -3, len: 34.1, num: [38.25, 27.43], part: 0 },
    { n: 4, d: "M34.86,44.63C43.38,44,59,42.12,68.6,41.51", type: "㇐a", start: [34.86, 44.63], end: [68.6, 41.51], dir: -5, endDir: -4, len: 33.9, num: [38.25, 40.63], part: 0 },
    { n: 5, d: "M34.71,59.66C44.5,59,58.38,57.5,68.45,57.03", type: "㇐a", start: [34.71, 59.66], end: [68.45, 57.03], dir: -4, endDir: -3, len: 33.8, num: [38.25, 55.63], part: 0 },
    { n: 6, d: "M41.99,66.75c0.26,1.5,0.01,2.99-0.41,4.04c-2.7,6.83-13.83,20.83-28.41,27.87", type: "㇒", start: [41.99, 66.75], end: [13.17, 98.66], dir: 132, endDir: 154, len: 44.6, num: [32.5, 74.5], part: 1 },
    { n: 7, d: "M54.49,61.37c1.07,1.07,1.33,2.59,1.38,4.43c0.2,8.19,0.04,6.2,0.04,18.2c0,10.12,1.23,11.53,18.54,11.53c18.81,0,19.81-1.53,19.81-10.12", type: "㇟", start: [54.49, 61.37], end: [94.26, 85.41], dir: 31, endDir: -90, len: 75.8, num: [48.5, 69.5], part: 1 },
  ],
  parts: [
    { element: "目", position: "top" },
    { element: "儿", position: "bottom" },
  ],
};

export default data;
