/*
 * KanjiVG stroke data for 言 (U+8A00) — release 20260714, source file kanji/08a00.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "言",
  code: "08a00",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M48.38,11.25c4.38,2.5,8.88,7.75,10.38,11.5", type: "㇔", start: [48.38, 11.25], end: [58.76, 22.75], dir: 48, endDir: 68, len: 15.7, num: [41.25, 12.13] },
    { n: 2, d: "M14.88,33.98c2.52,0.54,6.91,0.76,9.42,0.54c22.95-2.02,40.82-4.02,59.99-4.73c4.2-0.16,6.73,0.26,8.83,0.53", type: "㇐", start: [14.88, 33.98], end: [93.12, 30.32], dir: -3, endDir: 7, len: 78.5, num: [6.75, 36.13] },
    { n: 3, d: "M38.63,46.65C40,47,41,47,42.45,46.88c7.06-0.6,18.6-2.27,22.81-2.6c1.86-0.15,3.36-0.15,4.74,0.22", type: "㇐", start: [38.63, 46.65], end: [70, 44.5], dir: -4, endDir: 15, len: 31.6, num: [30.75, 46.63] },
    { n: 4, d: "M37.88,61.4c1.5,0.23,2.75,0.35,4.16,0.23c7.68-0.67,20.23-2.28,24.8-2.85c2.16-0.27,3.66-0.15,5.17,0.22", type: "㇐", start: [37.88, 61.4], end: [72.01, 59], dir: -4, endDir: 14, len: 34.3, num: [29.25, 63.13] },
    { n: 5, d: "M37,74.75c0.81,0.81,1.4,1.76,1.53,2.77c0.85,6.73,1.9,11.43,2.89,18.45c0.18,1.24,0.35,2.43,0.54,3.53", type: "㇑", start: [37, 74.75], end: [41.96, 99.5], dir: 79, endDir: 80, len: 25.5, num: [30.5, 82.63], part: 0 },
    { n: 6, d: "M39.53,76.74c9.24-1.7,22.59-3.37,30.29-4.25c2.21-0.25,3.55,1.17,3.24,2.32c-0.69,2.52-3.74,12.7-4.94,16.98", type: "㇕b", start: [39.53, 76.74], end: [68.12, 91.79], dir: 28, endDir: 106, len: 52.9, num: [39.5, 73.63], part: 0 },
    { n: 7, d: "M42.2,95.16c6.19-0.53,16.55-1.39,25.32-2.22c1.33-0.13,2.73-0.12,3.95-0.12", type: "㇐b", start: [42.2, 95.16], end: [71.47, 92.82], dir: -5, endDir: 0, len: 29.4, num: [44.5, 91.63], part: 0 },
  ],
  parts: [
    { element: "口" },
  ],
};

export default data;
