/*
 * KanjiVG stroke data for 話 (U+8A71) — release 20260714, source file kanji/08a71.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "話",
  code: "08a71",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M24.99,14c2.36,1.5,6.1,6.17,6.7,8.5", type: "㇔", start: [24.99, 14], end: [31.69, 22.5], dir: 52, endDir: 76, len: 11, num: [17.5, 14.63], part: 0 },
    { n: 2, d: "M11.37,32.83c1.41,0.42,3.07,0.29,4.51,0.17c8.29-0.7,16.95-1.9,23.59-2.81c1.28-0.17,3.22,0.11,3.87,0.23", type: "㇐", start: [11.37, 32.83], end: [43.34, 30.42], dir: -4, endDir: 10, len: 32.2, num: [3.5, 34.63], part: 0 },
    { n: 3, d: "M17.78,47.06c1.05,0.32,2.15,0.35,3.23,0.29c4.11-0.23,10.69-1.59,14.43-1.97c1.31-0.13,2.68-0.13,4.04-0.13", type: "㇐", start: [17.78, 47.06], end: [39.48, 45.25], dir: -5, endDir: 0, len: 21.9, num: [10.67, 48.13], part: 0 },
    { n: 4, d: "M18.58,59.33c1.2,0.36,2.8,0.13,4.04,0.08c3.71-0.16,8.38-0.79,12.92-1.36c1.43-0.18,2.85-0.34,4.3-0.08", type: "㇐", start: [18.58, 59.33], end: [39.84, 57.97], dir: -4, endDir: 10, len: 21.4, num: [10.5, 61.63], part: 0 },
    { n: 5, d: "M17.4,71.9c0.81,0.68,1.33,1.82,1.49,2.87c0.73,4.61,1.4,8.31,2.2,13.18c0.22,1.33,0.43,2.62,0.63,3.8", type: "㇑", start: [17.4, 71.9], end: [21.72, 91.75], dir: 78, endDir: 80, len: 20.5, num: [10.68, 78.5], part: 1 },
    { n: 6, d: "M19.64,73.54c6.67-1.14,13.31-2.75,19.46-3.66c1.85-0.27,2.96,1.26,2.7,2.51c-0.89,4.19-2.46,8.16-4.05,14.07", type: "㇕b", start: [19.64, 73.54], end: [37.75, 86.46], dir: 36, endDir: 105, len: 38.8, num: [20.5, 70.63], part: 1 },
    { n: 7, d: "M22.49,89.55c4.76-0.55,8.86-1.17,14.02-1.72c0.93-0.1,1.91,0.04,2.97-0.09", type: "㇐b", start: [22.49, 89.55], end: [39.48, 87.74], dir: -6, endDir: -7, len: 17.1, num: [25.5, 85.5], part: 1 },
    { n: 8, d: "M81.75,13.75c-0.12,1.25-0.79,2.39-1.66,3.06c-4.84,3.69-15.34,9.94-29.34,14.94", type: "㇒", start: [81.75, 13.75], end: [50.75, 31.75], dir: 150, endDir: 160, len: 36.6, num: [72.5, 13.5], part: 3 },
    { n: 9, d: "M45.39,45.8c1.55,0.34,4.36,0.62,6.73,0.34C62.8,44.9,76.37,43.07,91,42.23c2.28-0.13,4.49-0.01,6.75,0.29", type: "㇐", start: [45.39, 45.8], end: [97.75, 42.52], dir: -4, endDir: 8, len: 52.6, num: [47.25, 43.5], part: 3 },
    { n: 10, d: "M68.87,27.19c1.4,1.4,1.85,3.06,1.85,4.88c0,1.44-0.21,28.18-0.21,35.16", type: "㇑a", start: [68.87, 27.19], end: [70.51, 67.23], dir: 88, endDir: 90, len: 40.5, num: [59.5, 36.5], part: 3 },
    { n: 11, d: "M52.07,67.83c0.93,1.17,1.22,1.76,1.35,2.34c1.38,6.2,2.13,12.33,3.08,20.33c0.13,1.14,0.27,2.31,0.42,3.53", type: "㇑", start: [52.07, 67.83], end: [56.92, 94.03], dir: 80, endDir: 83, len: 26.9, num: [45.5, 78.5], part: 4 },
    { n: 12, d: "M54.62,69.29c12.9-1.37,25.41-2.73,32.68-3.31c2.94-0.24,3.79,2.4,3.37,3.8c-1.47,4.87-3.03,11.64-5.04,18.35", type: "㇕b", start: [54.62, 69.29], end: [85.63, 88.13], dir: 31, endDir: 107, len: 57.9, num: [53.5, 66.5], part: 4 },
    { n: 13, d: "M56.64,91.74c7.5-0.57,16.99-1.13,27.14-1.93c1.37-0.11,2.75-0.22,4.13-0.34", type: "㇐b", start: [56.64, 91.74], end: [87.91, 89.47], dir: -4, endDir: -5, len: 31.4, num: [60.5, 88.5], part: 4 },
  ],
  parts: [
    { element: "言", position: "left", radical: "general" },
    { element: "口", parent: 0 },
    { element: "舌", position: "right" },
    { element: "千", position: "top", parent: 2 },
    { element: "口", position: "bottom", parent: 2 },
  ],
};

export default data;
