/*
 * KanjiVG stroke data for 語 (U+8A9E) — release 20260714, source file kanji/08a9e.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "語",
  code: "08a9e",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M26,15.25c2.82,1.41,7.29,5.8,8,8", type: "㇔", start: [26, 15.25], end: [34, 23.25], dir: 45, endDir: 72, len: 11.5, num: [20.25, 13.63], part: 0 },
    { n: 2, d: "M12.37,32.97c1.25,0.28,2.88,0.66,4.36,0.53c7.02-0.59,17.78-1.75,25.95-3c1.52-0.23,3.57-0.38,5.16,0.03", type: "㇐", start: [12.37, 32.97], end: [47.84, 30.53], dir: -4, endDir: 14, len: 35.7, num: [3.75, 33.13], part: 0 },
    { n: 3, d: "M18.73,45.76c0.38,0.18,2.71,0.2,3.1,0.18c3.97-0.21,9.79-1.19,14.46-2.31c1.67-0.4,2.71-0.38,3.86-0.08", type: "㇐", start: [18.73, 45.76], end: [40.15, 43.55], dir: -6, endDir: 15, len: 21.7, num: [9.75, 45.13], part: 0 },
    { n: 4, d: "M18.73,58.89c0.89,0.23,1.89,0.36,3.35,0.15c3.89-0.54,10.71-1.51,14.85-2.29c0.7-0.13,1.82-0.26,2.61-0.1", type: "㇐", start: [18.73, 58.89], end: [39.54, 56.65], dir: -6, endDir: 11, len: 21, num: [9.75, 58.63], part: 0 },
    { n: 5, d: "M17.14,71.9c0.63,0.62,1.12,1.65,1.23,2.57c0.63,5.03,1.51,10.28,2.23,15.59c0.14,1.03,0.27,2.02,0.41,2.93", type: "㇑", start: [17.14, 71.9], end: [21.01, 92.99], dir: 80, endDir: 81, len: 21.6, num: [9.75, 73.63], part: 1 },
    { n: 6, d: "M19.37,73.6c5.67-0.94,15.47-2.73,20.36-3.48c1.49-0.22,2.39,1.05,2.18,2.08c-0.71,3.44-2.27,9.75-3.23,13.89", type: "㇕b", start: [19.37, 73.6], end: [38.68, 86.09], dir: 33, endDir: 103, len: 38.4, num: [20.25, 70.63], part: 1 },
    { n: 7, d: "M21.47,89.02c3.95-0.45,10.71-1.19,16.28-1.61c1.21-0.09,2.36-0.17,3.41-0.22", type: "㇐b", start: [21.47, 89.02], end: [41.16, 87.19], dir: -5, endDir: -3, len: 19.8, num: [24.75, 85.63], part: 1 },
    { n: 8, d: "M51.79,17.49c1.38,0.26,3.91,0.28,5.27,0.15C63.88,17,72.62,15.62,80,15.32c2.3-0.1,3.67,0.04,4.81,0.15", type: "㇐", start: [51.79, 17.49], end: [84.81, 15.47], dir: -4, endDir: 6, len: 33.2, num: [50.25, 13.63], part: 4 },
    { n: 9, d: "M67.75,20.25c0.37,1.25,0.5,2.38,0.23,3.75c-0.75,3.78-6.03,23.83-7.96,31.58", type: "㇑a", start: [67.75, 20.25], end: [60.02, 55.58], dir: 102, endDir: 104, len: 36.4, num: [74.25, 25.63], part: 3 },
    { n: 10, d: "M52.18,36.96c1.82,0.66,4.17,0.95,5.84,0.66c8.48-1.5,16.13-3.06,22.74-4.1c2.49-0.39,4.05,1.27,3.71,2.93c-0.6,2.93-2.48,11.43-3.74,17.86", type: "㇕c", start: [52.18, 36.96], end: [80.73, 54.31], dir: 31, endDir: 101, len: 52.9, num: [51.75, 34.63], part: 3 },
    { n: 11, d: "M46.33,58.46c1.13,0.24,3.94,0.2,5.07,0.08c12.34-1.29,19.11-2.39,40.88-4.02c1.88-0.14,3.75-0.02,4.69,0.09", type: "㇐", start: [46.33, 58.46], end: [96.97, 54.61], dir: -4, endDir: 7, len: 50.9, num: [47.25, 54.13], part: 5 },
    { n: 12, d: "M52.5,69.88c0.93,0.93,1.42,2.28,1.54,3.31c0.71,6.06,1.42,12.65,2.06,19.3c0.15,1.5,0.28,2.44,0.4,3.75", type: "㇑", start: [52.5, 69.88], end: [56.5, 96.24], dir: 81, endDir: 85, len: 26.9, num: [44.25, 85.63], part: 6 },
    { n: 13, d: "M54.99,71.67c9.47-1.45,23.75-3.41,28.85-3.9c2.14-0.21,3.28,0.98,2.86,2.93c-0.84,3.88-3.08,12.57-4.39,17.58", type: "㇕b", start: [54.99, 71.67], end: [82.31, 88.28], dir: 31, endDir: 105, len: 52.2, num: [56.25, 67.63], part: 6 },
    { n: 14, d: "M57.2,91.49c5.94-0.55,14.67-1.24,23.54-1.76c1.3-0.08,2.63-0.13,3.97-0.2", type: "㇐b", start: [57.2, 91.49], end: [84.71, 89.53], dir: -4, endDir: -3, len: 27.6, num: [60.75, 87.13], part: 6 },
  ],
  parts: [
    { element: "言", position: "left", radical: "general" },
    { element: "口", parent: 0 },
    { element: "吾", position: "right" },
    { element: "五", parent: 2 },
    { element: "二", part: "1", parent: 3 },
    { element: "二", part: "2", parent: 3 },
    { element: "口", parent: 2 },
  ],
};

export default data;
