/*
 * KanjiVG stroke data for 読 (U+8AAD) — release 20260714, source file kanji/08aad.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "読",
  code: "08aad",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M22.38,14.75c2.25,1.63,5.81,6.71,6.37,9.25", type: "㇔", start: [22.38, 14.75], end: [28.75, 24], dir: 55, endDir: 78, len: 11.4, num: [15.5, 15.5], part: 0 },
    { n: 2, d: "M10.37,33.08c1.61,0.48,3.62,0.35,5.27,0.14c5.96-0.76,13.52-1.42,20.1-2.38c1.5-0.22,3.09-0.43,4.6-0.16", type: "㇐", start: [10.37, 33.08], end: [40.34, 30.68], dir: -5, endDir: 10, len: 30.2, num: [3.75, 34.63], part: 0 },
    { n: 3, d: "M16.23,46.31c1.17,0.37,2.73,0.18,3.93-0.01c3.99-0.62,8.33-1.2,11.58-1.97c1.35-0.32,3.26-0.58,4.65-0.58", type: "㇐", start: [16.23, 46.31], end: [36.39, 43.75], dir: -7, endDir: 0, len: 20.4, num: [9.5, 48.13], part: 0 },
    { n: 4, d: "M16.73,58.58c1.02,0.35,2.46,0.15,3.53,0.04c3.8-0.4,9.57-1.17,12.55-1.77c1.45-0.29,2.94-0.48,4.22-0.14", type: "㇐", start: [16.73, 58.58], end: [37.03, 56.71], dir: -5, endDir: 15, len: 20.5, num: [9.5, 61.63], part: 0 },
    { n: 5, d: "M15.64,70.4c0.71,0.61,1.08,1.37,1.12,2.29c0.79,3.76,1.71,9.85,2.52,15.05c0.16,1.05,0.32,2.06,0.48,3", type: "㇑", start: [15.64, 70.4], end: [19.76, 90.74], dir: 79, endDir: 80, len: 20.9, num: [8.5, 76.63], part: 1 },
    { n: 6, d: "M17.75,72.05c6.09-0.91,11.59-1.7,17.42-2.67c1.7-0.28,2.73,1.3,2.49,2.58c-0.85,4.46-1.61,6.91-2.88,12.78", type: "㇕b", start: [17.75, 72.05], end: [34.78, 84.74], dir: 37, endDir: 102, len: 34.9, num: [18.5, 69.5], part: 1 },
    { n: 7, d: "M20.47,88.3c4.06-0.46,7.76-1.19,12.79-1.92c0.92-0.13,1.88-0.26,2.9-0.39", type: "㇐b", start: [20.47, 88.3], end: [36.16, 85.99], dir: -8, endDir: -7, len: 15.9, num: [22.5, 85.5], part: 1 },
    { n: 8, d: "M46.37,26.71c2.31,0.59,4.67,0.42,7,0.15c9.97-1.14,21.82-2.23,29.77-3.06c2.36-0.25,4.38-0.21,6.71,0.14", type: "㇐", start: [46.37, 26.71], end: [89.85, 23.94], dir: -4, endDir: 9, len: 43.7, num: [45.5, 24.5], part: 3 },
    { n: 9, d: "M65.76,13.25c1.06,1.06,1.59,2.08,1.59,3.25c0,8.5-0.07,17.03-0.19,20.46", type: "㇑a", start: [65.76, 13.25], end: [67.16, 36.96], dir: 87, endDir: 92, len: 24.2, num: [58.5, 13.5], part: 3 },
    { n: 10, d: "M52.53,38.58c2.22,0.42,4.15,0.3,5.98,0.08C64,38,71.21,37.1,78,36.47c1.61-0.15,3.63-0.29,5.23,0.04", type: "㇐", start: [52.53, 38.58], end: [83.23, 36.51], dir: -4, endDir: 12, len: 30.9, num: [42.5, 36.5], part: 3 },
    { n: 11, d: "M46.14,48.1c-0.11,3.93-1.7,12-2.6,14.35", type: "㇔", start: [46.14, 48.1], end: [43.54, 62.45], dir: 100, endDir: 111, len: 14.6, num: [37.5, 51.5], part: 5 },
    { n: 12, d: "M47,49.96c11.42-1.27,28-3.71,41.35-4.28c9.15-0.39,0.43,7.14-0.74,8.35", type: "㇖b", start: [47, 49.96], end: [87.61, 54.03], dir: 6, endDir: 134, len: 54.9, num: [46.5, 46.63], part: 5 },
    { n: 13, d: "M59.49,59.25c0.5,1.52,0.71,3.09,0.29,4.83c-2.76,11.61-6.54,22.94-15.26,30.61", type: "㇒", start: [59.49, 59.25], end: [44.52, 94.69], dir: 113, endDir: 139, len: 39.7, num: [49.5, 65.5], part: 7 },
    { n: 14, d: "M71.64,56.26c1.11,1.24,1.65,2.67,1.69,4.37c0.11,4.62-0.13,16.99-0.13,24.62c0,9.5,0.8,10.52,11.3,10.52c11,0,11.38-1.02,11.38-7.31", type: "㇟", start: [71.64, 56.26], end: [95.88, 88.46], dir: 53, endDir: -90, len: 65, num: [76.5, 63.5], part: 6 },
  ],
  parts: [
    { element: "言", position: "left", radical: "general" },
    { element: "口", parent: 0 },
    { element: "売", position: "right" },
    { element: "士", position: "top", parent: 2 },
    { position: "bottom", parent: 2 },
    { element: "冖", parent: 4 },
    { element: "儿", parent: 4 },
    { element: "丿", parent: 6 },
  ],
};

export default data;
