/*
 * KanjiVG stroke data for 買 (U+8CB7) — release 20260714, source file kanji/08cb7.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "買",
  code: "08cb7",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M20.5,14.64c0.49,0.49,1.44,1.59,1.66,2.43c1.09,4.17,1.51,6.88,2.4,11.91c0.2,1.15,0.39,2.26,0.55,3.26", type: "㇑", start: [20.5, 14.64], end: [25.11, 32.24], dir: 75, endDir: 81, len: 18.4, num: [14.5, 22.5], part: 0 },
    { n: 2, d: "M23.25,16.2c15.2-1.38,58.15-3.72,64.01-4.22c2.74-0.23,4.12,1.39,3.32,3.95c-1.08,3.44-1.82,5.56-3.62,10.4c-0.38,1.02-0.87,1.99-1.32,2.94", type: "㇕a", start: [23.25, 16.2], end: [85.64, 29.27], dir: 12, endDir: 115, len: 84.8, num: [24.5, 13.5], part: 0 },
    { n: 3, d: "M43.25,16.5c0.75,0.75,0.68,1.25,0.85,2.27c0.6,3.64,1.21,7.47,1.4,9.23", type: "㇑a", start: [43.25, 16.5], end: [45.5, 28], dir: 79, endDir: 84, len: 11.8, num: [37.5, 24.5], part: 0 },
    { n: 4, d: "M66.25,14.5c0.5,0.75,0.42,2.03,0.29,3.01c-0.54,4.37-0.79,6.62-1.29,9.24", type: "㇑a", start: [66.25, 14.5], end: [65.25, 26.75], dir: 95, endDir: 101, len: 12.4, num: [59.5, 22.5], part: 0 },
    { n: 5, d: "M26.3,30.62c8.83-0.74,51.2-3.49,59.17-3.65", type: "㇐a", start: [26.3, 30.62], end: [85.47, 26.97], dir: -4, endDir: -1, len: 59.3, num: [27.5, 27.5], part: 0 },
    { n: 6, d: "M34.7,38.87c1.09,1.09,1.57,2.82,1.57,4.01c0,1.2,0.07,32.68,0.07,33.28s-0.07,2.47-0.07,3.8", type: "㇑", start: [34.7, 38.87], end: [36.27, 79.96], dir: 88, endDir: 90, len: 41.5, num: [28.5, 47.5], part: 2 },
    { n: 7, d: "M37.02,40.77c8.15-0.63,32.05-3.03,34.84-3.03c2.89,0,4.19,1.26,4.19,3.7c0,2.44-0.08,19.9-0.06,33.08c0,1.35,0.04,2.86,0.04,4.34", type: "㇕a", start: [37.02, 40.77], end: [76.03, 78.86], dir: 44, endDir: 90, len: 78.8, num: [38.5, 39.13], part: 2 },
    { n: 8, d: "M37.53,52.38c5.97-0.26,31.44-2.43,37.25-2.43", type: "㇐a", start: [37.53, 52.38], end: [74.78, 49.95], dir: -4, endDir: 0, len: 37.3, num: [39.5, 49.63], part: 2 },
    { n: 9, d: "M37.5,64.75C46.25,64,65,62.5,74.59,62.1", type: "㇐a", start: [37.5, 64.75], end: [74.59, 62.1], dir: -4, endDir: -2, len: 37.2, num: [39.5, 61.63], part: 2 },
    { n: 10, d: "M37.76,76.86c8.24-0.48,27.49-1.73,36.87-2.04", type: "㇐a", start: [37.76, 76.86], end: [74.63, 74.82], dir: -3, endDir: -2, len: 36.9, num: [39.5, 73.63], part: 2 },
    { n: 11, d: "M43.77,83c0.23,1.5-0.38,2.82-1.5,3.83C38.75,90,30.5,95.5,21.5,99", type: "㇒", start: [43.77, 83], end: [21.5, 99], dir: 144, endDir: 159, len: 28.5, num: [28.5, 88.63], part: 3 },
    { n: 12, d: "M69.84,83.97C75,87.91,80.38,94.38,82.5,98.5", type: "㇔", start: [69.84, 83.97], end: [82.5, 98.5], dir: 49, endDir: 63, len: 19.4, num: [57.5, 87.5], part: 3 },
  ],
  parts: [
    { element: "罒", position: "top", radical: "nelson" },
    { element: "貝", position: "bottom", radical: "tradit" },
    { element: "目", position: "top", parent: 1 },
    { element: "八", position: "bottom", parent: 1 },
  ],
};

export default data;
