/*
 * KanjiVG stroke data for 赤 (U+8D64) — release 20260714, source file kanji/08d64.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "赤",
  code: "08d64",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M30.13,29.42c2.55,0.64,5.18,0.48,7.76,0.15c9.53-1.23,23.14-3.87,31.61-4.52c2.51-0.19,4.9-0.13,7.38,0.25", type: "㇐", start: [30.13, 29.42], end: [76.88, 25.3], dir: -5, endDir: 9, len: 47.1, num: [23.5, 29.5], part: 0 },
    { n: 2, d: "M52.24,12.45c1.53,1.53,2.01,3.55,2.01,5.05c0,3.33,0.04,25.2,0,26.25", type: "㇑a", start: [52.24, 12.45], end: [54.25, 43.75], dir: 86, endDir: 92, len: 31.8, num: [42.5, 12.5], part: 0 },
    { n: 3, d: "M14.38,49.17c2.64,0.58,4.98,0.91,10.12,0.13c18.5-2.8,40.29-6,58.24-7.47c3.33-0.27,6.79-0.66,10.13-0.3", type: "㇐", start: [14.38, 49.17], end: [92.87, 41.53], dir: -6, endDir: 6, len: 79.1, num: [7.5, 49.5], part: 0 },
    { n: 4, d: "M42.78,49.89c0.97,1.23,1.22,3.09,1.2,4.53c-0.22,15.82,0.15,26.07-8.72,37.82", type: "㇒", start: [42.78, 49.89], end: [35.26, 92.24], dir: 100, endDir: 127, len: 44.4, num: [35.5, 57.5], part: 1 },
    { n: 5, d: "M61.02,46.83c1.39,1.39,2.01,2.92,2.01,5.02c0,13.52-0.06,30.44-0.06,35.4c0,12.25-3.71,5.75-6.71,2.75", type: "㇚", start: [61.02, 46.83], end: [56.26, 90], dir: 96, endDir: -135, len: 55.5, num: [54.5, 55.5], part: 1 },
    { n: 6, d: "M28.53,63.89c0.35,1.23,0.25,2.31-0.02,3.18c-1.63,5.43-4.42,9.93-9.26,15.93", type: "㇒", start: [28.53, 63.89], end: [19.25, 83], dir: 116, endDir: 129, len: 21.8, num: [19.5, 64.5], part: 1 },
    { n: 7, d: "M78.77,63.83c3.86,3.92,9.11,12.92,10.98,19.17", type: "㇔", start: [78.77, 63.83], end: [89.75, 83], dir: 60, endDir: 73, len: 22.2, num: [75.5, 59.5], part: 1 },
  ],
  parts: [
    { element: "土", position: "top" },
    { position: "bottom" },
  ],
};

export default data;
