/*
 * KanjiVG stroke data for 走 (U+8D70) — release 20260714, source file kanji/08d70.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "走",
  code: "08d70",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M30.13,28.92c1.62,0.38,4.6,0.57,6.21,0.38C47.25,28,60.75,26,70.08,25.16c2.69-0.24,4.32,0.18,5.67,0.37", type: "㇐", start: [30.13, 28.92], end: [75.75, 25.53], dir: -4, endDir: 8, len: 45.9, num: [23.5, 30.5], part: 0 },
    { n: 2, d: "M52.01,12.37c1.25,1.25,2.05,2.85,2.05,5.01c0,4.58-0.06,25.5-0.06,26.37", type: "㇑a", start: [52.01, 12.37], end: [54, 43.75], dir: 86, endDir: 90, len: 31.9, num: [42.5, 13.5], part: 0 },
    { n: 3, d: "M15.13,48.05c2.29,0.69,6.48,0.95,8.77,0.69c24.84-2.74,36-4.24,60.98-6.45c3.79-0.33,6.35,0.08,8.25,0.43", type: "㇐", start: [15.13, 48.05], end: [93.13, 42.72], dir: -4, endDir: 10, len: 78.5, num: [8.5, 50.5], part: 0 },
    { n: 4, d: "M53.12,49c1.13,1.13,1.78,3.13,1.78,4.75c0,6.38-0.15,21.5-0.15,27", type: "㇑a", start: [53.12, 49], end: [54.75, 80.75], dir: 87, endDir: 90, len: 32.2, num: [47.5, 57.13], part: 1 },
    { n: 5, d: "M56.5,63.5c7.75-1,15.25-2.09,17.84-2.09c1.57,0,2.5,0.18,3.29,0.37", type: "㇐c", start: [56.5, 63.5], end: [77.63, 61.78], dir: -5, endDir: 14, len: 21.3, num: [59.5, 60.5], part: 1 },
    { n: 6, d: "M36.75,60.25c0.11,1.43-0.01,2.77-0.41,4.15c-2.01,6.95-8.97,19.48-20.84,28.1", type: "㇒", start: [36.75, 60.25], end: [15.5, 92.5], dir: 123, endDir: 144, len: 39.7, num: [28.5, 62.5], part: 1 },
    { n: 7, d: "M33.75,73.5c10.2,2.44,40.07,16.59,49.72,18.89C86.44,93.1,90.1,93.73,93,94", type: "㇏", start: [33.75, 73.5], end: [93, 94], dir: 19, endDir: 5, len: 62.9, num: [40.5, 72.5], part: 1 },
  ],
  parts: [
    { element: "土", position: "top" },
    { element: "龰", position: "bottom" },
  ],
};

export default data;
