/*
 * KanjiVG stroke data for 足 (U+8DB3) — release 20260714, source file kanji/08db3.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "足",
  code: "08db3",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M29.75,18.99c0.82,0.82,1.43,1.68,1.66,2.33c1.15,3.39,3.44,13.48,4.61,18.68c0.34,1.51,0.59,2.61,0.68,3", type: "㇑", start: [29.75, 18.99], end: [36.7, 43], dir: 74, endDir: 77, len: 25.2, num: [22.5, 25.5], part: 0 },
    { n: 2, d: "M31.56,19.63c12.09-1.87,34.1-5.01,40.27-5.14c2.89-0.06,3.98,2.41,3.7,3.88c-0.73,3.84-3.94,15.23-4.51,17.27", type: "㇕b", start: [31.56, 19.63], end: [71.02, 35.64], dir: 22, endDir: 106, len: 64.6, num: [32.5, 15.5], part: 0 },
    { n: 3, d: "M37.25,40.74c7.07-0.43,20.75-2.48,31.53-3.73c1.71-0.2,3.34-0.14,4.86-0.32", type: "㇐b", start: [37.25, 40.74], end: [73.64, 36.69], dir: -6, endDir: -7, len: 36.6, num: [39.5, 36.5], part: 0 },
    { n: 4, d: "M52.75,41c0.81,0.81,1.4,1.75,1.4,3.62c0,5.11,0.37,32.49,0.35,33.88", type: "㇑a", start: [52.75, 41], end: [54.5, 78.5], dir: 87, endDir: 91, len: 37.9, num: [46.5, 49.5], part: 1 },
    { n: 5, d: "M55.75,59.25C56.94,59.25,66.25,57.75,73.54,56.53C75.08,56.27,76.53,56.25,77.75,56.25", type: "㇐b", start: [55.75, 59.25], end: [77.75, 56.25], dir: -8, endDir: 0, len: 22.2, num: [57.5, 55.5], part: 1 },
    { n: 6, d: "M36.49,55c0.13,1.5,0.14,3.05-0.2,4.35c-2.04,7.78-10.16,24.15-17.79,30.9", type: "㇒", start: [36.49, 55], end: [18.5, 90.25], dir: 117, endDir: 139, len: 40.4, num: [27.5, 55.5], part: 1 },
    { n: 7, d: "M33.25,70.75C41.75,72.12,67,87.38,82,92.5c2.94,1,6.85,1.68,9.75,2", type: "㇏", start: [33.25, 70.75], end: [91.75, 94.5], dir: 22, endDir: 6, len: 63.4, num: [35.25, 81.5], part: 1 },
  ],
  parts: [
    { element: "口", position: "top" },
    { element: "龰", position: "bottom" },
  ],
};

export default data;
