/*
 * KanjiVG stroke data for 車 (U+8ECA) — release 20260714, source file kanji/08eca.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "車",
  code: "08eca",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M26,26c2.85,0.69,6.1,0.14,8.98-0.1c11.09-0.93,25.8-2.64,38.89-3.51c2.68-0.18,5.22-0.16,7.88,0.23", type: "㇐", start: [26, 26], end: [81.75, 22.62], dir: -3, endDir: 8, len: 56, num: [17.25, 26.5] },
    { n: 2, d: "M27.5,37.92c0.81,0.5,1.83,2.39,1.98,3.05c0.85,3.73,1.83,11.31,2.95,18.54c0.32,2.09,0.41,3.2,0.75,5.24", type: "㇑", start: [27.5, 37.92], end: [33.18, 64.75], dir: 78, endDir: 81, len: 27.8, num: [20.25, 45.13] },
    { n: 3, d: "M30.36,39.49c14.52-1.61,36.14-4.11,47.63-4.5c3.46-0.12,4.17,1.57,4.03,3.08c-0.42,4.32-2.01,13.81-3.5,20.19c-0.21,0.89-0.51,1.87-0.76,3", type: "㇕a", start: [30.36, 39.49], end: [77.76, 61.26], dir: 25, endDir: 102, len: 77.4, num: [33, 36.28] },
    { n: 4, d: "M32.5,51.25c13.75-1.5,34.25-3.75,47-4.25", type: "㇐a", start: [32.5, 51.25], end: [79.5, 47], dir: -5, endDir: -2, len: 47.2, num: [35.5, 48.13] },
    { n: 5, d: "M34.25,63.25C46,61.62,65,59.75,77,59.25", type: "㇐a", start: [34.25, 63.25], end: [77, 59.25], dir: -5, endDir: -2, len: 42.9, num: [35.5, 60.13] },
    { n: 6, d: "M16,77.86c3.62,0.89,7.38,0.77,10.63,0.39c18.51-2.14,39.85-4.55,57.12-5.45c3.05-0.16,6.5-0.05,9.5,0.63", type: "㇐", start: [16, 77.86], end: [93.25, 73.43], dir: -3, endDir: 13, len: 77.6, num: [6.75, 80.5] },
    { n: 7, d: "M52.5,11.51c1.36,1.36,2.06,2.78,2.14,6.02c0.03,1.07-0.07,48.79-0.19,70.7c-0.02,4.27-0.05,7.36-0.07,8.65", type: "㇑", start: [52.5, 11.51], end: [54.38, 96.88], dir: 89, endDir: 91, len: 85.9, num: [43.5, 11.5] },
  ],
  parts: [

  ],
};

export default data;
