/*
 * KanjiVG stroke data for 転 (U+8EE2) — release 20260714, source file kanji/08ee2.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "転",
  code: "08ee2",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M15.87,27.09c1.26,0.28,2.75,0.29,3.74,0.22C26,26.88,37.25,25,45.34,23.42c1.61-0.31,2.6-0.18,3.42-0.02", type: "㇐", start: [15.87, 27.09], end: [48.76, 23.4], dir: -6, endDir: 11, len: 33.2, num: [9.75, 28.63], part: 0 },
    { n: 2, d: "M15.2,39.78c0.76,0.76,1.42,1.84,1.58,2.86c0.6,3.83,1.38,11.25,2.25,18.6c0.13,1.09,0.26,2.18,0.39,3.26", type: "㇑", start: [15.2, 39.78], end: [19.42, 64.5], dir: 80, endDir: 83, len: 25.3, num: [9.75, 48.13], part: 0 },
    { n: 3, d: "M17.29,40.85c11.46-2.35,21.96-4.6,29.91-5.61c3.12-0.4,3.8,2.07,3.7,3.46c-0.29,4.07-0.77,8.65-1.9,15.16c-0.2,1.17-0.41,2.39-0.62,3.69", type: "㇕a", start: [17.29, 40.85], end: [48.38, 57.55], dir: 28, endDir: 99, len: 55.4, num: [17.5, 37.63], part: 0 },
    { n: 4, d: "M18.97,50.81c11.28-2.56,19.28-3.81,29.82-5.1", type: "㇐a", start: [18.97, 50.81], end: [48.79, 45.71], dir: -10, endDir: -7, len: 30.3, num: [21.75, 47.5], part: 0 },
    { n: 5, d: "M20.22,61.37C30.25,59.5,37,58.25,47.62,56.88", type: "㇐a", start: [20.22, 61.37], end: [47.62, 56.88], dir: -9, endDir: -7, len: 27.8, num: [21.5, 58.63], part: 0 },
    { n: 6, d: "M12.75,76.05c1.75,0.7,4.36,0.61,6.37,0.16c7.9-1.78,18.7-4.06,26.38-5.16c2.31-0.33,4.88-0.42,6.75,0.12", type: "㇐", start: [12.75, 76.05], end: [52.25, 71.17], dir: -7, endDir: 16, len: 40.1, num: [5.25, 78.16], part: 0 },
    { n: 7, d: "M31.66,12.7c1.19,1.19,1.68,2.56,1.68,3.73c0,2.23-0.05,55.54-0.13,74.32c-0.01,2.84-0.02,4.89-0.04,5.86", type: "㇑", start: [31.66, 12.7], end: [33.17, 96.61], dir: 89, endDir: 91, len: 84.4, num: [25.5, 12.5], part: 0 },
    { n: 8, d: "M57.99,25.62c1.76,0.38,4.02,0.2,5.11,0.07c7.03-0.81,17.13-2.38,22.96-2.93c1.44-0.14,3.44-0.26,4.95,0.06", type: "㇐", start: [57.99, 25.62], end: [91.01, 22.82], dir: -5, endDir: 12, len: 33.2, num: [56.25, 22.63], part: 2 },
    { n: 9, d: "M56.5,50.17c1.86,0.33,3.72,0.28,5.25,0.13c8.61-0.8,21.18-2.8,29.81-3.4c1.53-0.11,3.65-0.03,4.94,0.37", type: "㇐", start: [56.5, 50.17], end: [96.5, 47.27], dir: -4, endDir: 17, len: 40.3, num: [56.5, 47.5], part: 2 },
    { n: 10, d: "M74.17,52.46c0.25,1.2,0.08,2.52-0.46,3.97c-3.96,10.74-9.3,20.01-15.11,29.99c-1.58,2.71-0.7,3.97,1.78,3.42c5.22-1.15,18.37-4.34,30.13-7.26", type: "㇜", start: [74.17, 52.46], end: [90.51, 82.58], dir: 62, endDir: -14, len: 74.4, num: [61.5, 60.5], part: 3 },
    { n: 11, d: "M82.63,70.83c4.69,3.52,11.49,14.4,12.66,19.89", type: "㇔", start: [82.63, 70.83], end: [95.29, 90.72], dir: 58, endDir: 78, len: 23.9, num: [81.5, 68.5], part: 3 },
  ],
  parts: [
    { element: "車", position: "left", radical: "general" },
    { element: "云", position: "right" },
    { element: "二", position: "top", parent: 1 },
    { element: "厶", position: "bottom", parent: 1 },
  ],
};

export default data;
