/*
 * KanjiVG stroke data for 近 (U+8FD1) — release 20260714, source file kanji/08fd1.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "近",
  code: "08fd1",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M77.75,13.25c-0.25,1.5-1.74,2.71-2.86,3.4C70.25,19.5,62.5,23,51.81,26.72", type: "㇒", start: [77.75, 13.25], end: [51.81, 26.72], dir: 153, endDir: 161, len: 29.8, num: [80.25, 9.13], part: 0 },
    { n: 2, d: "M48.54,25.5c0.96,1.25,1.45,2.93,1.45,4.56c0,18.44,0.14,31.94-9.18,44.15", type: "㇒", start: [48.54, 25.5], end: [40.81, 74.21], dir: 99, endDir: 127, len: 50.9, num: [41.25, 34.63], part: 0 },
    { n: 3, d: "M52.75,40.9c0.58,0.12,3.06,0.31,4.6,0.12C65.62,40,78.72,37.99,87.9,37.2c1.54-0.13,4.25-0.12,5.22,0", type: "㇐", start: [52.75, 40.9], end: [93.12, 37.2], dir: -5, endDir: 7, len: 40.6, num: [56.25, 37.63], part: 0 },
    { n: 4, d: "M72.87,41.75c1.19,1.19,1.71,2.38,1.71,3.75c0,2.08-0.07,22.38-0.09,35c0,1.75,0,3.36,0,4.75", type: "㇑", start: [72.87, 41.75], end: [74.49, 85.25], dir: 88, endDir: 90, len: 44, num: [65.25, 51.13], part: 0 },
    { n: 5, d: "M20.96,19.25c3.63,1.74,9.38,7.17,10.29,9.88", type: "㇔", start: [20.96, 19.25], end: [31.25, 29.13], dir: 44, endDir: 71, len: 14.5, num: [9.75, 21.13], part: 1 },
    { n: 6, d: "M13.11,50.5c2.25,1,3.75,0.5,4.75,0.25S26.61,47.5,28.11,47c3-1,4.83,0.21,1.75,4.75c-6.11,9-5.86,9.25,0.25,15.5c3.04,3.11,1.64,4.5-0.75,6.5c-1.5,1.25-8.5,7.25-10,7.75", type: "㇋", start: [13.11, 50.5], end: [19.36, 81.5], dir: 79, endDir: 162, len: 63.1, num: [3.75, 52.63], part: 1 },
    { n: 7, d: "M15.25,83c3-0.5,9-1.75,13.5-0.75s30.07,7.71,34.5,9c12,3.5,21.25,4.5,30.25,2.75", type: "㇏a", start: [15.25, 83], end: [93.5, 94], dir: 8, endDir: -11, len: 79.9, num: [6.75, 85.63], part: 1 },
  ],
  parts: [
    { element: "斤", position: "nyoc" },
    { element: "⻌", position: "nyo", radical: "general" },
  ],
};

export default data;
