/*
 * KanjiVG stroke data for 週 (U+9031) — release 20260714, source file kanji/09031.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "週",
  code: "09031",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M45.93,17.66c1.02,1.02,1.67,2.55,1.67,4.3c0,21.04,2.53,45.54-8.1,58.79", type: "㇒/㇑", start: [45.93, 17.66], end: [39.5, 80.75], dir: 96, endDir: 129, len: 65.1, num: [39.75, 28.63], part: 1 },
    { n: 2, d: "M48.49,18.95c9.79-1.25,32.29-4.39,33.41-4.45c4.34-0.24,5.42,1.26,5.42,5.64c0,1.93,0.17,52.16,0.17,56.6c0,9.53-5.28,4.86-8.4,1.69", type: "㇆a", start: [48.49, 18.95], end: [79.09, 78.43], dir: 63, endDir: -135, len: 113.8, num: [53.25, 13.63], part: 1 },
    { n: 3, d: "M55.43,31.42c0.83,0.25,2.88,0.54,3.72,0.51c4.54-0.18,13.51-1.92,16.84-2.23c1.39-0.13,2.22-0.07,2.91,0.03", type: "㇐", start: [55.43, 31.42], end: [78.9, 29.73], dir: -4, endDir: 8, len: 23.7, num: [54.75, 28.63], part: 3 },
    { n: 4, d: "M65.84,22.3c0.99,0.99,1.51,2.32,1.51,3.39c0,3.19-0.07,10.44-0.07,16.81", type: "㇑a", start: [65.84, 22.3], end: [67.28, 42.5], dir: 86, endDir: 90, len: 20.6, num: [69.75, 24.13], part: 3 },
    { n: 5, d: "M53.61,44.53c1,0.35,2.64,0.41,4.31,0.23C65,44,70.38,43.38,77.01,42.4c1.84-0.27,3.25-0.4,4.81-0.26", type: "㇐", start: [53.61, 44.53], end: [81.82, 42.14], dir: -5, endDir: 5, len: 28.4, num: [51.75, 40.63], part: 3 },
    { n: 6, d: "M56.17,53.75c1.08,0.75,1.6,2.01,1.71,2.97c0.5,4.53,1.05,6.63,1.48,10.27c0.17,1.46,0.3,2.58,0.34,2.94", type: "㇑", start: [56.17, 53.75], end: [59.7, 69.93], dir: 78, endDir: 84, len: 16.9, num: [50.25, 66.13], part: 4 },
    { n: 7, d: "M58.6,55.4c5.86-1.39,13.69-2.83,16.29-3.02c1.73-0.13,2.48,1,2.28,2.58c-0.38,2.92-1.34,5.94-2.12,9.61", type: "㇕b", start: [58.6, 55.4], end: [75.05, 64.57], dir: 29, endDir: 102, len: 30.5, num: [60.75, 54.13], part: 4 },
    { n: 8, d: "M60.65,67.64c2.32-0.44,8.3-1.1,13.1-1.63c1.43-0.16,2.69-0.28,3.61-0.34", type: "㇐b", start: [60.65, 67.64], end: [77.36, 65.67], dir: -7, endDir: -4, len: 16.8, num: [62.25, 64.63], part: 4 },
    { n: 9, d: "M20.71,19c3.1,1.41,8.02,5.8,8.79,8", type: "㇔", start: [20.71, 19], end: [29.5, 27], dir: 42, endDir: 71, len: 12.1, num: [11.25, 16.63], part: 5 },
    { n: 10, d: "M13.25,54.95c2.25,0.92,4.29,0.84,5.25,0.48c2.5-0.93,8.31-4.06,9.75-4.68c2.88-1.24,4.14,0.9,1.5,3.78c-6.38,6.98-6,8.23-0.75,14.1c1.83,2.04,2.03,3.44-1.5,6.12c-5.25,4-7.5,5.75-10.75,8.5", type: "㇋", start: [13.25, 54.95], end: [16.75, 83.25], dir: 83, endDir: 140, len: 61.4, num: [0.75, 52.63], part: 5 },
    { n: 11, d: "M13.75,85.75c4.12-0.88,10.41-0.97,15-0.5c7.25,0.75,29.97,5.13,34.5,6c13,2.5,21.25,4.5,30.25,2.75", type: "㇏a", start: [13.75, 85.75], end: [93.5, 94], dir: 6, endDir: -11, len: 80.7, num: [2.25, 85.63], part: 5 },
  ],
  parts: [
    { element: "周", position: "nyoc" },
    { element: "冂", parent: 0 },
    { element: "吉", parent: 0 },
    { element: "士", parent: 2 },
    { element: "口", parent: 2 },
    { element: "⻌", position: "nyo", radical: "general" },
  ],
};

export default data;
