/*
 * KanjiVG stroke data for 道 (U+9053) — release 20260714, source file kanji/09053.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "道",
  code: "09053",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M49.38,14.88c2.61,1.78,6.73,7.3,7.38,10.06", type: "㇔", start: [49.38, 14.88], end: [56.76, 24.94], dir: 54, endDir: 77, len: 12.6, num: [42.5, 15.5], part: 0 },
    { n: 2, d: "M77.25,12.5c0.06,0.84-0.03,1.66-0.37,2.42c-1.38,3.08-3.38,6.7-6.63,10.2", type: "㇒", start: [77.25, 12.5], end: [70.25, 25.12], dir: 119, endDir: 133, len: 14.7, num: [69.5, 13.5], part: 0 },
    { n: 3, d: "M42.06,32.6c1.75,0.45,4.97,0.38,6.7,0.2c9.99-1.05,25.86-2.93,36.82-3.2c2.91-0.07,4.8,0.15,6.12,0.44", type: "㇐", start: [42.06, 32.6], end: [91.7, 30.04], dir: -3, endDir: 12, len: 49.8, num: [35.25, 33.13], part: 0 },
    { n: 4, d: "M64.26,33.62c0.25,0.1-0.23,1.75-0.39,2.04c-1.03,1.93-2.08,4.55-4.5,7.09", type: "㇒", start: [64.26, 33.62], end: [59.37, 42.75], dir: 118, endDir: 134, len: 10.6, num: [68.25, 39.13], part: 1 },
    { n: 5, d: "M51.06,43.52c0.77,0.77,1.13,1.71,1.13,2.82c0,0.9-0.1,22.98-0.06,31.9c0.01,2.08,0.03,3.45,0.06,3.66", type: "㇑", start: [51.06, 43.52], end: [52.19, 81.9], dir: 88, endDir: 82, len: 38.7, num: [44.5, 52.63], part: 2 },
    { n: 6, d: "M53.01,45.09c6.24-0.71,22.66-2.75,24.6-2.88c1.96-0.14,3.35,0.55,3.35,2.81c0,1.08-0.57,23.4-0.8,32.24c-0.05,2-0.09,3.28-0.12,3.43", type: "㇕a", start: [53.01, 45.09], end: [80.04, 80.69], dir: 53, endDir: 101, len: 65.6, num: [51.5, 42.13], part: 2 },
    { n: 7, d: "M52.9,55.9c6.1-0.4,20.85-2.15,26.64-2.34", type: "㇐a", start: [52.9, 55.9], end: [79.54, 53.56], dir: -5, endDir: -2, len: 26.7, num: [56.5, 54.13], part: 2 },
    { n: 8, d: "M53.11,67.65c6.85-0.47,19.47-1.75,26.13-1.75", type: "㇐a", start: [53.11, 67.65], end: [79.24, 65.9], dir: -4, endDir: 0, len: 26.2, num: [56.46, 64.63], part: 2 },
    { n: 9, d: "M53.36,79.25c5.14,0,18.66-1.07,25.31-1.07", type: "㇐a", start: [53.36, 79.25], end: [78.67, 78.18], dir: -2, endDir: 0, len: 25.3, num: [56.46, 76.63], part: 2 },
    { n: 10, d: "M19.75,20c3.38,1.75,8,6.12,9.5,8.75", type: "㇔", start: [19.75, 20], end: [29.25, 28.75], dir: 43, endDir: 60, len: 13, num: [8.5, 20.5], part: 3 },
    { n: 11, d: "M13,51.53c2.25,0.86,3.75,0.43,4.75,0.22s9-3.47,10.5-3.9c2.96-0.85,4.22,0.21,2.44,3.03c-6.56,10.38-6.81,8.5-0.11,14.4c2.39,2.1,2.15,3.52-0.57,5.48C25.5,74,21.75,76.25,17.5,79.04", type: "㇋", start: [13, 51.53], end: [17.5, 79.04], dir: 81, endDir: 147, len: 62.1, num: [3.5, 53.5], part: 3 },
    { n: 12, d: "M12.5,81.71c3.11-0.47,9.22-0.87,13.97-0.71c7.15,0.25,31.13,8.25,35.71,9.46C74.61,93.76,81.62,95.5,91,96.05", type: "㇏a", start: [12.5, 81.71], end: [91, 96.05], dir: 10, endDir: 3, len: 80.4, num: [3.5, 84.13], part: 3 },
  ],
  parts: [
    { element: "首", position: "nyoc" },
    { element: "自", parent: 0 },
    { element: "目", parent: 1 },
    { element: "⻌", position: "nyo", radical: "general" },
  ],
};

export default data;
