/*
 * KanjiVG stroke data for 金 (U+91D1) — release 20260714, source file kanji/091d1.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "金",
  code: "091d1",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M51.75,11.88c0.25,1.52-0.22,3.57-0.8,4.84C47.73,23.79,33.13,47.1,14.5,58", type: "㇒", start: [51.75, 11.88], end: [14.5, 58], dir: 129, endDir: 150, len: 60.7, num: [43.25, 13.13], part: 0 },
    { n: 2, d: "M52.25,18.25c9.5,7.5,34.14,30.88,37.21,32.67c3.12,1.82,4.14,2.66,5.54,2.83", type: "㇏", start: [52.25, 18.25], end: [95, 53.75], dir: 40, endDir: 7, len: 55.8, num: [60.5, 21.5], part: 0 },
    { n: 3, d: "M34.02,47.08c1.69,0.65,3.85,0.36,5.6,0.21c6.91-0.6,14.33-1.69,23.99-2.64c2.07-0.2,4.1-0.4,6.15,0.12", type: "㇐", start: [34.02, 47.08], end: [69.76, 44.77], dir: -4, endDir: 14, len: 36, num: [42.5, 43.5], part: 2 },
    { n: 4, d: "M30.18,64.96c1.95,0.67,4.47,0.31,6.47,0.12c9.24-0.87,17.42-1.58,31.35-2.53c2.3-0.16,4.68-0.36,6.96,0.08", type: "㇐", start: [30.18, 64.96], end: [74.96, 62.63], dir: -3, endDir: 11, len: 45, num: [21.5, 66.5], part: 2 },
    { n: 5, d: "M51.47,48.82c0.89,0.85,0.89,3.76,0.89,4.43c0,3.64,0.27,38.71,0.22,39.82", type: "㇑a", start: [51.47, 48.82], end: [52.58, 93.07], dir: 89, endDir: 93, len: 44.4, num: [56.5, 54.5], part: 1 },
    { n: 6, d: "M31,74.75c3.25,3,7.48,9.27,8.5,12", type: "㇔", start: [31, 74.75], end: [39.5, 86.75], dir: 55, endDir: 70, len: 14.8, num: [23.5, 78.5], part: 1 },
    { n: 7, d: "M73.01,72.11c0.24,1.14,0.11,2.46-0.54,3.51C70.38,79,66.44,83.22,63,86", type: "㇒", start: [73.01, 72.11], end: [63, 86], dir: 126, endDir: 141, len: 17.7, num: [78.5, 74.5], part: 1 },
    { n: 8, d: "M18.5,94.86c2.88,1.01,6.41,0.4,9.37,0.15c16.55-1.42,32.95-2.12,51.51-3c3.13-0.15,6.32-0.27,9.38,0.59", type: "㇐", start: [18.5, 94.86], end: [88.76, 92.6], dir: -2, endDir: 16, len: 70.5, num: [10.5, 96.5], part: 1 },
  ],
  parts: [
    { position: "top" },
    { position: "bottom" },
    { parent: 1 },
  ],
};

export default data;
