/*
 * KanjiVG stroke data for 長 (U+9577) — release 20260714, source file kanji/09577.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "長",
  code: "09577",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M34,14.75C35.25,16,36,18,36,19.5s0,33.5,0,35.75", type: "㇑a", start: [34, 14.75], end: [36, 55.25], dir: 87, endDir: 90, len: 41, num: [29.25, 24.13] },
    { n: 2, d: "M37.75,16c9.6-0.15,21.73-3.26,26.63-4.2c1.97-0.38,3.9-0.41,5.87,0.06", type: "㇐b", start: [37.75, 16], end: [70.25, 11.86], dir: -7, endDir: 13, len: 32.9, num: [37.5, 12.5] },
    { n: 3, d: "M37.25,29.5C48.12,28.25,57,27,64,25.72c1.96-0.36,3.76-0.25,5.25,0.06", type: "㇐b", start: [37.25, 29.5], end: [69.25, 25.78], dir: -7, endDir: 12, len: 32.3, num: [40.5, 25.63] },
    { n: 4, d: "M37.5,42.5c8.88-0.86,21.62-2.62,26.75-3.53c1.97-0.35,3.88-0.32,5.75,0", type: "㇐b", start: [37.5, 42.5], end: [70, 38.97], dir: -6, endDir: 10, len: 32.8, num: [40.5, 39.13] },
    { n: 5, d: "M10.88,58.23c3.14,0.86,6.44,0.68,9.62,0.29c19.73-2.35,44.86-6.1,65-7.61c2.97-0.22,5.7-0.08,8.63,0.4", type: "㇐", start: [10.88, 58.23], end: [94.13, 51.31], dir: -5, endDir: 9, len: 83.8, num: [3.75, 59.5] },
    { n: 6, d: "M31.25,60.25c0.94,0.94,1.39,2.38,1.39,4c0,11.82-0.7,28.19-0.7,30.19s1.65,3.14,3.74,1.64c2.09-1.5,17.25-11.09,20.03-12.59", type: "㇙", start: [31.25, 60.25], end: [55.71, 83.49], dir: 44, endDir: -28, len: 63.6, num: [25.5, 69.5] },
    { n: 7, d: "M76.52,55.25c0.23,1.25-0.33,2.45-1.05,3.41C73.5,61.25,69.62,65,64.62,68.75", type: "㇒", start: [76.52, 55.25], end: [64.62, 68.75], dir: 131, endDir: 143, len: 18.5, num: [81.5, 61.5] },
    { n: 8, d: "M46.5,62.25c8.21,0,34.52,25.9,44.28,29.5C93.12,92.61,94.51,93,97,93.5", type: "㇏", start: [46.5, 62.25], end: [97, 93.5], dir: 32, endDir: 11, len: 60, num: [43.5, 71.5] },
  ],
  parts: [

  ],
};

export default data;
