/*
 * KanjiVG stroke data for 間 (U+9593) — release 20260714, source file kanji/09593.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "間",
  code: "09593",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M18.64,15.3c0.71,0.71,1.18,1.82,1.18,3.43c0,3.89-0.05,56.65-0.19,72.77c-0.02,1.92-0.03,4.03-0.05,4.65", type: "㇑", start: [18.64, 15.3], end: [19.58, 96.15], dir: 89, endDir: 92, len: 81.1, num: [12.75, 23.5], part: 1 },
    { n: 2, d: "M21.01,16.81c5.75-0.6,18.73-2.74,20.5-2.84c1.85-0.1,2.86,0.28,2.9,2.02c0.06,2.75-0.5,16.1-0.85,20.76c-0.12,1.55-0.19,2.57-0.19,2.7", type: "㇕a", start: [21.01, 16.81], end: [43.37, 39.45], dir: 45, endDir: 90, len: 48.3, num: [21.75, 13.63], part: 1 },
    { n: 3, d: "M20.95,27.27c5.99-0.61,14.92-2.02,21.88-2.6", type: "㇐a", start: [20.95, 27.27], end: [42.83, 24.67], dir: -7, endDir: -5, len: 22, num: [24.75, 24.5], part: 1 },
    { n: 4, d: "M21.02,39.04c8.11-1.19,14.14-2.1,21.31-2.64", type: "㇐a", start: [21.02, 39.04], end: [42.33, 36.4], dir: -7, endDir: -4, len: 21.5, num: [24.75, 35.5], part: 1 },
    { n: 5, d: "M63.19,13.1c0.98,0.98,1.34,2.15,1.34,2.97c0,5.8-0.08,12.65-0.06,18.93c0.01,2.01,0.02,3.4,0.06,3.58", type: "㇑", start: [63.19, 13.1], end: [64.53, 38.58], dir: 87, endDir: 77, len: 25.9, num: [56.5, 21.5], part: 2 },
    { n: 6, d: "M65.32,14.77c5.97-0.68,20.69-3.19,22.38-3.28c1.8-0.09,2.81,0.88,2.81,2.82c0,17-0.22,66.12-0.22,78.44c0,10.5-6.35,1.36-7.72,0.23", type: "㇆a", start: [65.32, 14.77], end: [82.57, 92.98], dir: 78, endDir: -140, len: 119.1, num: [65.25, 11.5], part: 2 },
    { n: 7, d: "M65.63,24.79c4.49-0.42,19.73-1.99,23.35-1.99", type: "㇐a", start: [65.63, 24.79], end: [88.98, 22.8], dir: -5, endDir: 0, len: 23.4, num: [68.54, 22.5], part: 2 },
    { n: 8, d: "M65.22,36.07c6.41-0.32,16.53-1.32,23.49-1.81", type: "㇐a", start: [65.22, 36.07], end: [88.71, 34.26], dir: -4, endDir: -4, len: 23.6, num: [68.5, 33.5], part: 2 },
    { n: 9, d: "M40.56,50.95c0.74,0.74,1.04,1.93,1.04,2.99c0,0.83-0.08,20.84-0.05,29.06c0.01,2.25,0.02,2.77,0.05,3", type: "㇑", start: [40.56, 50.95], end: [41.6, 86], dir: 88, endDir: 83, len: 35.3, num: [34.5, 57.5], part: 3 },
    { n: 10, d: "M42.26,52.09c5.56-0.48,19.71-1.98,21.3-2.1c1.68-0.13,2.76,1.46,2.63,2.24c-0.21,1.24-0.41,20.66-0.48,29.02c-0.02,2.29-0.03,3.8-0.03,3.97", type: "㇕a", start: [42.26, 52.09], end: [65.68, 85.22], dir: 55, endDir: 90, len: 58.3, num: [42.75, 48.5], part: 3 },
    { n: 11, d: "M42.64,66.6c5.11-0.48,17.36-1.73,21.88-2.07", type: "㇐a", start: [42.64, 66.6], end: [64.52, 64.53], dir: -5, endDir: -4, len: 22, num: [44.5, 63.5], part: 3 },
    { n: 12, d: "M42.25,82.8c5.13-0.3,17-1.55,22.26-2.05", type: "㇐a", start: [42.25, 82.8], end: [64.51, 80.75], dir: -5, endDir: -5, len: 22.4, num: [44.31, 79.5], part: 3 },
  ],
  parts: [
    { element: "門", position: "kamae", radical: "general" },
    { position: "left", parent: 0 },
    { position: "right", parent: 0 },
    { element: "日" },
  ],
};

export default data;
