/*
 * KanjiVG stroke data for 雨 (U+96E8) — release 20260714, source file kanji/096e8.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "雨",
  code: "096e8",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M25.75,22.37c1.87,0.4,4.47,0.62,6.32,0.4c11.68-1.39,28.28-3.77,41.25-4.64c2.49-0.17,4.37-0.12,7.18,0.28", type: "㇐", start: [25.75, 22.37], end: [80.5, 18.41], dir: -4, endDir: 8, len: 55.1, num: [18.75, 22.63] },
    { n: 2, d: "M15.5,41.25c1.25,1.5,1.66,3.26,1.89,5.19c1.24,10.69,2.19,26.61,2.66,36.31c0.13,2.7,0.2,5,0.2,6", type: "㇑", start: [15.5, 41.25], end: [20.25, 88.75], dir: 84, endDir: 90, len: 48, num: [9.5, 48.5] },
    { n: 3, d: "M18.25,44.25c1.42-0.09,62.76-5.33,69.5-6c2.5-0.25,4.61,1,4.5,3.75c-0.5,12.75-1.77,28.11-6,44.75c-1.88,7.38-5.38,1.88-8.5-1.25", type: "㇆a", start: [18.25, 44.25], end: [77.75, 85.5], dir: 35, endDir: -135, len: 134.4, num: [21.5, 40.5] },
    { n: 4, d: "M52.25,23.5C53.31,24.56,54,26.25,54,28c0,0.82-0.25,37.8-0.43,53c-0.04,3.43-0.07,5.74-0.07,6.25", type: "㇑", start: [52.25, 23.5], end: [53.5, 87.25], dir: 89, endDir: 90, len: 64.2, num: [45.5, 31.25] },
    { n: 5, d: "M31,53.5c4.21,1.24,8.95,3.94,11.25,6", type: "㇔", start: [31, 53.5], end: [42.25, 59.5], dir: 28, endDir: 42, len: 12.8, num: [23.25, 56.25] },
    { n: 6, d: "M30.5,68.75c3.8,1.26,9.68,5.89,11.75,8", type: "㇔", start: [30.5, 68.75], end: [42.25, 76.75], dir: 34, endDir: 46, len: 14.3, num: [23, 70.75] },
    { n: 7, d: "M66.88,48.88c4.98,1.99,10.63,5.97,12.62,7.62", type: "㇔", start: [66.88, 48.88], end: [79.5, 56.5], dir: 31, endDir: 40, len: 14.8, num: [59, 51.5] },
    { n: 8, d: "M67.25,66.5c2.75,1,9,5.5,11,7.75", type: "㇔", start: [67.25, 66.5], end: [78.25, 74.25], dir: 35, endDir: 48, len: 13.5, num: [58.5, 66.25] },
  ],
  parts: [

  ],
};

export default data;
