/*
 * KanjiVG stroke data for 電 (U+96FB) — release 20260714, source file kanji/096fb.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "電",
  code: "096fb",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M34.66,16.19c2.31,0.7,4.78,0.25,7.11-0.04c6.03-0.75,16.15-1.97,23.49-2.76c2.19-0.23,4.03-0.14,6.05,0.1", type: "㇐", start: [34.66, 16.19], end: [71.31, 13.49], dir: -4, endDir: 7, len: 36.9, num: [28.5, 18.5], part: 0 },
    { n: 2, d: "M19.51,29.11c-0.2,5.55-1.93,11.7-3.21,17.3", type: "㇔/㇑", start: [19.51, 29.11], end: [16.3, 46.41], dir: 101, endDir: 103, len: 17.6, num: [12.5, 31.63], part: 0 },
    { n: 3, d: "M20.85,32.18C37.62,30.38,70,25.62,86.4,25.2c9.1-0.24,2.35,6.05-0.78,9.53", type: "㇖b/㇆", start: [20.85, 32.18], end: [85.62, 34.73], dir: 2, endDir: 132, len: 80.9, num: [22.5, 28.5], part: 0 },
    { n: 4, d: "M50.92,17.26c1.1,1.1,1.83,2.49,1.83,3.76c0,3.98-0.16,17.08-0.23,23.73c-0.02,2.1-0.04,3.56-0.04,3.89", type: "㇑", start: [50.92, 17.26], end: [52.48, 48.64], dir: 87, endDir: 90, len: 31.9, num: [45.5, 24.5], part: 0 },
    { n: 5, d: "M32.75,36.46c3.42,0.53,8.09,2.12,9.96,3", type: "㇔", start: [32.75, 36.46], end: [42.71, 39.46], dir: 17, endDir: 25, len: 10.4, num: [26.5, 40.5], part: 0 },
    { n: 6, d: "M31.25,45c3.16,0.57,8.05,2.68,9.77,3.64", type: "㇔", start: [31.25, 45], end: [41.02, 48.64], dir: 20, endDir: 29, len: 10.5, num: [24.5, 47.5], part: 0 },
    { n: 7, d: "M65.5,33.47c3.66,0.79,7.81,2.37,9.28,3.03", type: "㇔", start: [65.5, 33.47], end: [74.78, 36.5], dir: 18, endDir: 24, len: 9.8, num: [59.5, 35.5], part: 0 },
    { n: 8, d: "M65.54,41.89c2.82,0.77,6.67,3.06,8.21,4.34", type: "㇔", start: [65.54, 41.89], end: [73.75, 46.23], dir: 28, endDir: 40, len: 9.3, num: [58.5, 43.5], part: 0 },
    { n: 9, d: "M25.86,55.87c0.89,1.04,1.07,1.52,1.21,2.88c0.47,4.62,2.55,21.84,2.55,22.22c0,0.43,0.19,1.93,0.37,2.79", type: "㇑", start: [25.86, 55.87], end: [29.99, 83.76], dir: 82, endDir: 78, len: 28.4, num: [19.5, 62.5], part: 2 },
    { n: 10, d: "M28.04,57.11c10.79-1,41.49-4.23,43.85-4.37c4.11-0.24,5.36,1.76,4.73,4.82c-0.27,1.31-2.37,9.94-4.05,17.74c-0.2,0.95-0.69,2.39-0.69,3.04", type: "㇕a", start: [28.04, 57.11], end: [71.88, 78.34], dir: 26, endDir: 90, len: 73.7, num: [27.5, 54.5], part: 2 },
    { n: 11, d: "M29.46,68.34c7.42-0.97,36.17-3.47,44.14-3.8", type: "㇐a", start: [29.46, 68.34], end: [73.6, 64.54], dir: -5, endDir: -2, len: 44.3, num: [31.5, 65.5], part: 2 },
    { n: 12, d: "M31.02,80.34C42.25,79,59.5,77.75,71.25,76.75", type: "㇐a", start: [31.02, 80.34], end: [71.25, 76.75], dir: -5, endDir: -5, len: 40.4, num: [31.5, 77.5], part: 2 },
    { n: 13, d: "M48.42,57.62c1.08,1.13,1.45,2.8,1.45,4.78c0,4.85-0.1,12.75-0.1,18.85c0,12.75,1.48,14.5,20.5,14.5c19.23,0,20.18-2.75,20.18-10.82", type: "㇟", start: [48.42, 57.62], end: [90.45, 84.93], dir: 33, endDir: -90, len: 81.6, num: [53.5, 62.5], part: 1 },
  ],
  parts: [
    { element: "雨", position: "top", radical: "general" },
    { position: "bottom" },
    { element: "日", parent: 1 },
  ],
};

export default data;
