/*
 * KanjiVG stroke data for 青 (U+9752) — release 20260714, source file kanji/09752.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "青",
  code: "09752",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M32.13,21.42c1.62,0.38,4.59,0.54,6.21,0.38c9.16-0.92,21.57-2.3,34.18-3.13c2.69-0.18,3.81-0.09,5.23-0.02", type: "㇐", start: [32.13, 21.42], end: [77.75, 18.65], dir: -3, endDir: 3, len: 45.8, num: [25.5, 23.5], part: 0 },
    { n: 2, d: "M52.81,8.63c1.15,1.15,1.76,2.62,1.76,4.42c0,0.43-0.09,28.62-0.07,30.19", type: "㇑a", start: [52.81, 8.63], end: [54.5, 43.24], dir: 87, endDir: 89, len: 35.1, num: [42.75, 9.5], part: 0 },
    { n: 3, d: "M34,33.37c2.39,0.62,4.73,0.4,7.13,0.05c9.07-1.31,22.36-2.96,28.71-3.46c2.21-0.17,3.85-0.08,5.03-0.02", type: "㇐", start: [34, 33.37], end: [74.87, 29.94], dir: -5, endDir: 3, len: 41.1, num: [25.5, 35.5], part: 0 },
    { n: 4, d: "M13.5,47c2.5,0.75,5.8,0.86,8.88,0.55c19.41-1.93,51.54-5.05,65.69-5.8c3.1-0.16,7.07,0,9.3,0.73", type: "㇐", start: [13.5, 47], end: [97.37, 42.48], dir: -3, endDir: 18, len: 84.3, num: [5.5, 48.5], part: 0 },
    { n: 5, d: "M36.26,54.19c1.09,1.09,1.59,2.89,1.59,3.52c0,4.92,0,20.42,0,34.56c0,2.23-0.1,4.11-0.1,6.24", type: "㇑", start: [36.26, 54.19], end: [37.75, 98.51], dir: 88, endDir: 90, len: 44.7, num: [29.5, 61.5], part: 1 },
    { n: 6, d: "M38.2,55.78c0.59-0.03,29.02-2.73,30.58-2.8c2.47-0.11,3.73,0.89,3.73,3.05c0,3.72,0.08,26.23,0.08,38.15c0,10.58-6.97,1.31-7.86,0.57", type: "㇆a", start: [38.2, 55.78], end: [64.73, 94.75], dir: 56, endDir: -140, len: 87.9, num: [39.5, 53.5], part: 1 },
    { n: 7, d: "M39.2,67.61c5.93-0.23,24.72-2.4,32.25-2.4", type: "㇐a", start: [39.2, 67.61], end: [71.45, 65.21], dir: -4, endDir: 0, len: 32.3, num: [41.5, 65.5], part: 1 },
    { n: 8, d: "M39.12,79.23c5.88-0.35,24.26-1.98,32.13-2.31", type: "㇐a", start: [39.12, 79.23], end: [71.25, 76.92], dir: -4, endDir: -2, len: 32.2, num: [41.5, 76.5], part: 1 },
  ],
  parts: [
    { element: "龶", position: "top" },
    { element: "月", position: "bottom" },
  ],
};

export default data;
