/*
 * KanjiVG stroke data for 食 (U+98DF) — release 20260714, source file kanji/098df.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "食",
  code: "098df",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M52.75,10.5c0.11,0.98-0.19,2.67-0.97,3.93C45,25.34,31.75,41.19,14,51.5", type: "㇒", start: [52.75, 10.5], end: [14, 51.5], dir: 133, endDir: 150, len: 57.5, num: [44.25, 10.5] },
    { n: 2, d: "M52.75,16.25c5.09,4.8,25.71,19.61,33.7,24.9c2.68,1.78,5.37,2.79,8.55,3.35", type: "㇏", start: [52.75, 16.25], end: [95, 44.5], dir: 34, endDir: 10, len: 51.2, num: [61.5, 19.63] },
    { n: 3, d: "M52.25,29.25c1,1,1.5,2.25,1.5,3.5c0,2,0,3,0,5.5", type: "㇑a", start: [52.25, 29.25], end: [53.75, 38.25], dir: 81, endDir: 90, len: 9.4, num: [51.5, 26.5] },
    { n: 4, d: "M38,40c0.83,0.47,2.19,1,3.86,0.83c9.39-0.96,21.95-2.76,23.25-2.84c1.67-0.1,3.14,0.88,3.11,2.53C68.2,41.8,67,53.25,66.34,62.4c-0.07,0.94-0.13,1.36-0.13,1.99", type: "㇕", start: [38, 40], end: [66.21, 64.39], dir: 41, endDir: 90, len: 55.9, num: [43.5, 37.5] },
    { n: 5, d: "M40.83,51.73C47.25,51.25,59.5,50,66,49.75", type: "㇐a", start: [40.83, 51.73], end: [66, 49.75], dir: -4, endDir: -2, len: 25.2, num: [43.5, 49.63] },
    { n: 6, d: "M40.69,63.9c7.04-0.52,16.55-1.62,24.6-2.04", type: "㇐a", start: [40.69, 63.9], end: [65.29, 61.86], dir: -5, endDir: -3, len: 24.7, num: [43.5, 61.63] },
    { n: 7, d: "M38.25,40.25c1.12,1.12,1.5,2.62,1.5,4c0,9.12,0,43.62,0,47.25c0,4,1,4.88,4.12,2.88c2.93-1.87,6.75-5.25,10.88-8.38", type: "㇙", start: [38.25, 40.25], end: [54.75, 86], dir: 70, endDir: -37, len: 72.8, num: [32.25, 51.13] },
    { n: 8, d: "M74,64c0.25,1.25,0.09,2.57-0.75,3.5c-3.5,3.88-4.5,4.88-7.25,7.5", type: "㇒", start: [74, 64], end: [66, 75], dir: 126, endDir: 136, len: 14.1, num: [77.5, 63.13] },
    { n: 9, d: "M51.5,71C55.75,71,77,90,81,92.75c2.49,1.71,4.62,2.62,7.5,3.5", type: "㇏", start: [51.5, 71], end: [88.5, 96.25], dir: 34, endDir: 17, len: 45.1, num: [48.5, 78.5] },
  ],
  parts: [

  ],
};

export default data;
