/*
 * KanjiVG stroke data for 飲 (U+98F2) — release 20260714, source file kanji/098f2.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "飲",
  code: "098f2",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M31.53,14.5c0.06,0.73,0.24,1.94-0.12,2.92c-2.96,8.1-11.79,20.97-21.04,27.95", type: "㇒", start: [31.53, 14.5], end: [10.37, 45.37], dir: 124, endDir: 143, len: 38.3, num: [23.25, 16.63], part: 0 },
    { n: 2, d: "M33.5,19.5c5.48,2.15,11.9,6.21,15,10.75", type: "㇔/㇏", start: [33.5, 19.5], end: [48.5, 30.25], dir: 36, endDir: 56, len: 18.7, num: [41.25, 19.63], part: 0 },
    { n: 3, d: "M32.79,32.26c0.85,0.85,1.28,2.38,1.28,3.32c0,3.54-0.08,5.92-0.08,8.2", type: "㇑a", start: [32.79, 32.26], end: [33.99, 43.78], dir: 84, endDir: 90, len: 11.8, num: [31.5, 29.5], part: 0 },
    { n: 4, d: "M20.01,46.32c1.61,0.8,2.86,0.43,4.86,0.03c5.87-1.17,15.18-2.91,16.08-3.04c2.3-0.32,2.98,1.17,2.77,2.63c-0.71,4.9-2.07,13.76-2.78,18.54c-0.27,1.86-0.45,3.1-0.45,3.26", type: "㇕", start: [20.01, 46.32], end: [40.49, 67.74], dir: 46, endDir: 90, len: 48, num: [23.25, 43.05], part: 0 },
    { n: 5, d: "M22.71,57.53c4.17-0.91,13.42-2.41,18.53-3.16", type: "㇐a", start: [22.71, 57.53], end: [41.24, 54.37], dir: -10, endDir: -8, len: 18.8, num: [25.5, 54.13], part: 0 },
    { n: 6, d: "M22.37,68.85c5.51-0.98,11.63-1.73,17.21-2.47", type: "㇐a", start: [22.37, 68.85], end: [39.58, 66.38], dir: -8, endDir: -8, len: 17.4, num: [25.5, 66.13], part: 0 },
    { n: 7, d: "M20.37,47.01c0.69,0.69,1.03,1.8,1.03,2.74c0,5.75-0.29,36.68-0.33,38.97C21,92.75,21.5,93.75,26,90.5c2.1-1.52,7-5,12.5-8.25", type: "㇙", start: [20.37, 47.01], end: [38.5, 82.25], dir: 63, endDir: -31, len: 65.5, num: [14.5, 55.5], part: 0 },
    { n: 8, d: "M37.25,74.25c1.59,2.03,4.09,7.46,5,11.75", type: "㇔/㇏", start: [37.25, 74.25], end: [42.25, 86], dir: 67, endDir: 78, len: 12.8, num: [30.5, 77.5], part: 0 },
    { n: 9, d: "M61.5,14.25c0.25,1.12,0.42,2.14,0.18,3.31C60,25.75,55.82,40.12,49,49.5", type: "㇒", start: [61.5, 14.25], end: [49, 49.5], dir: 110, endDir: 126, len: 37.9, num: [52.5, 14.5], part: 1 },
    { n: 10, d: "M58.22,37.74c1.9,0.39,3.14,0.18,4.51-0.14c1.67-0.39,21.21-5.25,22.76-5.6c6.75-1.5,3.5,4.5-3,11.25", type: "㇖a", start: [58.22, 37.74], end: [82.49, 43.25], dir: 13, endDir: 134, len: 44.8, num: [62.5, 34.5], part: 1 },
    { n: 11, d: "M64.85,47.5c0.78,1.5,0.86,2.88,0.62,4.52C63,68.62,57.25,84.5,42.25,95.75", type: "㇒", start: [64.85, 47.5], end: [42.25, 95.75], dir: 115, endDir: 143, len: 55.5, num: [54.5, 53.5], part: 1 },
    { n: 12, d: "M65.42,60.5c3.56,6.77,15.26,21.56,22.62,29.46c1.89,2.03,3.98,4.66,6.71,5.54", type: "㇏", start: [65.42, 60.5], end: [94.75, 95.5], dir: 50, endDir: 18, len: 46, num: [69.5, 64.5], part: 1 },
  ],
  parts: [
    { element: "飠", position: "left", radical: "general" },
    { element: "欠", position: "right" },
  ],
};

export default data;
