/*
 * KanjiVG stroke data for 駅 (U+99C5) — release 20260714, source file kanji/099c5.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "駅",
  code: "099c5",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M16.24,17.12c0.76,0.63,1.5,1.69,1.49,2.88c-0.04,7.8-0.57,24.25-0.67,34.5c-0.02,2.35,0.09,3.32-0.31,5.75", type: "㇑", start: [16.24, 17.12], end: [16.75, 60.25], dir: 89, endDir: 99, len: 43.6, num: [10.5, 26.5], part: 0 },
    { n: 2, d: "M18.23,18.15c4.39-0.65,17.37-2.21,22.41-2.87c1.63-0.21,3.26-0.51,4.9-0.21", type: "㇐b", start: [18.23, 18.15], end: [45.54, 15.07], dir: -6, endDir: 10, len: 27.5, num: [16.5, 14.5], part: 0 },
    { n: 3, d: "M30.31,17.82c0.49,0.49,0.95,1.46,0.95,2.49c0,6.17-0.25,26.44-0.25,35.66", type: "㇑a", start: [30.31, 17.82], end: [31.01, 55.97], dir: 89, endDir: 90, len: 38.4, num: [33.5, 24.5], part: 0 },
    { n: 4, d: "M18.41,32.09c5.46-0.51,16.44-2.11,21.13-2.77c1.19-0.17,3.34-0.57,4.56-0.25", type: "㇐b", start: [18.41, 32.09], end: [44.1, 29.07], dir: -7, endDir: 15, len: 25.9, num: [20.25, 28.63], part: 0 },
    { n: 5, d: "M18.51,44.88c5.61-0.52,16.7-1.95,21.02-2.57c1.15-0.17,3.05-0.71,4.17-0.2", type: "㇐b", start: [18.51, 44.88], end: [43.7, 42.11], dir: -6, endDir: 24, len: 25.4, num: [20.43, 42.13], part: 0 },
    { n: 6, d: "M17.74,59.65c6.17-1.41,20.29-4.04,23.68-4.63c4.33-0.76,4.19,2.81,3.95,6.45C44.7,71.81,42.59,83.13,39.75,90c-3,7.25-5.62,1.62-7.21-0.86", type: "㇆a", start: [17.74, 59.65], end: [32.54, 89.14], dir: 63, endDir: -123, len: 73.9, num: [20.29, 55.63], part: 0 },
    { n: 7, d: "M9.79,73.5c0.28,6.41-0.57,12.04-0.87,13.32", type: "㇔", start: [9.79, 73.5], end: [8.92, 86.82], dir: 94, endDir: 103, len: 13.4, num: [4.5, 72.5], part: 1 },
    { n: 8, d: "M17.5,71.5c1.08,2.1,2,4.75,2.25,8.5", type: "㇔", start: [17.5, 71.5], end: [19.75, 80], dir: 75, endDir: 86, len: 8.9, num: [11.25, 70.5], part: 1 },
    { n: 9, d: "M25.44,68.22C26,69.25,28,72.64,28.25,76", type: "㇔", start: [25.44, 68.22], end: [28.25, 76], dir: 70, endDir: 86, len: 8.3, num: [19.25, 67.5], part: 1 },
    { n: 10, d: "M32.75,65.25c1.25,2.01,3.3,4.09,3.75,6.75", type: "㇔", start: [32.75, 65.25], end: [36.5, 72], dir: 61, endDir: 80, len: 7.8, num: [24.5, 65.5], part: 1 },
    { n: 11, d: "M55.22,20.32c1.16,0.77,2.9,0.9,4.14,0.79c7.4-0.61,19.18-2.64,21.85-2.97c3.3-0.4,4.77,1.69,4.42,3.94C84.97,26.2,83.6,34.25,82,40.32", type: "㇕c", start: [55.22, 20.32], end: [82, 40.32], dir: 37, endDir: 105, len: 52, num: [58.5, 16.5], part: 3 },
    { n: 12, d: "M58.61,44.25c3.51-0.38,13.46-1.53,20.43-2.42c2.36-0.3,3.58-0.33,5.1-0.09", type: "㇐b", start: [58.61, 44.25], end: [84.14, 41.74], dir: -6, endDir: 9, len: 25.7, num: [60.5, 40.63], part: 3 },
    { n: 13, d: "M56.84,21.12c0.91,0.88,1.04,2.43,1.05,3.38c0.67,41.32-3.54,54.77-10.14,66.5", type: "㇒", start: [56.84, 21.12], end: [47.75, 91], dir: 97, endDir: 119, len: 71.7, num: [47.5, 27.5], part: 4 },
    { n: 14, d: "M64.28,44.75c5.1,9.38,16.09,30.23,25.17,40.55c2.13,2.42,4.99,5.29,8.05,6.45", type: "㇏", start: [64.28, 44.75], end: [97.5, 91.75], dir: 55, endDir: 21, len: 58.2, num: [71.5, 54.5], part: 5 },
  ],
  parts: [
    { element: "馬", position: "left", radical: "general" },
    { element: "灬", parent: 0 },
    { element: "尺", position: "right" },
    { element: "尸", parent: 2 },
    { element: "八", part: "1", parent: 3 },
    { element: "八", part: "2", parent: 2 },
  ],
};

export default data;
