/*
 * KanjiVG stroke data for 高 (U+9AD8) — release 20260714, source file kanji/09ad8.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "高",
  code: "09ad8",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M52.47,11.75c1.08,1.08,1.48,2.25,1.48,4.22c0,1.53-0.12,4.28-0.12,5.45", type: "㇑a", start: [52.47, 11.75], end: [53.83, 21.42], dir: 82, endDir: 90, len: 10.1, num: [44.25, 10.63], part: 1 },
    { n: 2, d: "M22.9,25.7c2.68,0.3,4.96,0.26,7.47-0.04c14.76-1.78,35.83-4.16,49.3-5.17c2.89-0.22,4.99-0.12,6.81,0.33", type: "㇐", start: [22.9, 25.7], end: [86.48, 20.82], dir: -4, endDir: 14, len: 63.9, num: [14.25, 25.5], part: 1 },
    { n: 3, d: "M36.25,34.75c1,0.63,1.5,1.5,1.78,2.89c0.72,3.59,1.36,7.37,2.05,11.85c0.2,1.3,0.17,1.82,0.44,3.01", type: "㇑", start: [36.25, 34.75], end: [40.52, 52.5], dir: 76, endDir: 77, len: 18.6, num: [27.75, 37.63], part: 2 },
    { n: 4, d: "M39.05,36.33c9.95-1.71,23.99-3.65,29.61-4.1c2.96-0.23,3.83,1.02,3.14,3.31c-0.88,2.93-2.17,7.01-3.32,10.2", type: "㇕b", start: [39.05, 36.33], end: [68.48, 45.74], dir: 18, endDir: 110, len: 46.5, num: [39.75, 33.13], part: 2 },
    { n: 5, d: "M41.28,49.94c6.57-0.42,16.36-1.87,25.72-2.71c1.3-0.12,2.59-0.22,3.85-0.31", type: "㇐b", start: [41.28, 49.94], end: [70.85, 46.92], dir: -6, endDir: -4, len: 29.7, num: [44.25, 46.63], part: 2 },
    { n: 6, d: "M21,60.25c1.31,1.31,1.9,2.76,2.21,5c0.79,5.62,2.21,18.19,3.16,26.99c0.15,1.39,0.28,2.67,0.38,3.76", type: "㇑", start: [21, 60.25], end: [26.75, 96], dir: 81, endDir: 85, len: 36.5, num: [14.25, 69.13], part: 4 },
    { n: 7, d: "M24.06,64c16.08-1.51,58.63-6.55,60.19-6.75c3.75-0.5,6,1.5,5.25,6.25c-1.49,9.45-2.62,19.62-5.25,28.25c-2.05,6.75-5.38,2.5-7.8,0", type: "㇆a", start: [24.06, 64], end: [76.45, 91.75], dir: 28, endDir: -134, len: 110.5, num: [29.25, 58.63], part: 4 },
    { n: 8, d: "M41.5,71.68c0.66,0.66,1.16,1.63,1.31,2.47c0.89,2.82,1.58,7.24,2.39,11.81c0.21,1.16,0.4,1.78,0.56,2.79", type: "㇑", start: [41.5, 71.68], end: [45.76, 88.75], dir: 76, endDir: 81, len: 17.7, num: [35.25, 79.63], part: 5 },
    { n: 9, d: "M44.02,73.08c6.79-1.36,17.1-2.86,20.92-3.35c1.81-0.23,3.31,1.02,3.13,2.5c-0.35,2.92-1.96,8.31-3.12,11.75", type: "㇕b", start: [44.02, 73.08], end: [64.95, 83.98], dir: 28, endDir: 109, len: 38, num: [44.25, 70.63], part: 5 },
    { n: 10, d: "M46.44,87.05c4.61-0.4,11.01-1.31,17.32-1.94c0.88-0.09,1.77-0.17,2.65-0.26", type: "㇐b", start: [46.44, 87.05], end: [66.41, 84.85], dir: -6, endDir: -6, len: 20.1, num: [47.25, 84.13], part: 5 },
  ],
  parts: [
    { position: "top" },
    { element: "亠", parent: 0 },
    { element: "口", parent: 0 },
    { element: "冋", position: "bottom" },
    { element: "冂", parent: 3 },
    { element: "口", parent: 3 },
  ],
};

export default data;
