/*
 * KanjiVG stroke data for 魚 (U+9B5A) — release 20260714, source file kanji/09b5a.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "魚",
  code: "09b5a",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M48,13c0.14,1.21-0.07,2.22-0.59,3.32C45.08,21.29,37,30.31,26.25,36", type: "㇒", start: [48, 13], end: [26.25, 36], dir: 133, endDir: 152, len: 32.7, num: [39.5, 13.5], part: 0 },
    { n: 2, d: "M49,19.13c1.25,0.37,2.35,0.4,3.8,0.24c4.73-0.53,10.95-1.37,14.14-2.13c2.5-0.6,3.69,1.64,2.06,3.51c-4.94,5.7-9.5,11.12-14.25,17.25", type: "㇇", start: [49, 19.13], end: [54.75, 38], dir: 73, endDir: 128, len: 46.3, num: [53.5, 15.13], part: 0 },
    { n: 3, d: "M27.49,40.98c1.2,1.2,1.88,2.4,2.11,3.82c0.85,5.2,2.43,14.61,3.41,22.71c0.17,1.36,0.32,2.69,0.47,3.96", type: "㇑", start: [27.49, 40.98], end: [33.48, 71.47], dir: 79, endDir: 83, len: 31.4, num: [21.75, 49.5], part: 2 },
    { n: 4, d: "M30.27,42.78C45.25,40.62,67,37.75,78.41,37.3c3.85-0.15,5.83,1.46,5.59,3.95c-0.5,5.12-1.85,15.04-3.39,23.73c-0.2,1.15-0.41,2.25-0.61,3.27", type: "㇕a", start: [30.27, 42.78], end: [80, 68.25], dir: 27, endDir: 101, len: 83.7, num: [34.5, 39.13], part: 2 },
    { n: 5, d: "M53.75,41.5c1,0.75,1.12,1.88,1.16,2.98C55.13,50.39,55,65.45,55,66.25", type: "㇑a", start: [53.75, 41.5], end: [55, 66.25], dir: 87, endDir: 90, len: 25.1, num: [47.5, 49.5], part: 2 },
    { n: 6, d: "M32.47,55.61C43.5,54.38,69.88,52,81.21,51.64", type: "㇐a", start: [32.47, 55.61], end: [81.21, 51.64], dir: -5, endDir: -2, len: 48.9, num: [34, 52.63], part: 2 },
    { n: 7, d: "M34.2,69.54c12.92-1.29,30.42-3.04,45.8-3.79", type: "㇐a", start: [34.2, 69.54], end: [80, 65.75], dir: -5, endDir: -3, len: 46, num: [35.5, 66.13], part: 2 },
    { n: 8, d: "M26.25,81c0,5.25-5.75,13-7.25,14.5", type: "㇔", start: [26.25, 81], end: [19, 95.5], dir: 117, endDir: 135, len: 16.5, num: [20.25, 79.5], part: 3 },
    { n: 9, d: "M42.52,79.08c3.15,2.76,6.15,10.84,6.94,15.13", type: "㇔", start: [42.52, 79.08], end: [49.46, 94.21], dir: 65, endDir: 80, len: 16.8, num: [35.5, 79.5], part: 3 },
    { n: 10, d: "M62.37,77.83c3.15,2.76,8.15,11.34,8.93,15.63", type: "㇔", start: [62.37, 77.83], end: [71.3, 93.46], dir: 60, endDir: 80, len: 18.2, num: [52.5, 79.5], part: 3 },
    { n: 11, d: "M84.27,78.58c4.16,2.63,10.75,10.8,11.79,14.88", type: "㇔", start: [84.27, 78.58], end: [96.06, 93.46], dir: 52, endDir: 76, len: 19.2, num: [74.5, 79.5], part: 3 },
  ],
  parts: [
    { element: "𠂊", position: "top" },
    { position: "bottom" },
    { element: "田", parent: 1 },
    { element: "灬", parent: 1 },
  ],
};

export default data;
