/*
 * KanjiVG stroke data for 黒 (U+9ED2) — release 20260714, source file kanji/09ed2.svg
 * Copyright (C) 2009-2011 Ulrich Apel and the KanjiVG contributors — https://kanjivg.tagaini.net
 * Licensed CC BY-SA 3.0: https://creativecommons.org/licenses/by-sa/3.0/
 * Adapted for Astra: path data copied verbatim; start/end points, directions, lengths and
 * label positions were computed from it. This file remains under CC BY-SA 3.0 (see ../NOTICE.md).
 * GENERATED by scripts/build-kanji-strokes.ts — do not edit by hand.
 */
import type { KanjiStrokeData } from "../types";

const data: KanjiStrokeData = {
  kanji: "黒",
  code: "09ed2",
  release: "20260714",
  viewBox: 109,
  strokes: [
    { n: 1, d: "M29.11,18.41c0.8,0.8,1.14,1.84,1.4,3.33c1.05,6.1,2.44,15.14,3.45,22.03c0.2,1.34,0.38,2.59,0.54,3.73", type: "㇑", start: [29.11, 18.41], end: [34.5, 47.5], dir: 80, endDir: 82, len: 29.7, num: [20.25, 27.13], part: 1 },
    { n: 2, d: "M31.26,20.14c14.95-1.85,32.51-3.41,46.55-4.69c3.6-0.33,4.93,2.06,4.76,3.76c-0.35,3.51-2.57,13.12-4.73,20.58c-0.5,1.74-0.77,2.63-1.27,4.07", type: "㇕a", start: [31.26, 20.14], end: [76.57, 43.86], dir: 28, endDir: 109, len: 79.2, num: [35.25, 16.63], part: 1 },
    { n: 3, d: "M33.82,32.24c6.81-0.74,37.68-3.74,45.65-3.91", type: "㇐a", start: [33.82, 32.24], end: [79.47, 28.33], dir: -5, endDir: -1, len: 45.8, num: [38.25, 28.63], part: 1 },
    { n: 4, d: "M35.47,43.91c11.53-1.16,28.06-3.11,41.12-3.86", type: "㇐a", start: [35.47, 43.91], end: [76.59, 40.05], dir: -5, endDir: -3, len: 41.3, num: [38.25, 40.5], part: 1 },
    { n: 5, d: "M53.29,19.56c0.98,0.93,1.45,1.98,1.49,3.11C55.14,32.86,55.05,57.6,55,67.75", type: "㇑a", start: [53.29, 19.56], end: [55, 67.75], dir: 88, endDir: 90, len: 48.6, num: [58.62, 25.38], part: 0 },
    { n: 6, d: "M33.88,57.14c1.48,0.28,4.2,0.38,5.68,0.28c9.66-0.67,21.01-2.54,32.19-3.22c2.46-0.15,3.95,0.13,5.19,0.27", type: "㇐", start: [33.88, 57.14], end: [76.94, 54.47], dir: -4, endDir: 6, len: 43.3, num: [27.12, 57], part: 0 },
    { n: 7, d: "M20.63,70.47c2.16,0.4,6.14,0.56,8.29,0.4c18.27-1.37,34.62-3,52.13-3.34c3.6-0.07,5.77,0.19,7.57,0.39", type: "㇐", start: [20.63, 70.47], end: [88.62, 67.92], dir: -2, endDir: 6, len: 68.1, num: [15, 70.5], part: 0 },
    { n: 8, d: "M24.75,81.88c-1.27,6.05-7.36,13.11-9,14.62", type: "㇔", start: [24.75, 81.88], end: [15.75, 96.5], dir: 122, endDir: 137, len: 17.4, num: [17.25, 82.63], part: 2 },
    { n: 9, d: "M42,79.5c1.71,2.87,4.25,10.5,3.76,15.25", type: "㇔", start: [42, 79.5], end: [45.76, 94.75], dir: 76, endDir: 96, len: 15.9, num: [35.25, 82.63], part: 2 },
    { n: 10, d: "M62.75,78.5c2.65,2.69,6.5,10.5,6.5,15.25", type: "㇔", start: [62.75, 78.5], end: [69.25, 93.75], dir: 67, endDir: 90, len: 16.8, num: [52.5, 80.5], part: 2 },
    { n: 11, d: "M83.71,79.08c4.27,2.63,11.03,10.8,12.1,14.88", type: "㇔", start: [83.71, 79.08], end: [95.81, 93.96], dir: 51, endDir: 75, len: 19.4, num: [73.5, 79.63], part: 2 },
  ],
  parts: [
    { element: "里", position: "top" },
    { element: "日", parent: 0 },
    { element: "灬", position: "bottom" },
  ],
};

export default data;
