import type { KanjiWordEntry } from "./types";

export const KANJI_WORD_FAMILIES: Record<string, KanjiWordEntry[]> = {
  "生": [
    { word: "先生", reading: "せんせい", meaning: "Teacher", kanjiReading: "せい", readingType: "onyomi", commonness: "common" },
    { word: "生きる", reading: "いきる", meaning: "To live", kanjiReading: "い", readingType: "kunyomi", commonness: "common" },
    { word: "生", reading: "なま", meaning: "Raw / fresh / live", kanjiReading: "なま", readingType: "kunyomi", commonness: "common" },
    { word: "生まれる", reading: "うまれる", meaning: "To be born", kanjiReading: "う", readingType: "kunyomi", commonness: "common" },
    { word: "誕生", reading: "たんじょう", meaning: "Birth", kanjiReading: "じょう", readingType: "onyomi-variant", note: "生 has a second onyomi ショウ, which voices to じょう here — different from the セイ you see in 先生.", commonness: "common" },
    { word: "一生", reading: "いっしょう", meaning: "One's whole life", kanjiReading: "しょう", readingType: "onyomi-variant", note: "Same secondary onyomi ショウ as in 誕生, here unvoiced and doubled before the small っ.", commonness: "common" },
  ],
  "上": [
    { word: "上手", reading: "じょうず", meaning: "Skilled", kanjiReading: "じょう", readingType: "onyomi", commonness: "common" },
    { word: "上", reading: "うえ", meaning: "Above / on top", kanjiReading: "うえ", readingType: "kunyomi", commonness: "common" },
    { word: "上げる", reading: "あげる", meaning: "To raise", kanjiReading: "あ", readingType: "kunyomi", commonness: "common" },
    { word: "上る", reading: "のぼる", meaning: "To climb / go up", kanjiReading: "のぼ", readingType: "kunyomi", note: "A separate kunyomi from あげる — this one is about ascending (stairs, a mountain), not lifting something.", commonness: "common" },
    { word: "上着", reading: "うわぎ", meaning: "Jacket / outerwear", kanjiReading: "うわ", readingType: "kunyomi", note: "うわ is a reading of 上 that only shows up in a handful of compounds like this one.", commonness: "moderate" },
    { word: "屋上", reading: "おくじょう", meaning: "Rooftop", kanjiReading: "じょう", readingType: "onyomi", commonness: "common" },
  ],
  "下": [
    { word: "下手", reading: "へた", meaning: "Unskilled", kanjiReading: "へ", readingType: "irregular", note: "A special whole-word reading (jukujikun) — 下 doesn't normally read as へ on its own.", commonness: "common" },
    { word: "下", reading: "した", meaning: "Below / under", kanjiReading: "した", readingType: "kunyomi", commonness: "common" },
    { word: "下がる", reading: "さがる", meaning: "To go down / descend", kanjiReading: "さ", readingType: "kunyomi", commonness: "common" },
    { word: "地下", reading: "ちか", meaning: "Underground", kanjiReading: "か", readingType: "onyomi", commonness: "common" },
    { word: "下車", reading: "げしゃ", meaning: "Getting off (a train/bus)", kanjiReading: "げ", readingType: "onyomi", note: "Uses the less common of 下's two onyomi (ゲ) instead of カ.", commonness: "common" },
    { word: "下さい", reading: "ください", meaning: "Please give me", kanjiReading: "くだ", readingType: "kunyomi", note: "くだ-さい is yet another kunyomi, distinct from した and さげる.", commonness: "common" },
  ],
  "中": [
    { word: "中学校", reading: "ちゅうがっこう", meaning: "Junior high school", kanjiReading: "ちゅう", readingType: "onyomi", commonness: "common" },
    { word: "中", reading: "なか", meaning: "Middle / inside", kanjiReading: "なか", readingType: "kunyomi", commonness: "common" },
    { word: "一日中", reading: "いちにちじゅう", meaning: "All day long", kanjiReading: "じゅう", readingType: "onyomi-variant", note: "In time-span words like this, 中 voices from ちゅう to じゅう.", commonness: "common" },
    { word: "世界中", reading: "せかいじゅう", meaning: "All over the world", kanjiReading: "じゅう", readingType: "onyomi-variant", note: "Same じゅう pattern as 一日中, used for 'throughout' rather than a strict time duration.", commonness: "moderate" },
  ],
  "分": [
    { word: "分かる", reading: "わかる", meaning: "To understand", kanjiReading: "わ", readingType: "kunyomi", commonness: "common" },
    { word: "五分", reading: "ごふん", meaning: "Five minutes", kanjiReading: "ふん", readingType: "onyomi", commonness: "common" },
    { word: "自分", reading: "じぶん", meaning: "Oneself", kanjiReading: "ぶん", readingType: "onyomi", commonness: "common" },
    { word: "分ける", reading: "わける", meaning: "To divide", kanjiReading: "わ", readingType: "kunyomi", commonness: "common" },
    { word: "五分五分", reading: "ごぶごぶ", meaning: "Fifty-fifty / even odds", kanjiReading: "ぶ", readingType: "onyomi-variant", note: "ぶ is a third onyomi for 分, separate from ぶん and ふん, used in ratio/proportion words.", commonness: "moderate" },
  ],
  "気": [
    { word: "元気", reading: "げんき", meaning: "Healthy / energetic", kanjiReading: "き", readingType: "onyomi", commonness: "common" },
    { word: "天気", reading: "てんき", meaning: "Weather", kanjiReading: "き", readingType: "onyomi", commonness: "common" },
    { word: "気配", reading: "けはい", meaning: "Sign / indication", kanjiReading: "け", readingType: "onyomi-variant", note: "気 has a rarer second onyomi ケ, heard here instead of the usual キ.", commonness: "common" },
    { word: "気持ち", reading: "きもち", meaning: "Feeling", kanjiReading: "き", readingType: "onyomi", commonness: "common" },
  ],
  "会": [
    { word: "会う", reading: "あう", meaning: "To meet", kanjiReading: "あ", readingType: "kunyomi", commonness: "common" },
    { word: "会社", reading: "かいしゃ", meaning: "Company", kanjiReading: "かい", readingType: "onyomi", commonness: "common" },
    { word: "出会う", reading: "であう", meaning: "To encounter / run into", kanjiReading: "あ", readingType: "kunyomi", commonness: "common" },
    { word: "会釈", reading: "えしゃく", meaning: "A slight bow / nod of greeting", kanjiReading: "え", readingType: "onyomi-variant", note: "A rare onyomi エ that shows up in almost no other word besides this one and 会得 (えとく).", commonness: "rare" },
  ],
  "行": [
    { word: "行く", reading: "いく", meaning: "To go", kanjiReading: "い", readingType: "kunyomi", commonness: "common" },
    { word: "行う", reading: "おこなう", meaning: "To carry out / conduct", kanjiReading: "おこな", readingType: "kunyomi", commonness: "common" },
    { word: "行動", reading: "こうどう", meaning: "Action / behavior", kanjiReading: "こう", readingType: "onyomi", commonness: "common" },
    { word: "行事", reading: "ぎょうじ", meaning: "Event / function", kanjiReading: "ぎょう", readingType: "onyomi-variant", note: "行's second onyomi ギョウ, common in words about ceremonies and scheduled events.", commonness: "common" },
  ],
  "今": [
    { word: "今", reading: "いま", meaning: "Now", kanjiReading: "いま", readingType: "kunyomi", commonness: "common" },
    { word: "今日", reading: "きょう", meaning: "Today", kanjiReading: "きょう", readingType: "irregular", note: "A very common irregular combination (jukujikun) that you'll use daily!", commonness: "common" },
    { word: "今月", reading: "こんげつ", meaning: "This month", kanjiReading: "こん", readingType: "onyomi", commonness: "common" },
    { word: "今週", reading: "こんしゅう", meaning: "This week", kanjiReading: "こん", readingType: "onyomi", commonness: "common" },
    { word: "今年", reading: "ことし", meaning: "This year", kanjiReading: "ことし", readingType: "irregular", note: "Another jukujikun reading. Normal readings of 今 and 年 don't combine this way.", commonness: "common" },
    { word: "今回", reading: "こんかい", meaning: "This time", kanjiReading: "こん", readingType: "onyomi", commonness: "common" },
  ],
  "日": [
    { word: "日本", reading: "にほん", meaning: "Japan", kanjiReading: "に", readingType: "onyomi-variant", note: "Here, 日 changes to に as a sound shift before ほん.", commonness: "common" },
    { word: "毎日", reading: "まいにち", meaning: "Every day", kanjiReading: "にち", readingType: "onyomi", commonness: "common" },
    { word: "日曜日", reading: "にちようび", meaning: "Sunday", kanjiReading: "にち", readingType: "onyomi", commonness: "common" },
    { word: "今日", reading: "きょう", meaning: "Today", kanjiReading: "きょう", readingType: "irregular", note: "Irregular jukujikun reading. Super critical to learn first!", commonness: "common" },
    { word: "日記", reading: "にっき", meaning: "Diary", kanjiReading: "にっ", readingType: "onyomi-variant", note: "The sound doubles (sokuon) into にっ before き.", commonness: "common" },
    { word: "お日様", reading: "おひさま", meaning: "The sun (polite)", kanjiReading: "ひ", readingType: "kunyomi", commonness: "common" },
  ],
  "月": [
    { word: "月曜日", reading: "げつようび", meaning: "Monday", kanjiReading: "げつ", readingType: "onyomi", commonness: "common" },
    { word: "今月", reading: "こんげつ", meaning: "This month", kanjiReading: "げつ", readingType: "onyomi", commonness: "common" },
    { word: "一月", reading: "いちがつ", meaning: "January", kanjiReading: "がつ", readingType: "onyomi-variant", note: "Months of the year use the がつ reading instead of げつ.", commonness: "common" },
    { word: "三ヶ月", reading: "さんかげつ", meaning: "Three months (duration)", kanjiReading: "げつ", readingType: "onyomi", commonness: "common" },
    { word: "月", reading: "つき", meaning: "The moon / moon phase", kanjiReading: "つき", readingType: "kunyomi", commonness: "common" },
  ],
  "木": [
    { word: "木", reading: "き", meaning: "Tree / wood", kanjiReading: "き", readingType: "kunyomi", commonness: "common" },
    { word: "木曜日", reading: "もくようび", meaning: "Thursday", kanjiReading: "もく", readingType: "onyomi", commonness: "common" },
    { word: "大木", reading: "たいぼく", meaning: "Huge tree / old timber", kanjiReading: "ぼく", readingType: "onyomi-variant", note: "Uses the secondary onyomi ボク instead of モク.", commonness: "moderate" },
    { word: "木刀", reading: "ぼくとう", meaning: "Wooden sword / training blade", kanjiReading: "ぼく", readingType: "onyomi-variant", commonness: "moderate" },
  ],
  "水": [
    { word: "水曜日", reading: "すいようび", meaning: "Wednesday", kanjiReading: "すい", readingType: "onyomi", commonness: "common" },
    { word: "水", reading: "みず", meaning: "Water", kanjiReading: "みず", readingType: "kunyomi", commonness: "common" },
    { word: "海水", reading: "かいすい", meaning: "Seawater", kanjiReading: "すい", readingType: "onyomi", commonness: "common" },
    { word: "水着", reading: "みずぎ", meaning: "Swimsuit / swimwear", kanjiReading: "みず", readingType: "kunyomi", commonness: "common" },
  ],
};
